### ISSUE TITLE
关于仓库地址问题

### ISSUE THREAD

**Issue by peterzhang41** [zq1997/deepin-wine#1]
wszqkzqk仓库是https://mirrors.aliyun.com/
为什么你的是清华？ 你是说清华的会301到官网？

**Comment by zq1997** [comment]
真正的官网在这里[http://packages.deepin.com/](http://packages.deepin.com/deepin/pool/non-free/d/)，我在这个地址下载贼慢，不知道你那边情况这么样。清华镜像速度快而且同步很及时，wszqkzqk用阿里云估计也是一个道理，然后我本人是教育网，清华镜像下载速度有十几兆，就用了这个。

清华镜像还是挺靠谱的，应该不会出现篡改软件包这种骚操作，所以说是官方原版软件包。

**Comment by peterzhang41** [comment]
好的

**Comment by CescMessi** [comment]
我这里清华源非常慢，阿里和官方的倒是很快，有没有可能根据IP分配源？或者给个官方源的选项

**Comment by zq1997** [comment]
只能用一个源，以后我改成用阿里云吧，没想到清华的源会在部分地区这么慢
