### ISSUE TITLE
安装TIM之后中文无法显示呢？ 这边是wine的配置问题吗？

### ISSUE THREAD

**Issue by liguobao** [zq1997/deepin-wine#10]

**Comment by zq1997** [comment]
有好多close了的issue提到了这个问题，可以先尝试一下他们的解决方法。
因为字体的问题原因太杂了，解决方案还真没一个通用的

**Comment by liguobao** [comment]
系统语言切换到中文后正常显示， 但是微信输入框炸了， 显示的是黑色方块。。。

**Comment by liguobao** [comment]
https://github.com/wszqkzqk/deepin-wine-ubuntu/issues/136

参考这里解决了。

**Comment by MakerFace** [comment]
> 系统语言切换到中文后正常显示， 但是微信输入框炸了， 显示的是黑色方块。。。

ubuntu 20.04，切换中文正常，微信也正常。
