### ISSUE TITLE
com.qq.im.deepin 无法登录，并且卡死

### ISSUE THREAD

**Issue by YaoLaiGang** [zq1997/deepin-wine#100]
频繁报错：RasEnumConnectionsW RAS support is not implemented!
不知是否缺少依赖。另外已经设置了代理。

**Comment by function2-llx** [comment]
唔，我之前一直用的 TIM，然后这次更新到 V20 后没有 TIM 了，装了 QQ，也是无法登录（输入账号密码点登录后卡死，或者点扫描二维码也会卡死）；现在想知道怎么才能找到之前的 TIM 的 deb 包（

**Comment by zq1997** [comment]
装了windows字体？

**Comment by YaoLaiGang** [comment]
是的，好像是这个问题。我从深度论坛下了一个修改版之后就可以正常使用了。



---原始邮件---
发件人: "zq1997"<notifications@github.com&gt;
发送时间: 2020年11月22日(周日) 中午12:54
收件人: "zq1997/deepin-wine"<deepin-wine@noreply.github.com&gt;;
抄送: "Author"<author@noreply.github.com&gt;;"残桥断雪"<2046682604@qq.com&gt;;
主题: Re: [zq1997/deepin-wine] com.qq.im.deepin 无法登录，并且卡死 (#100)




 
装了windows字体？

**Comment by zq1997** [comment]
把windows字体所在目录软链接加入wine容器的C:\Windows\Fonts目录里去就行

**Comment by YaoLaiGang** [comment]
> 把windows字体所在目录软链接加入wine容器的C:\Windows\Fonts目录里去就行

[具体方案是替换dwrite.dll文件](dwrite)

**Comment by YaoLaiGang** [comment]
> 把windows字体所在目录软链接加入wine容器的C:\Windows\Fonts目录里去就行

[具体方案是替换dwrite.dll文件](https://bbs.deepin.org/post/201598)

**Comment by YaoLaiGang** [comment]
> 把windows字体所在目录软链接加入wine容器的C:\Windows\Fonts目录里去就行

我用替换字体也可以解决此问题：
此时解决方案是把 win 的宋体的 ttc 文件往 QQ 的 wine 容器里也装一份（即复制到 ~/.deepinwine/Deepin-QQ/drive_c/Windows/Fonts 里)，此时 QQ 不再使用宋体里的点阵字体，也基本不会卡死了。
