### ISSUE TITLE
Cannot install com.qq.weixin.deepin because of libc6 version

### ISSUE THREAD

**Issue by zoukyle** [zq1997/deepin-wine#103]
Cannot install because of libc6 version.

Ubuntu 18.04
Linux 5.4.0-54-generic #60~18.04.1-Ubuntu SMP Fri Nov 6 17:25:16 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

sudo apt-get install com.qq.weixin.deepin
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 com.qq.weixin.deepin:i386 : Depends: libc6:i386 (>= 2.28) but 2.27-3ubuntu1.3 is to be installed
                             Recommends: libcapi20-3:i386 but it is not going to be installed
                             Recommends: libcups2:i386 but it is not going to be installed
                             Recommends: libglu1-mesa:i386 but it is not going to be installed or
                                         libglu1:i386
                             Recommends: libgsm1:i386 but it is not going to be installed
                             Recommends: libgssapi-krb5-2:i386 but it is not going to be installed
                             Recommends: libkrb5-3:i386 but it is not going to be installed
                             Recommends: libodbc1:i386 but it is not going to be installed
                             Recommends: libosmesa6:i386 but it is not going to be installed
                             Recommends: libsane:i386 or
                                         libsane1:i386 but it is not going to be installed
                             Recommends: libsdl2-2.0-0:i386 but it is not going to be installed
                             Recommends: libv4l-0:i386 but it is not going to be installed
                             Recommends: libxcomposite1:i386 but it is not going to be installed
                             Recommends: libxcursor1:i386 but it is not going to be installed
                             Recommends: libxfixes3:i386 but it is not going to be installed
                             Recommends: libxi6:i386 but it is not going to be installed
                             Recommends: libxinerama1:i386 but it is not going to be installed
                             Recommends: libxrandr2:i386 but it is not going to be installed
                             Recommends: libxrender1:i386 but it is not going to be installed
                             Recommends: libxslt1.1:i386 but it is not going to be installed
                             Recommends: libxxf86vm1:i386 but it is not going to be installed
E: Unable to correct problems, you have held broken packages.

**Comment by Baloneo** [comment]
same problem

**Comment by Baloneo** [comment]
I try to install version libc:1386:2.28
```
➜  chrome-download sudo dpkg -i libc6-i386_2.31-0ubuntu9.1_amd64.deb
Selecting previously unselected package libc6-i386.
(Reading database ... 732986 files and directories currently installed.)
Preparing to unpack libc6-i386_2.31-0ubuntu9.1_amd64.deb ...
Unpacking libc6-i386 (2.31-0ubuntu9.1) ...
Replaced by files in installed package libc6:i386 (2.27-3ubuntu1.3) ...
dpkg: dependency problems prevent configuration of libc6-i386:
 libc6-i386 depends on libc6 (= 2.31-0ubuntu9.1); however:
  Version of libc6:amd64 on system is 2.27-3ubuntu1.3.

dpkg: error processing package libc6-i386 (--install):
 dependency problems - leaving unconfigured
Processing triggers for libc-bin (2.27-3ubuntu1.3) ...
Errors were encountered while processing:
 libc6-i386

```
but need upgrade libc6:amd64, if ichange, I think this will affect my system dependency package
`Version of libc6:amd64 on system is 2.27-3ubuntu1.3.
`

**Comment by zq1997** [comment]
https://github.com/zq1997/deepin-wine/issues/99
