### ISSUE TITLE
# 使用体验反馈

### ISSUE THREAD

**Issue by passerby223** [zq1997/deepin-wine#104]
Kubuntu 20.04.1 LTS完美运行，目前未发现任何bug。非常好用，感谢开发者~已推荐给身边朋友用

**Comment by zq1997** [comment]
谢谢 :laughing:

**Comment by wistarine** [comment]
请问 微信dpi怎么改 阿？？执行 这个不好用阿 WINEPREFIX=~/.deepinwine/容器名称 deepin-wine winecfg

**Comment by yiyayamaya** [comment]
> Kubuntu 20.04.1 LTS完美运行，目前未发现任何bug。非常好用，感谢开发者~已推荐给身边朋友用

楼主能请问下您的deepin wine版本么
