### ISSUE TITLE
Ubuntu20.04LTS微信截屏之后发不出去，收到图片无法放大

### ISSUE THREAD

**Issue by andyleeeeeeeeee** [zq1997/deepin-wine#105]
Ubuntu20.04LTS微信截屏之后发不出去，收到图片无法放大，请问有人遇到同样情况吗？怎么破

**Comment by nonamestreet** [comment]
> 解决方案，在终端执行：
> sudo apt install libjpeg62:i386
这个也解决了我在ubuntu 20.40下面，接收的很多照片完全无法显示的问题。
