### ISSUE TITLE
Ubuntu 20.04.1下企业微信的二维码空白

### ISSUE THREAD

**Issue by PLAmao** [zq1997/deepin-wine#106]
如题，二维码空白，重装好多次，电脑重启也没用

**Comment by zq1997** [comment]
之前有碰到过ipv6情况下QQ加载不出头像的情况，不知道是不是类似问题

**Comment by PLAmao** [comment]
> 之前有碰到过ipv6情况下QQ加载不出头像的情况，不知道是不是类似问题

@zq1997 ，可是我没用ipv6

**Comment by zq1997** [comment]
控制变量试试：硬件、网络……都可能是问题

**Comment by zugle666** [comment]
> 如题，二维码空白，重装好多次，电脑重启也没用

我的也是二维码显示空白
但实际上，企业微信的二维码图片在这个文件夹里，扫这个码就可以登录了：
~/Documents/WXWork/Global/Image

**Comment by zugle666** [comment]
> 如题，二维码空白，重装好多次，电脑重启也没用

我现在的企业微信能出现二维码了
以前空白的原因是：
1. 我以前安装过wszqkzqk/deepin-wine-ubuntu
2. 我没有卸载干净以前的wine

具体卸载方法是
1. 卸载

```
sudo apt-get purge --autoremove com.qq.weixin.deepin
sudo apt-get purge --autoremove com.qq.weixin.work.deepin 
sudo apt-get purge --autoremove deepin-wine-uninstaller
```

2. 删除desktop有关微信和企业微信的全部删掉

```
cd ~/.local/share/applications/
删除有关微信和企业微信的desktop
```

3. 删除这个文件夹：~/.deepinwine

4. 删除配置文件夹：

```
rm -rf ~/Documents/WeChat Files
rm -rf ~/Documents/WXWork
```

5. 最后重新安装zq1997/deepin-wine的企业微信和微信

```
sudo apt install com.qq.weixin.deepin 
sudo apt install deepin.com.weixin.work
```

6. 解决截图发送为空的问题

```
sudo apt install libjpeg62:i386
```

7. 重启电脑

企业微信的二维码就能正常显示了，也可以点击企业微信后，再扫码下面的文件夹里的二维码登录企业微信：
~/Documents/WXWork/Global/Image
