### ISSUE TITLE
阿里旺旺通过点击淘宝链接（聊天图标）无法启动已安装的阿里旺旺软件，即使软件已启动也没反应？

### ISSUE THREAD

**Issue by minlee998** [zq1997/deepin-wine#107]
Linux Mint 20，已经成功安装淘宝的阿里旺旺，运行看起来稳如狗，但是点击淘宝的聊天链接，无法关联启动阿里旺旺软件，请问大家有遇到这个问题吗？

**Comment by zq1997** [comment]
应该不行，从网页启动APP是需要像系统注册软件的安装状态的，这个应该是wine应用做不到的。

**Comment by minlee998** [comment]
> 应该不行，从网页启动APP是需要像系统注册软件的安装状态的，这个应该是wine应用做不到的。

这样的话，要如何才能在电脑上与卖家沟通，难道需要在手机上发起对话，再回到电脑上吗，哈哈

**Comment by zq1997** [comment]
我也不太清除，我没用过阿里旺旺

**Comment by fe7ng654123** [comment]
https://bbs.deepin.org/en/post/34479
这里有一个很久以前的workaroud

> 接着打开终端输入" wine '/home/misaki/.wine/drive_c/Program Files/AliWangWang/8.10.24C/WWCmd.exe' +刚刚你复制到的连接"

不知道现在还有没有类似方法，有人研究一下吗

**Comment by fe7ng654123** [comment]
实测那个JavaScript还是能用的，蛮力运行 wine '/home/osboxes/.deepinwine/Deepin-WangWang/drive_c/Program Files/AliWangWang/9.12.10C/WWCmd.exe/WWCmd.exe' aliim:sendmsg?spm=a1z0d.6639537.1997196601.2.19247484L5Z2X9&touid=cntaobao%E5%8D%A1%E9%BA%A6%E4%BB%91%E6%97%97%E8%88%B0%E5%BA%97&siteid=cntaobao&gid=

可以唤出旺旺程序，输入账号密码登录后聊天窗口无法正常显示，应该是因为我直接跳过了 deepin-wine-helper 来启动程序
到这里就不会弄，等大神帮忙


[replace_wangwang_link.user.js.txt](https://github.com/zq1997/deepin-wine/files/8113683/replace_wangwang_link.user.js.txt)
附上JavaScript, 删掉最后的txt，在chrome或Firefox拓展页直接拖入安装
