### ISSUE TITLE
ubuntu 16.04版本安装微信出现依赖问题，急求方法！！！

### ISSUE THREAD

**Issue by hu674494966** [zq1997/deepin-wine#108]
系统基本情况如下：
~$ echo $XDG_CURRENT_DESKTOP
Unity
~$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.7 LTS
Release:	16.04
Codename:	xenial

具体报错：
sudo apt-get -f install com.qq.weixin.deepin
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 com.qq.weixin.deepin:i386 : Depends: libc6:i386 (>= 2.28) but 2.23-0ubuntu11.2 is to be installed
                             Depends: libgphoto2-6:i386 (>= 2.5.10) but 2.5.9-3 is to be installed
                             Depends: libgphoto2-port12:i386 (>= 2.5.10) but 2.5.9-3 is to be installed
                             Depends: libvkd3d1:i386 (>= 1.0) but it is not going to be installed
                             Recommends: libsdl2-2.0-0:i386 but it is not going to be installed
E: Unable to correct problems, you have held broken packages.

**Comment by zq1997** [comment]
太老了版本

**Comment by Alex-wjq** [comment]
这次更新，基本劝退了16.04或者18.04的用户了

**Comment by hu674494966** [comment]
> 太老了版本

貌似只能升级系统对吧

**Comment by zq1997** [comment]
是的



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "hu674494966"<notifications@github.com&gt;; 
发送时间: 2020年11月26日(星期四) 中午1:45
收件人: "zq1997/deepin-wine"<deepin-wine@noreply.github.com&gt;; 
抄送: "1943825697"<email2zq@qq.com&gt;; "Comment"<comment@noreply.github.com&gt;; 
主题: Re: [zq1997/deepin-wine] ubuntu 16.04版本安装微信出现依赖问题，急求方法！！！ (#108)





  
太老了版本
  
貌似只能升级系统对吧
 
&mdash;

**Comment by hu674494966** [comment]
> 这次更新，基本劝退了16.04或者18.04的用户了
嗯，确实比较尴尬，如果是这样，那暂时只能放弃了

**Comment by hu674494966** [comment]
> 是的
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "hu674494966"<notifications@github.com&gt;; 发送时间: 2020年11月26日(星期四) 中午1:45 收件人: "zq1997/deepin-wine"<deepin-wine@noreply.github.com&gt;; 抄送: "1943825697"<email2zq@qq.com&gt;; "Comment"<comment@noreply.github.com&gt;; 主题: Re: [zq1997/deepin-wine] ubuntu 16.04版本安装微信出现依赖问题，急求方法！！！ (#108) 太老了版本 貌似只能升级系统对吧 &mdash; You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by zq1997** [comment]
deepin官方已经把旧版的包撤了现在

**Comment by hu674494966** [comment]
> 是的
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "hu674494966"<notifications@github.com&gt;; 发送时间: 2020年11月26日(星期四) 中午1:45 收件人: "zq1997/deepin-wine"<deepin-wine@noreply.github.com&gt;; 抄送: "1943825697"<email2zq@qq.com&gt;; "Comment"<comment@noreply.github.com&gt;; 主题: Re: [zq1997/deepin-wine] ubuntu 16.04版本安装微信出现依赖问题，急求方法！！！ (#108) 太老了版本 貌似只能升级系统对吧 &mdash; You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.



> 这次更新，基本劝退了16.04或者18.04的用户了



> deepin官方已经把旧版的包撤了现在

好的，了解，多谢

**Comment by hu674494966** [comment]
> deepin官方已经把旧版的包撤了现在

好的，了解，多谢
