### ISSUE TITLE
运行命令错误是什么原因？

### ISSUE THREAD

**Issue by yhc1994** [zq1997/deepin-wine#11]
E: 仓库 “http://package.elementaryos.cn/apt xenial Release” 没有 Release 文件。
W: GPG 错误：http://package.elementaryos.cn/bionic bionic InRelease: 由于没有公钥，无法验证下列签名： NO_PUBKEY D4B649FF24A060B1
E: 仓库 “http://package.elementaryos.cn/bionic bionic InRelease” 没有数字签名。

**Comment by yhc1994** [comment]
:~$ wget -qO- https://deepin-wine.i-m.dev/setup.sh | sudo sh
W: 无法下载 http://package.elementaryos.cn/apt/dists/xenial/InRelease  无法连接上 package.elementaryos.cn:80 (118.24.104.111)，连接超时
W: 无法下载 http://package.elementaryos.cn/bionic/dists/bionic/InRelease  不能连接到 package.elementaryos.cn：http：
W: 部分索引文件下载失败。如果忽略它们，那将转而使用旧的索引文件。
一切顺利，你可以用apt系列命令来安装直接安装QQ、微信了。
如果觉得有用的话，去 https://github.com/zq1997/deepin-wine 点个star吧😛

还有这样的

**Comment by zq1997** [comment]
注意看链接，应该是你的elementoryos系统仓库的问题，和本仓库无关。

**Comment by wang-xiaowu** [comment]
记录一下：
```
你遇到的错误信息是关于 Microsoft 的软件仓库签名验证失败。具体错误是：
错误:4 https://packages.microsoft.com/repos/code stable InRelease
  由于没有公钥，无法验证下列签名： NO_PUBKEY EB3E94ADBE1229CF
这表明你的系统无法验证 https://packages.microsoft.com/repos/code 仓库中的软件包，因为缺少对应的公钥。
解决方法：
要解决这个问题，你需要手动导入缺失的公钥。以下是步骤：
步骤 1: 导入 Microsoft 的 GPG 公钥
下载并添加 Microsoft 的公钥：
使用以下命令导入公钥：
curl https://packages.microsoft.com/keys/microsoft.asc | sudo gpg --dearmor -o /usr/share/keyrings/microsoft-archive-keyring.gpg
这将从 https://packages.microsoft.com/keys/microsoft.asc 下载 GPG 公钥，并将其保存到 /usr/share/keyrings/microsoft-archive-keyring.gpg。
步骤 2: 更新 apt 源配置
更新你的 APT 源配置文件，确保 apt 使用正确的密钥文件。编辑 Microsoft 的仓库源配置文件：
sudo vim /etc/apt/sources.list.d/vscode.list
如果你看到类似这样的行：
deb [arch=amd64] https://packages.microsoft.com/repos/code stable main
你需要将其修改为：
deb [arch=amd64 signed-by=/usr/share/keyrings/microsoft-archive-keyring.gpg] https://packages.microsoft.com/repos/code stable main
这将告诉 apt 使用你刚才导入的 GPG 密钥进行签名验证。
步骤 3: 更新软件源
更新 APT 索引：
sudo apt update
```
