### ISSUE TITLE
XDG_DATA_DIRS的bug，重启多次依然没有图标

### ISSUE THREAD

**Issue by Hoking007** [zq1997/deepin-wine#110]
首先，非常感谢作者的贡献，让我们能够在Linux这个方便的使用微信和QQ！

系统：
kubuntu 20.04 KDE

现象：
之前一直使用本仓库来运行微信和TIM，然后11月28日最新拉取本仓库，安装最新的微信和QQ，并且按照说明重启（多次），并未出现微信和QQ图标。

分析：
$ ls -l /etc/profile.d
total 40
-rw-r--r-- 1 root root   96 12月  5  2019 01-locale-fix.sh
-rw-r--r-- 1 root root  833 9月   4 23:42 apps-bin-path.sh
-rw-r--r-- 1 root root  729 2月   2  2020 bash_completion.sh
-rw-r--r-- 1 root root 1003 8月  13  2019 cedilla-portuguese.sh
-rw-r--r-- 1 root root  233 11月 28 17:20 deepin-wine.i-m.dev.sh
-rw-r--r-- 1 root root 1107 11月  4  2019 gawk.csh
-rw-r--r-- 1 root root  757 11月  4  2019 gawk.sh
-rw-r--r-- 1 root root  349 9月   4 01:55 im-config_wayland.sh
-rw-r--r-- 1 root root 1368 6月  12 01:44 vte-2.91.sh
-rw-r--r-- 1 root root  966 6月  12 01:44 vte.csh

$ cat /etc/profile.d/deepin-wine.i-m.dev.sh 
XDG_DATA_DIRS=${XDG_DATA_DIRS:-/usr/local/share:/usr/share}
for deepin_dir in /opt/apps/*/entries; do
    if [ -d "$deepin_dir/applications" ]; then
        XDG_DATA_DIRS="$XDG_DATA_DIRS:$deepin_dir"
    fi
done
export XDG_DATA_DIRS

$ ls -l /opt/apps 
total 12
drwxr-xr-x 4 root root 4096 11月 27 22:38 com.dingtalk.deepin
drwxr-xr-x 4 root root 4096 11月 27 22:38 com.qq.im.deepin
drwxr-xr-x 4 root root 4096 11月 27 22:38 com.qq.weixin.deepin

多次重启后查看XDG_DATA_DIRS
$ echo $XDG_DATA_DIRS
/usr/share/plasma:/usr/local/share/:/usr/share/

以上，是我目前的状态信息，经过重启，也没有出现图标。
虽然，我手动将/opt/apps 下面的desktop和icon拷贝到~/.local/share下面对应位置能够正常显示图标，但是总觉得不够优雅，因此将此问题反馈出来，希望作者看看是我单个电脑问题，还是大家都有这个问题？
谢谢！

**Comment by zq1997** [comment]
看起来是设置的值被`/usr/share/plasma`覆盖取消了

**Comment by Hoking007** [comment]
> 看起来是设置的值被`/usr/share/plasma`覆盖取消了

设置环境变量的脚本，是否可以更靠后一点，比如用户登录时运行脚本，这样被系统覆盖的机会小一些

**Comment by zq1997** [comment]
可以手动移入用户profile，主要是考虑多用户，以及防止删除，才放在系统目录
