### ISSUE TITLE
ubuntu20.04 安装微信后双击图标无法启动，也没有什么报错的，也重启了还是没有解决有大神能帮助解决下吗，重装后一样

### ISSUE THREAD

**Issue by Liu-Hangyu** [zq1997/deepin-wine#112]
ubuntu20.04 安装微信后双击图标无法启动，求助大神

**Comment by huihui571** [comment]
ubuntu20.04原本可以正常使用，今天在系统软件更新中安装了更新之后，也是点击图标无法启动，没有任何报错。

**Comment by Liu-Hangyu** [comment]
谢谢，明白了，现在我先装了一个老版的，先用着

**Comment by huihui571** [comment]
> 谢谢，明白了，现在我先装了一个老版的，先用着

能问下你装了老版是老版的微信吗，怎么装的啊。我系统安装了更新之后，现在微信一直用不了了。

**Comment by lbf4616** [comment]
同样问题，点了没反应

**Comment by Sciroccogti** [comment]
QQ 也是，有一次似乎在顶栏提示运行 apt 的时候没有权限。

**Comment by simonchen007** [comment]
老版的微信吗，怎么装 ?

**Comment by Esther-99** [comment]
同样问题，ubuntu20.04安装后点击没反应，不报错

**Comment by NingAnMe** [comment]
解决了这个问题：
可以进入`/opt/apps/com.qq.weixin.deepin/files`目录，执行`bash ./run.sh`
然后根据报错，解决对应的问题就可以了。
我遇到了两个问题。
第一个问题
```
libGL error: No matching fbConfigs or visuals found
libGL error: failed to load driver: swrast
```
安装对应NVIDIA驱动版本的32位驱动就可以
`sudo apt-get install libnvidia-gl-470:i386`，可以`nvidia-smi`查看自己的驱动版本，把`470`替换掉

第二个问题
```
X Error of failed request:  BadValue (integer parameter out of range for operation)
  Major opcode of failed request:  154 (GLX)
  Minor opcode of failed request:  24 (X_GLXCreateNewContext)
  Value in failed request:  0x0
  Serial number of failed request:  29
  Current serial number in output stream:  30
```
重启一下X服务`sudo systemctl restart display-manager`

**Comment by simonchen007** [comment]
我后来也解决了，我的现象更加奇葩。把系统从 简体中文 换成 英文 或者 繁体中文，就解决了。
