### ISSUE TITLE
top icon plus 里 微信图标在接收到新消息后会消失

### ISSUE THREAD

**Issue by qingshanyuluo** [zq1997/deepin-wine#113]
是ubuntu20.04 默认桌面 开启topicon-plus 后
如题，微信接收到新消息后后台图标会闪烁，估计插件不知道怎么处理，就直接消失了

**Comment by 2793145003** [comment]
QQ也是。
插件里关掉topicon-plus，在wine里点掉那些消息提示再打开就好了。
然后收到消息后图标又会消失。

**Comment by 1992black** [comment]
> QQ也是。
> 插件里关掉topicon-plus，在wine里点掉那些消息提示再打开就好了。
> 然后收到消息后图标又会消失。

单屏幕不会出现这个问题， 如果是多屏幕把最左面的屏幕设置为主屏幕就可以了。
原始帖见 https://bbs.deepin.org/forum.php?mod=viewthread&tid=155949 第9楼

**Comment by qingshanyuluo** [comment]
没错是多显示器的问题

**Comment by Suliang1027** [comment]
topicon-plus在我这儿一直不能用，tray icons到是可以
