### ISSUE TITLE
你好，请问怎样设置缩放呢

### ISSUE THREAD

**Issue by wwwljxw** [zq1997/deepin-wine#114]
### 我尝试使用过以下命令
~/.deepinwine/Deepin-QQ deepin-wine winecfg

**Comment by bigonestep** [comment]
遇到了同样的问题，求解答

**Comment by zq1997** [comment]
`WINEPREFIX=~/.deepinwine/Deepin-QQ deepin-wine winecfg`

**Comment by zq1997** [comment]
新版本deepin-wine不在全局路径，还需要手动输入全路径。
2020年10月前的教程都不能直接适用。

**Comment by bigonestep** [comment]
> 新版本deepin-wine不在全局路径，还需要手动输入全路径。
> 2020年10月前的教程都不能直接适用。

查找了一下，没有找到deepin-wine的路径，麻烦您可以告知一下么？

**Comment by zq1997** [comment]
可能是`/home/?????/.deepinwine/deepin-wine5/bin`里

**Comment by chenjianyuan** [comment]
root@xxxx:/home/xxxx/.deepinwine/deepin-wine5/bin# ls
function_grep.pl  msiexec  regedit   widl  wineboot   winecfg      winecpp  winedump  wineg++  winemaker  winepath        wineserver  wrc
msidb             notepad  regsvr32  wine  winebuild  wineconsole  winedbg  winefile  winegcc  winemine   wine-preloader  wmc

全局搜索不到 deep-wine 命令

**Comment by zq1997** [comment]
不要deepin-前缀

**Comment by chenjianyuan** [comment]
万分感谢，大佬牛逼！

**Comment by dickzhenhua** [comment]
> 不要deepin-预设

那究竟完整的指令是什么？请给出，谢谢

**Comment by phyzhenli** [comment]
ubuntu 20.04.1
完整的指令：env WINEPREFIX=~/.deepinwine/Deepin-WeChat ~/.deepinwine/deepin-wine5-stable/bin/wine winecfg

**Comment by wistarine** [comment]
收到 感谢，另外i如何用ctrl +alt +w 实现 调出微信？

**Comment by Frank1126lin** [comment]
> env WINEPREFIX=~/.deepinwine/Deepin-WeChat ~/.deepinwine/deepin-wine5-stable/bin/wine winecfg
增加调整方式
https://blog.csdn.net/weixin_36349646/article/details/102670624?utm_medium=distribute.pc_relevant.none-task-blog-baidujs_title-2&spm=1001.2101.3001.4242

**Comment by zhang8473** [comment]
env DEEPIN_WINE_SCALE=2 也可以

**Comment by phyzhenli** [comment]
> env DEEPIN_WINE_SCALE=2 也可以

试了，不行。另外我update了，deepin-wine5-stable升级到了deepin-wine6-stable，命令改成对应版本即可。
