### ISSUE TITLE
无法发送截图

### ISSUE THREAD

**Issue by grassvalley** [zq1997/deepin-wine#115]
系统环境： Mint 20 Xfce 桌面环境

截图软件：Xfce自带截图，flameshot

问题描述：
使用截图软件进行截图，保存至粘贴板。在微信输入窗口，按下ctrl-v可以把图片粘贴到输入窗口。但是按下回车或者点击发送按钮后，输入区清空，消息区没有内容。
另外，对方发送过来的图片，点击后是一片空白，不显示图片内容。

**Comment by grassvalley** [comment]
在网上搜了一下。安装 libjpeg62:i386包可以解决这个问题。
sudo apt install libjpeg62:i386

**Comment by Catiks** [comment]
谢谢老哥

**Comment by HarsonLau** [comment]
谢谢老哥

**Comment by rangerzhou** [comment]
感谢大兄弟！

**Comment by aiwoqu** [comment]
谢谢老哥
