### ISSUE TITLE
更新的时候报仓库没有数字签名

### ISSUE THREAD

**Issue by Loyolichoo** [zq1997/deepin-wine#116]
如下是报错内容，略过其他源更新
$ sudo apt update
忽略:10 https://deepin-wine.i-m.dev  InRelease                                 
获取:11 https://deepin-wine.i-m.dev  Release [1,221 B]                         
忽略:12 https://deepin-wine.i-m.dev  Release.gpg                               
正在读取软件包列表... 完成                                                     
E: 仓库 “https://deepin-wine.i-m.dev  Release” 没有数字签名。
N: 无法安全地用该源进行更新，所以默认禁用该源。
N: 参见 apt-secure(8) 手册以了解仓库创建和用户配置方面的细节。

环境相关：
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.1 LTS
Release:	20.04
Codename:	focal

$ uname -a
Linux ubuntu-YangTianM4601c-00 5.4.0-58-generic #64-Ubuntu SMP Wed Dec 9 08:16:25 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

$ apt -v
apt 2.0.2ubuntu0.2 (amd64)

**Comment by zq1997** [comment]
适用setup.sh，不熟悉的情况下不要自行配置
