### ISSUE TITLE
在ubuntu20.10中安装，出现依赖错误

### ISSUE THREAD

**Issue by grassvalley** [zq1997/deepin-wine#120]
在ubuntu 20.10 上运行安装，出现如下错误：

`下列软件包有未满足的依赖关系：
 libgirepository-1.0-1 : 破坏: python-gi (< 3.34.0-4~) 但是 3.30.4-1 正要被安装
 python-gobject-2 : 依赖: libffi7 (>= 3.3~20180313) 但无法安装它
E: 无法修正错误，因为您要求某些软件包保持现状，就是它们破坏了软件包间的依赖关系。
`

**Comment by Loyolichoo** [comment]
libgirepository-1.0-1/focal-updates,now 1.64.1-1~ubuntu20.04.1 amd64 [已安装，自动]
python-gi/focal,now 3.36.0-1 amd64 [已安装，自动]
python-gobject-2/focal,now 2.28.6-14ubuntu1 amd64 [已安装，自动]
libffi7/focal,now 3.3-4 amd64 [已安装，自动]
20.04环境下这个几个包的版本搭配是正常的，你看看你是哪个包安不了，哪个包版本号不对。理论上一般包只限制最低版本号，往高版本升不会有依赖问题

**Comment by Loyolichoo** [comment]
libffi7在20.10已经替换为了libffi8ubuntu1，你可以选择改依赖关系然后重打包，也可以选择去下一个20.04的libffi7
https://packages.ubuntu.com/focal/libffi7

**Comment by Loyolichoo** [comment]
再附赠一个向日葵的重打包教程，依葫芦画瓢即可
https://www.jianshu.com/p/289001a00cb1

**Comment by szwhy** [comment]
貌似需要>3.34.0-4版本的python-gi，但只有Focal (20.04)才能装上3.36.0-1版本，Groovy (20.10)这个包已经Status:Superseded了
这个源带的又是装不了的3.30.4-1版本
参考：
https://answers.launchpad.net/ubuntu/focal/amd64/python-gi/3.36.0-1
https://answers.launchpad.net/ubuntu/groovy/amd64/python-gi/3.36.0-1

**Comment by duzhaokun123** [comment]
@szwhy  那就手动下载安装
https://mirrors.tuna.tsinghua.edu.cn/ubuntu/pool/universe/p/pygobject/python-gi_3.36.0-1_amd64.deb
反正是`universe`里的
