### ISSUE TITLE
ubuntu 20.04 LTS wine只下载了微信，每过一段时间wine会无响应，此时键盘无法输入

### ISSUE THREAD

**Issue by dongdongqiang2018** [zq1997/deepin-wine#121]
如题
之前ubuntu在18.04 后来wine的微信无法在此版本下安装，便升级了20.04，但是最近发现一个问题，在ubuntu 20.04 LTS 的wine下面只下载了微信，每过一段时间wine会无响应，此时键盘无法输入。
开始以为是与机械键盘驱动有冲突， 后来排除此问题， 微信重装过了也没有解决， 是不是要重装以下wine
这个问题是个例还是普遍存在的

**Comment by zq1997** [comment]
搜狗输入法？

**Comment by Loyolichoo** [comment]
试试重启输入法，搜狗输入法更新到最新版

**Comment by dongdongqiang2018** [comment]
> 搜狗输入法？

谢谢大佬回复，查明原因了， 是cherry键盘和系统有冲突，厂家已经给出了解决方案

**Comment by dongdongqiang2018** [comment]
> 试试重启输入法，搜狗输入法更新到最新版

谢谢回复， 没有安装搜狗输入法， 是键盘的原因
