### ISSUE TITLE
请问大神，微信如何升级？

### ISSUE THREAD

**Issue by wistarine** [zq1997/deepin-wine#127]
相互尊重！

相互尊重！

相互尊重！

大家的时间都很宝贵，不要再提出一些不知所谓的问题了，务必注意下面的事项！

# 阅读主页文档！

**主页的文档里面，尤其是其中【更多问题】一节，已经介绍了很多常见问题的解决方案了。**

# 描述清楚问题信息

去公安局报案，不说时间地点，不说来龙去脉，上来就一句“我钱丢了”，警察会理你吗？

什么系统，什么桌面，什么版本，什么条件下会发生什么问题？说清楚！

如果你有第二台电脑，最好两台电脑都试试，排除问题干扰，这是最好不过了。

# 啥都不会，又啥都不说清楚，但还是希望问题能够解决

建议买火车票去河南，到少林寺烧香拜佛，说不定就灵了呢。

**Comment by wistarine** [comment]
搞定了 谢谢....直接在win下 下载一个安装后的然后把\program files\tencent\wechat文件夹 压缩后 解压替换即可

**Comment by VixeruntR** [comment]
> 搞定了 谢谢....直接在win下 下载一个安装后的然后把\program files\tencent\wechat文件夹 压缩后 解压替换即可

请问替换哪个文件夹呀？
