### ISSUE TITLE
建议将有道云笔记加入本源？

### ISSUE THREAD

**Issue by hck8288** [zq1997/deepin-wine#128]

**Comment by Okeyja** [comment]
复议。建议大大产粮。

**Comment by kgbook** [comment]
+1, 一直使用有道云笔记。

也可以下载 deb 包，先用着。
百度云下载：https://pan.baidu.com/s/1v0y0OEak4Cj814ao15BNbA    提取码: pskt

**Comment by zq1997** [comment]
添加了`com.youdao.note.deepin`到仓库

**Comment by hck8288** [comment]
感谢
