### ISSUE TITLE
ubuntu16.04无法使用了？

### ISSUE THREAD

**Issue by luckychay** [zq1997/deepin-wine#129]
更新到V2之前在一台装有ubuntu 16.04的机器上装过，现在仍然可用。然而更新后，我在另外一台机器上安装时出现依赖错误，所需的包版本都很新，基本都是ubuntu18.04以上使用的，这个是不是意味着没有兼容好？以前的版本还可以用吗？

错误如下：
The following packages have unmet dependencies:
 com.qq.weixin.deepin:i386 : Depends: libc6:i386 (>= 2.28) but 2.23-0ubuntu11.2 is to be installed

**Comment by zq1997** [comment]
#108

**Comment by luckychay** [comment]
OK 明白了
