### ISSUE TITLE
移植飞书

### ISSUE THREAD

**Issue by BlueSky-07** [zq1997/deepin-wine#133]
经过测试，飞书可以正常使用，能否帮忙添加到白名单呢？

OS: Mint 20.1

[cn.feishu.deepin_3.32.3deepin2_i386.deb](https://community-store-packages.deepin.com/appstore/pool/appstore/c/cn.feishu.deepin/cn.feishu.deepin_3.32.3deepin2_i386.deb)

**Comment by zq1997** [comment]
添加了`cn.feishu.deepin`
