### ISSUE TITLE
QQ安装失败，提示无法下载deb包

### ISSUE THREAD

**Issue by cqulpj** [zq1997/deepin-wine#137]
微信安装成功，安装qq的时候提示无法下载deb包，
系统版本及相关配置如下：

lpj@lpj-E520:/etc/apt$ echo $XDG_CURRENT_DESKTOP
KDE
lpj@lpj-E520:/etc/apt$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 20.04.2 LTS
Release:        20.04
Codename:       focal
lpj@lpj-E520:/etc/apt$ grep -rn '^\s*deb ' --include '*.list' /etc/apt/
/etc/apt/sources.list:5:deb http://mirrors.aliyun.com/ubuntu/ focal main restricted
/etc/apt/sources.list:10:deb http://mirrors.aliyun.com/ubuntu/ focal-updates main restricted
/etc/apt/sources.list:16:deb http://mirrors.aliyun.com/ubuntu/ focal universe
/etc/apt/sources.list:18:deb http://mirrors.aliyun.com/ubuntu/ focal-updates universe
/etc/apt/sources.list:26:deb http://mirrors.aliyun.com/ubuntu/ focal multiverse
/etc/apt/sources.list:28:deb http://mirrors.aliyun.com/ubuntu/ focal-updates multiverse
/etc/apt/sources.list:36:deb http://mirrors.aliyun.com/ubuntu/ focal-backports main restricted universe multiverse
/etc/apt/sources.list:46:deb http://mirrors.aliyun.com/ubuntu/ focal-security main restricted
/etc/apt/sources.list:48:deb http://mirrors.aliyun.com/ubuntu/ focal-security universe
/etc/apt/sources.list:50:deb http://mirrors.aliyun.com/ubuntu/ focal-security multiverse
/etc/apt/sources.list.d/google-chrome.list:3:deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main
/etc/apt/sources.list.d/deepin-wine.i-m.dev.list:1:deb [trusted=yes] https://deepin-wine.i-m.dev /

安装qq时终端输出详细信息如下

lpj@lpj-E520:/etc/apt$ sudo apt install com.qq.im.deepin
正在读取软件包列表... 完成
正在分析软件包的依赖关系树       
正在读取状态信息... 完成       
下列【新】软件包将被安装：
  com.qq.im.deepin:i386
升级了 0 个软件包，新安装了 1 个软件包，要卸载 0 个软件包，有 2 个软件包未被升级。
需要下载 138 MB 的归档。
解压缩后会消耗 156 MB 的额外空间。
错误:1 https://deepin-wine.i-m.dev  com.qq.im.deepin 9.3.2deepin14
  404  Not Found [IP: 58.51.151.5 443]
E: 无法下载 https://community-store-packages.deepin.com/appstore/pool/appstore/c/com.qq.im.deepin/com.qq.im.deepin_9.3.2deepin14_i386.deb  404  Not Found [IP: 58.51.151.5 443]
E: 有几个软件包无法下载，要不运行 apt-get update 或者加上 --fix-missing 的选项再试试？

这个是deepin官方库的原因么？

**Comment by Sciroccogti** [comment]
我也是这样。前两天还能下的呢

**Comment by YangFanJack** [comment]
我也是这样的

**Comment by cqulpj** [comment]
我添加了deepin v20的官方源，然后从官方源安装成功了，估计是官方deb包地址有变更，这里还没同步

**Comment by Sciroccogti** [comment]
> deepin v20的官方源

求教，如何添加？

**Comment by cqulpj** [comment]
deb https://community-store-packages.deepin.com/appstore eagle appstore
添加这个到/etc/apt/sources.list中，然后
sudo apt update
这样就添加好了，安装前先用
sudo apt search com.qq
这样查看一下都有哪些软件包，应该就是com.qq.im.deepin，然后安装就行了
sudo apt install com.qq.im.deepin

我用的是kubuntu，安装好后启动器里找不到，重启一下就可以了

**Comment by Sciroccogti** [comment]
> deb [community-store-packages.deepin.com/appstore](https://community-store-packages.deepin.com/appstore) eagle appstore
> 添加这个到/etc/apt/sources.list中，然后
> sudo apt update
> 这样就添加好了

我这边提示需要公钥。。

添加的 deb 行是：
```
deb [trusted=yes] https://community-store-packages.deepin.com/appstore eagle appstore
```

**Comment by cqulpj** [comment]
哦哦，对的，需要公钥，我今天把这一步搞忘了，添加公钥的命令是：
sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 1C30362C0A53D5BB
最后的公钥参考终端提示替换，然后就可以安装了

**Comment by faawdd** [comment]
版本号错误，应该是 com.qq.im.deepin9.3.2deepin20

**Comment by FindHao** [comment]
> 1、打开/etc/apt/sources.list文件，添加下面的deepin v20的源
> deb https://community-store-packages.deepin.com/appstore eagle appstore
> 2、用下面的命令添加公钥
> sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 1C30362C0A53D5BB
> 末尾的公钥参考终端提示替换，
> 3、sudo apt update
> 4、sudo apt search com.qq
> 这样查看一下都有哪些软件包，应该就是com.qq.im.deepin，然后安装就行了
> sudo apt install com.qq.im.deepin
> 
> 我用的是kubuntu，安装好后启动器里找不到，重启一下就可以了

那岂不是直接用deepin官方源就行了。这个repo还需要吗？
