### ISSUE TITLE
无法在qq里使用fcitx输入法

### ISSUE THREAD

**Issue by freeze-dolphin** [zq1997/deepin-wine#139]
### 指令输出
```
freeze-dolphin@vortex:~$ echo $XDG_CURRENT_DESKTOP
XFCE
freeze-dolphin@vortex:~$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.2 LTS
Release:	20.04
Codename:	focal
freeze-dolphin@vortex:~$ grep -rn '^\s*deb ' --include '*.list' /etc/apt/
/etc/apt/sources.list:5:deb http://mirrors.aliyun.com/ubuntu/ focal restricted main universe multiverse
/etc/apt/sources.list:10:deb http://mirrors.aliyun.com/ubuntu/ focal-updates restricted main universe multiverse
/etc/apt/sources.list:32:deb http://mirrors.aliyun.com/ubuntu/ focal-backports restricted multiverse main universe
/etc/apt/sources.list:39:deb http://archive.canonical.com/ubuntu focal partner
/etc/apt/sources.list:42:deb http://mirrors.aliyun.com/ubuntu/ focal-security restricted main universe multiverse
/etc/apt/sources.list:52:deb https://typora.io/linux ./
/etc/apt/sources.list.d/deepin-wine.i-m.dev.list:1:deb [trusted=yes] https://deepin-wine.i-m.dev /
freeze-dolphin@vortex:~$ 
```
### 问题内容
无法在qq里使用fcitx输入法  
输入法版本:  
```
freeze-dolphin@vortex:~$ fcitx --version
fcitx version: 4.2.9.7
freeze-dolphin@vortex:~$ 
```

其实勉强可以克服，只需要开个mousepad里面打字然后 <kbd>Ctrl</kbd> + <kbd>X</kbd> 剪切到QQ里  
但是这样真的很麻烦啊，如果有解决思路请麻烦分享一下叭！

**Comment by AnalogKnight** [comment]
同20.04，QQ使用正常，但输入法有所区别
是否可以考虑更换输入法暂时解决问题？

**Comment by NichtsVonChaos** [comment]
1、有没有设置环境变量？也就是

```
export GTK_IM_MODULE=fcitx
export QT_IM_MODULE=fcitx
export XMODIFIERS=@im=fcitx
```

这一陀，到处都写一写试试，什么.bashrc（其他sh就写对应地方），.xprofile，/etc/environment啥的都试试。

2、系统是不是中文系统？如果不是，打开你的/etc/locale.gen，取消注释

```
zh_CN.UTF-8 UTF-8
```
这一行再运行

```
sudo locale-gen
```

重启再试试。

**Comment by CyrusYip** [comment]
能用 Ibus 输入法吗？如果可以的话，用这个方法可以用 Fcitx5：

```bash
# 安装 Ibus 输入法，将它设置为默认的输入法
sudo apt install ibus
im-config -n ibus

# 安装 Fctix5

sudo apt install \
fcitx5 \
fcitx5-pinyin \
fcitx5-chinese-addons \
fcitx5-frontend-gtk2 \
fcitx5-frontend-gtk3 \
fcitx5-frontend-qt5 \
kde-config-fcitx5 \
fcitx5-module-ibus

# 开机启动 Fcitx5
cp /usr/share/applications/fcitx5.desktop ~/.config/autostart/

# 设置 Fcitx5（如果已经设置过了就跳过这一步）
fcitx5-configtool

如果有缺失的包就先添加下面的 PPA：
# sudo add-apt-repository ppa:hosxy/fcitx5
```

参考文章：[在 RStudio 中使用 Fcitx5（Kubuntu 20.10） - 叶寻 | Cyrus Yip](https://cyrusyip.org/post/2020/11/01/use-fcitx5-in-rstudio-on-kubuntu20.10)

**Comment by shenchunhang** [comment]
和题主一致都是 ubuntu server 20.04,只是输入法不一样, 我用的是 ibus, 
但是在wineqq里面还是没法输出中文来, 
ibus应该没有问题, 做修改应该是 改 deepinwine 或者wineqq

**Comment by hxlhxl** [comment]
> 1、有没有设置环境变量？也就是
> 
> ```
> export GTK_IM_MODULE=fcitx
> export QT_IM_MODULE=fcitx
> export XMODIFIERS=@im=fcitx
> ```
> 
> 这一陀，到处都写一写试试，什么.bashrc（其他sh就写对应地方），.xprofile，/etc/environment啥的都试试。
> 
> 2、系统是不是中文系统？如果不是，打开你的/etc/locale.gen，取消注释
> 
> ```
> zh_CN.UTF-8 UTF-8
> ```
> 
> 这一行再运行
> 
> ```
> sudo locale-gen
> ```
> 
> 重启再试试。

亲测有用
本人环境
 
```bash
$ Debian 11

$ fcitx5 --version
5.0.5

$ /bin/deepin-wine8-stable --version
wine-8.16

$ 企业微信
4.1.32.6005
```

不需要在 `/opt/deepinwine/tools/run_v4.sh` 或者 `/opt/apps/com.qq.weixin.work.deepin/files/run.sh` 中添加关于 fcitx 的环境变量
只需要在 `/etc/locale.gen` 中添加上 `zh_CN.UTF-8 UTF-8` 重启企业微信就可以输入中文了。
