### ISSUE TITLE
Ubuntu20.04安装微信后，没有看到有微信图标

### ISSUE THREAD

**Issue by Lobinson1** [zq1997/deepin-wine#142]
如题，各位大佬有遇到过执行命令sudo apt-get install com.qq.weixin.deepin 安装完成后，没有出现微信图标，但实际是安装完成了。
重新执行命令也提示已经安装到最新版本

**Comment by wang5561207** [comment]
常见问题
没有应用图标
注销！注销！注销！

注销不懂？重启会吗！

**Comment by Leslie-Hung** [comment]
kali-xfce4重启后也没有
