### ISSUE TITLE
钉钉闪退问题

### ISSUE THREAD

**Issue by timchine** [zq1997/deepin-wine#144]
大佬们辛苦了！下面我就说说我遇到的问题。
这是我的环境配置
/etc/apt/sources.list.d/google-chrome.list:3:deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main
/etc/apt/sources.list.d/deepin-wine.i-m.dev.list:1:deb [trusted=yes] https://deepin-wine.i-m.dev /
/etc/apt/sources.list:5:deb http://cn.archive.ubuntu.com/ubuntu/ focal main restricted
/etc/apt/sources.list:9:deb http://cn.archive.ubuntu.com/ubuntu/ focal-updates main restricted
/etc/apt/sources.list:14:deb http://cn.archive.ubuntu.com/ubuntu/ focal universe
/etc/apt/sources.list:16:deb http://cn.archive.ubuntu.com/ubuntu/ focal-updates universe
/etc/apt/sources.list:24:deb http://cn.archive.ubuntu.com/ubuntu/ focal multiverse
/etc/apt/sources.list:26:deb http://cn.archive.ubuntu.com/ubuntu/ focal-updates multiverse
/etc/apt/sources.list:34:deb http://cn.archive.ubuntu.com/ubuntu/ focal-backports main restricted universe multiverse
/etc/apt/sources.list:43:deb http://security.ubuntu.com/ubuntu focal-security main restricted
/etc/apt/sources.list:44:deb http://security.ubuntu.com/ubuntu focal-security universe
/etc/apt/sources.list:46:deb http://security.ubuntu.com/ubuntu focal-security multiverse
首先在安装你们钉钉的之前有安装过各种版本的钉钉，要么消息看不到文字，要么加密消息看不了，不过综合来讲你们的钉钉还是不错的，不过，我装了过后重启电脑，然后在用钉钉，就会闪退。直接闪退，然后我试着查询系统下所有有关钉钉的文件，我以为是各种版本钉钉相互影响造成的，结果重新安装好了，然后重启电脑有闪退。然后我进行删除Deepin-Dding文件夹重启钉钉，结果又好了。然后重启电脑，我曹心态炸裂，又闪退，不过综合来讲还是挺好用。（我不太清楚钉钉登录页是一个还是两个，当登录页变了就会退出）有一个不是问题的问题，什么qq音乐啊，微信啊，在使用一段时间后会莫名奇妙的退出。

**Comment by leemengxing** [comment]
我也有这个问题，每次退出钉钉，在登录就进不去，要删除容器重启才行。

**Comment by chenls** [comment]
我也发现这个问题，钉钉安装后会自动升级版本，第一次打卡正常，重新打开后就闪退，删掉~/.deepinwine/Deepin-Dding版本就还原了，可以恢复，但是下一次又自动会更新版本，所以现在就每次重新打开钉钉都需要先删除~/.deepinwine/Deepin-Dding，有没有什么好的解决方法

**Comment by chenls** [comment]
> 我也发现这个问题，钉钉安装后会自动升级版本，第一次打卡正常，重新打开后就闪退，删掉~/.deepinwine/Deepin-Dding版本就还原了，可以恢复，但是下一次又自动会更新版本，所以现在就每次重新打开钉钉都需要先删除~/.deepinwine/Deepin-Dding，有没有什么好的解决方法

貌似删除~/.deepinwine/Deepin-Dding/drive_c/Program Files/DingDing/DingTalkUpdater.exe这个文件后就不会崩溃了
