### ISSUE TITLE
Ubuntu 18.04升级到20.04安装出现依赖问题

### ISSUE THREAD

**Issue by benxiaohai1212** [zq1997/deepin-wine#145]
下列软件包有未满足的依赖关系：
 com.qq.weixin.deepin:i386 : 依赖: libglib2.0-0:i386 (>= 2.12.0) 但是它将不会被安装
                             依赖: libgphoto2-6:i386 (>= 2.5.10) 但是它将不会被安装
                             依赖: libgstreamer-plugins-base1.0-0:i386 (>= 1.0.0) 但是它将不会被安装
                             依赖: libgstreamer1.0-0:i386 (>= 1.4.0) 但是它将不会被安装
                             依赖: libldap-2.4-2:i386 (>= 2.4.7) 但是它将不会被安装
                             依赖: libxml2:i386 (>= 2.9.0) 但是它将不会被安装
                             推荐: libcups2:i386 但是它将不会被安装
                             推荐: libgnutls30:i386 但是它将不会被安装 或
                                     libgnutls28:i386 但无法安装它 或
                                     libgnutls26:i386 但无法安装它
                             推荐: libgssapi-krb5-2:i386 但是它将不会被安装
                             推荐: libkrb5-3:i386 但是它将不会被安装
                             推荐: libsane:i386 但是它将不会被安装 或
                                     libsane1:i386
                             推荐: libxslt1.1:i386 但是它将不会被安装

**Comment by zq1997** [comment]
请先参考README
