### ISSUE TITLE
作者您好，非常感谢您的工作。我是在chromeOS中使用Debian虚拟机的用户，安装了软件后无论是logout或者reboot虚拟机，甚至是电脑，都没有办法显示出来应用图标，请问有没有解决办法，非常感谢！

### ISSUE THREAD

**Issue by HortiCarrillo** [zq1997/deepin-wine#148]
PRETTY_NAME="Debian GNU/Linux 10 (buster)"
NAME="Debian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster

**Comment by zq1997** [comment]
看下`echo $XDG_DATA_DIRS`的结果

**Comment by HortiCarrillo** [comment]
> 看下`echo $XDG_DATA_DIRS`的结果

cauyxk@penguin:~$ echo $XDG_DATA_DIRS
/home/cauyaoxiukun/.local/share:/home/cauyaoxiukun/.local/share/flatpak/exports/share:/var/lib/flatpak/exports/share:/usr/local/share:/usr/share:/var/lib/snapd/desktop:/opt/apps/com.qq.im.deepin/entries:/opt/apps/com.qq.weixin.deepin/entries:/opt/apps/net.cnki.cajviewer/entries

**Comment by zq1997** [comment]
设置正常。
可能是这个DE不兼容

**Comment by zq1997** [comment]
可能必须自己手动启动文件了，如`/opt/apps/com.qq.weixin.deepin/entries/applications/com.qq.weixin.deepin.desktop`

**Comment by HortiCarrillo** [comment]
好的，感谢
