### ISSUE TITLE
linux mint的QQ、微信、钉钉来新消息会自动打开

### ISSUE THREAD

**Issue by po888375** [zq1997/deepin-wine#149]
echo $XDG_CURRENT_DESKTOP输出：X-Cinnamon
lsb_release -a输出：
No LSB modules are available.
Distributor ID:	Linuxmint
Description:	Linux Mint 20.1
Release:	20.1
Codename:	ulyssa
问题描述：linux mint的QQ、微信、钉钉来新消息会自动打开，有大哥知道怎么回事吗

**Comment by zq1997** [comment]
确实。
另外把QQ❌掉，最小到托盘就行。
我之前用mint也是这个问题，后来用ubuntu就没这个问题。

**Comment by po888375** [comment]
> 确实。
> 另外把QQ掉，最小到托盘就行。
> 我之前用mint也是这个问题，后来用ubuntu就没这个问题。

但是把窗口关了，来消息又要去打开，而且有时候聊天等待消息的时候还要干其他事情，就很蛋疼。。

**Comment by grassvalley** [comment]
我用mint也遇到这个问题，在与人讨论问题时，非常不恰当地弹出来微信聊天窗口，非常尴尬！

**Comment by abcfyk** [comment]
manjaro 有同样的问题

**Comment by phpluo** [comment]
> echo $XDG_CURRENT_DESKTOP输出：X-Cinnamon
> lsb_release -a输出：
> No LSB modules are available.
> Distributor ID: Linuxmint
> Description: Linux Mint 20.1
> Release: 20.1
> Codename: ulyssa
> 问题描述：linux mint的QQ、微信、钉钉来新消息会自动打开，有大哥知道怎么回事吗

现在mint20.2没有这个问题了吧，我在虚拟机试了 是不会弹出来了。
