### ISSUE TITLE
Ubuntu 20.04钉钉安装后输入框问题

### ISSUE THREAD

**Issue by BEaN001** [zq1997/deepin-wine#153]
输入框无法显示，但是能发送信息。

**Comment by jonbenzhang** [comment]
遇到了同样问题，解决了吗

**Comment by jonbenzhang** [comment]
我的解决了
.deepinwine/Deepin-WeChat/drive_c/windows/system32/riched20.dll
#这个文件替换掉
[riched20.zip](https://github.com/zq1997/deepin-wine/files/7450752/riched20.zip)
