### ISSUE TITLE
微信和钉钉的.desktop文件在哪儿？

### ISSUE THREAD

**Issue by grassvalley** [zq1997/deepin-wine#156]
一般安装的应用程序，都会生成一个 .desktop 文件，存放在 /usr/share/applications 文件夹下。但是我在这个文件夹下并没有找到对应的 .desktop 文件。在 ~/.local/share/applications 文件夹下也没有找到。

那么，deepin-wine 是没有采用 .desktop 这种规范，还是放到了其他位置？

**Comment by TimingX** [comment]
在这里，如QQ的 /opt/apps/com.qq.im.deepin/entries/applications

**Comment by MakerFace** [comment]
> 在这里，如QQ的 /opt/apps/com.qq.im.deepin/entries/applications

厉害了，找了好久
