### ISSUE TITLE
apt update 提示证书不可信，一直更新不了

### ISSUE THREAD

**Issue by zengguangzhong** [zq1997/deepin-wine#157]
https://deepin-wine.i-m.dev/https/community-store-packages.deepin.com/appstore/pool/appstore/d/deepin-wine-helper/deepin-wine-helper_5.1.13-1_i386.deb  Certificate verification failed: The certificate is NOT trusted. The certificate issuer is unknown.  Could not handshake: Error in the certificate verification

**Comment by zq1997** [comment]
浏览器可以直接下载的，应该是客户端问题

**Comment by zengguangzhong** [comment]
![image](https://user-images.githubusercontent.com/20290798/115992561-e78e3700-a600-11eb-80fc-4d3d6fc5af14.png)


我现在只要update 就一直有这个提示，本地证书都没问题，下载安装其它的包都可以。能解决吗？大佬

**Comment by zq1997** [comment]
看一下`curl -vi https://deepin-wine.i-m.dev`

**Comment by zengguangzhong** [comment]
![Uploading image.png…]()


能加下微信指导下吗  ？大佬  ，微信号：yunplan

**Comment by zengguangzhong** [comment]
![image](https://user-images.githubusercontent.com/20290798/115996565-62138280-a612-11eb-8b5c-95fdfddb6ef7.png)

能加下微信指导下吗 ？大佬 ，微信号：yunplan

**Comment by zq1997** [comment]
https证书没有认证通过，难道是这个系统（看UI不是ubuntu）内安装的CA证书比较特殊？没有包含DST ROOT CA X3？
或者你之前动过ssl证书？
不太习惯微信加陌生人，抱歉

**Comment by zengguangzhong** [comment]
我的是mint 20.1 ，我没动过证书。

![image](https://user-images.githubusercontent.com/20290798/115996748-2c22ce00-a613-11eb-99e0-226ac4c52f35.png)

你说的这个证书我看了有。就在路劲：/etc/ssl/certs 下

**Comment by zq1997** [comment]
`ls /etc/ssl/certs/ca-certificates.crt -al`

**Comment by zengguangzhong** [comment]
![image](https://user-images.githubusercontent.com/20290798/115996880-a18e9e80-a613-11eb-9dbe-6fa3966156da.png)

**Comment by zq1997** [comment]
`curl -vI https://www.baidu.com`

**Comment by zengguangzhong** [comment]
![image](https://user-images.githubusercontent.com/20290798/115996970-f7634680-a613-11eb-9742-2f6a03b1c375.png)

**Comment by zq1997** [comment]
那就不关这个仓库的问题了，先修复百度的问题

**Comment by zengguangzhong** [comment]
咋修复有思路吗？

**Comment by zq1997** [comment]
不清楚之前有过什么动作，不好猜测。
总之现在是ssl认证过程被破坏了

**Comment by zengguangzhong** [comment]
我好像在root下就正常了。

**Comment by zengguangzhong** [comment]
另外有个问题  微信收到消息后自动弹出来。有办法吗

**Comment by zengguangzhong** [comment]
![image](https://user-images.githubusercontent.com/20290798/115997700-b6b8fc80-a616-11eb-814f-981245f32313.png)

我在root下，请求百度没问题。但是apt update 上面的还是有问题

**Comment by zq1997** [comment]
update用的是nobody账户

**Comment by zengguangzhong** [comment]
我在update前加了sudo的也是Nobody账户？

**Comment by zq1997** [comment]
是的

**Comment by zengguangzhong** [comment]
没有参数能使用root身份更新吗

**Comment by zq1997** [comment]
不能

**Comment by zengguangzhong** [comment]
解决了  chmod 755 /etc/ssl/certs 即可
