### ISSUE TITLE
无法访问deepin商店源

### ISSUE THREAD

**Issue by zzonnee** [zq1997/deepin-wine#162]
$ sudo apt-get install com.qq.weixin.deepin
Err:1 https://deepin-wine.i-m.dev  com.qq.weixin.deepin 2.9.5.41deepin7
  404  Not Found [IP: 58.51.151.5 443]
E: Failed to fetch https://community-store-packages.deepin.com/appstore/pool/appstore/c/com.qq.weixin.deepin/com.qq.weixin.deepin_2.9.5.41deepin7_i386.deb  404  Not Found [IP: 58.51.151.5 443]
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?

**Comment by zq1997** [comment]
上游刚更新了
