### ISSUE TITLE
微信和QQ界面大小无法调整

### ISSUE THREAD

**Issue by PhoneSix** [zq1997/deepin-wine#168]
感谢你的工作. 我下载了微信和QQ, 可以成功登陆, 但是界面非常小, 看着费眼睛. 我试图通过缩放显示器来解决, 但微信和QQ的界面大小没有随之改变. 有什么建议吗? 非常感谢!

**Comment by PhoneSix** [comment]
搞定了,通过改变dpi解决了

**Comment by Richard-LXA** [comment]
> 搞定了,通过改变dpi解决了

请问咋解决的啊

**Comment by ccll** [comment]
这issue发起者真是搞笑，自己解决了不说咋解决的。

给 @Richard-LXA 和所有类似问题的同伴。

我是这么解决的:
1. 运行winecfg
```
env WINEPREFIX=/home/<your home>/.deepinwine/Deepin-WeChat deepin-wine6-stable winecfg
```

2. 在 'Graphics' tab里，选上'Allow the window manager to decorate the windows'。

3. 再运行 WeChat，就可以拖拽改大小了。

**Comment by PhoneSix** [comment]
@ccll 首先我给出了解决方案的关键词，因为我比较懒，所以只给了关键词，我觉得搜索一下关键词就能找到解决方案。其次，你详细分享了你的解决方案，我觉得你的做法很棒。最后，直接说我搞笑，你礼貌吗？？？

**Comment by Cielstar** [comment]
> 这issue发起者真是搞笑，自己解决了不说咋解决的。
> 
> 给 @Richard-LXA 和所有类似问题的同伴。
> 
> 我是这么解决的:
> 
>     1. 运行winecfg
> 
> 
> ```
> env WINEPREFIX=/home/<your home>/.deepinwine/Deepin-WeChat deepin-wine6-stable winecfg
> ```
> 
>     2. 在 'Graphics' tab里，选上'Allow the window manager to decorate the windows'。
> 
>     3. 再运行 WeChat，就可以拖拽改大小了。

大佬我运行了这条命令，显示没有winecfg这个文件或目录啊，Tim也这样

**Comment by tai-yi-c** [comment]
> Chat deepin-wine6-stable winecfg

大佬，我运行了那个命令之后，但是打开微信没什么变化，当我再次运行命令之后，发现改动没有了。

在这之后，我又改了一次之后，通过运行命令检查改动，确实保存下来了。但是一旦我打开微信，改动就消失了，可以请大佬解惑吗。

我是ubuntu22.04

**Comment by MarkShawn2020** [comment]
> 

默认dpi是96，如果你用的是mac，retina resolution的话，直接改成2倍（192）即可，也不需要拖了，2倍就是对应的标准dpi

**Comment by MarkShawn2020** [comment]
>     2. 在 'Graphics' tab里，选上'Allow the window manager to decorate the windows'。

默认dpi是96，如果你用的是mac，retina resolution的话，直接改成2倍（192）即可，也不需要拖了，2倍就是对应的标准dpi

**Comment by nowhereman1999** [comment]
> > Chat deepin-wine6-stable winecfg
> 
> 大佬，我运行了那个命令之后，但是打开微信没什么变化，当我再次运行命令之后，发现改动没有了。
> 
> 在这之后，我又改了一次之后，通过运行命令检查改动，确实保存下来了。但是一旦我打开微信，改动就消失了，可以请大佬解惑吗。
> 
> 我是ubuntu22.04

请问你解决了吗,我是mint21,然后按照前面大佬的教程Allow the window manager to decorate the windows之后仍然无法拖拽改大小

**Comment by nowhereman1999** [comment]
> > ```
> > 2. 在 'Graphics' tab里，选上'Allow the window manager to decorate the windows'。
> > ```
> 
> 默认dpi是96，如果你用的是mac，retina resolution的话，直接改成2倍（192）即可，也不需要拖了，2倍就是对应的标准dpi

大佬,你好,我使用的是mint21,然后安装了whitesur的macos主题,如果我显示设置为100%缩放的话,tim的界面看起来就没什么问题,但是我安装的dock就会错位:
![image](https://user-images.githubusercontent.com/53631206/205314054-0f49fe33-1a0a-4757-bac0-4bb0af671166.png)
如果我将缩放改为125%,那么我的dock就恢复正常,但是tim的大小又有问题:
![image](https://user-images.githubusercontent.com/53631206/205314279-fa852af0-bf9c-4be5-9aca-e6a0ec1c0c7f.png)
请问我这种情况该如何解决呢?
