### ISSUE TITLE
Ubuntu 21.04下安装微信失败

### ISSUE THREAD

**Issue by pay46** [zq1997/deepin-wine#173]
提示以下错误

The following packages have unmet dependencies:
 libgirepository-1.0-1 : Breaks: python-gi (< 3.34.0-4~) but 3.30.4-1 is to be installed
E: Unable to correct problems, you have held broken packages.

**Comment by zq1997** [comment]
21.04的`python-gi`已经升级到了3.36.0-1

**Comment by abcfyk** [comment]
试试这个： https://serverfault.com/questions/250224/how-do-i-get-apt-get-to-ignore-some-dependencies

**Comment by sqlAIJava** [comment]
所以应该如何正确安装呢 宝～

**Comment by pay46** [comment]
谢谢
