### ISSUE TITLE
微信安装成功，点击闪一下就没了

### ISSUE THREAD

**Issue by chenloveheimei** [zq1997/deepin-wine#176]
### 1. 环境

(p37) long@long-Ubuntu:~$ echo $XDG_CURRENT_DESKTOP
ubuntu:GNOME
(p37) long@long-Ubuntu:~$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.2 LTS
Release:	20.04
Codename:	focal
(p37) long@long-Ubuntu:~$ grep -rn '^\s*deb ' --include '*.list' /etc/apt/
/etc/apt/sources.list.d/google-chrome.list:3:deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main
/etc/apt/sources.list.d/deepin-wine.i-m.dev.list:1:deb [trusted=yes] https://deepin-wine.i-m.dev /
/etc/apt/sources.list:5:deb http://cn.archive.ubuntu.com/ubuntu/ focal main restricted
/etc/apt/sources.list:10:deb http://cn.archive.ubuntu.com/ubuntu/ focal-updates main restricted
/etc/apt/sources.list:16:deb http://cn.archive.ubuntu.com/ubuntu/ focal universe
/etc/apt/sources.list:18:deb http://cn.archive.ubuntu.com/ubuntu/ focal-updates universe
/etc/apt/sources.list:26:deb http://cn.archive.ubuntu.com/ubuntu/ focal multiverse
/etc/apt/sources.list:28:deb http://cn.archive.ubuntu.com/ubuntu/ focal-updates multiverse
/etc/apt/sources.list:36:deb http://cn.archive.ubuntu.com/ubuntu/ focal-backports main restricted universe multiverse
/etc/apt/sources.list:46:deb http://security.ubuntu.com/ubuntu focal-security main restricted
/etc/apt/sources.list:48:deb http://security.ubuntu.com/ubuntu focal-security universe
/etc/apt/sources.list:50:deb http://security.ubuntu.com/ubuntu focal-security multiverse

### 2. 运行 run.sh

(p37) long@long-Ubuntu:/opt/apps/com.qq.weixin.deepin/files$ sudo ./run.sh 
Run Deepin-WeChat 3.2.1.154deepin8 c:/Program Files/Tencent/WeChat/WeChat.exe
run Deepin-WeChat progress pid 
总用量 0
lrwxrwxrwx 1 root root 10 6月  25 21:18 c: -> ../drive_c
lrwxrwxrwx 1 root root 10 6月  25 19:34 com1 -> /dev/ttyS0
lrwxrwxrwx 1 root root 10 6月  25 19:34 com10 -> /dev/ttyS9
lrwxrwxrwx 1 root root 11 6月  25 19:34 com11 -> /dev/ttyS10
lrwxrwxrwx 1 root root 11 6月  25 19:34 com12 -> /dev/ttyS11
lrwxrwxrwx 1 root root 11 6月  25 19:34 com13 -> /dev/ttyS12
lrwxrwxrwx 1 root root 11 6月  25 19:34 com14 -> /dev/ttyS13
lrwxrwxrwx 1 root root 11 6月  25 19:34 com15 -> /dev/ttyS14
lrwxrwxrwx 1 root root 11 6月  25 19:34 com16 -> /dev/ttyS15
lrwxrwxrwx 1 root root 11 6月  25 19:34 com17 -> /dev/ttyS16
lrwxrwxrwx 1 root root 11 6月  25 19:34 com18 -> /dev/ttyS17
lrwxrwxrwx 1 root root 11 6月  25 19:34 com19 -> /dev/ttyS18
lrwxrwxrwx 1 root root 10 6月  25 19:34 com2 -> /dev/ttyS1
lrwxrwxrwx 1 root root 11 6月  25 19:34 com20 -> /dev/ttyS19
lrwxrwxrwx 1 root root 11 6月  25 19:34 com21 -> /dev/ttyS20
lrwxrwxrwx 1 root root 11 6月  25 19:34 com22 -> /dev/ttyS21
lrwxrwxrwx 1 root root 11 6月  25 19:34 com23 -> /dev/ttyS22
lrwxrwxrwx 1 root root 11 6月  25 19:34 com24 -> /dev/ttyS23
lrwxrwxrwx 1 root root 11 6月  25 19:34 com25 -> /dev/ttyS24
lrwxrwxrwx 1 root root 11 6月  25 19:34 com26 -> /dev/ttyS25
lrwxrwxrwx 1 root root 11 6月  25 19:34 com27 -> /dev/ttyS26
lrwxrwxrwx 1 root root 11 6月  25 19:34 com28 -> /dev/ttyS27
lrwxrwxrwx 1 root root 11 6月  25 19:34 com29 -> /dev/ttyS28
lrwxrwxrwx 1 root root 10 6月  25 19:34 com3 -> /dev/ttyS2
lrwxrwxrwx 1 root root 11 6月  25 19:34 com30 -> /dev/ttyS29
lrwxrwxrwx 1 root root 11 6月  25 19:34 com31 -> /dev/ttyS30
lrwxrwxrwx 1 root root 11 6月  25 19:34 com32 -> /dev/ttyS31
lrwxrwxrwx 1 root root 10 6月  25 19:34 com4 -> /dev/ttyS3
lrwxrwxrwx 1 root root 10 6月  25 19:34 com5 -> /dev/ttyS4
lrwxrwxrwx 1 root root 10 6月  25 19:34 com6 -> /dev/ttyS5
lrwxrwxrwx 1 root root 10 6月  25 19:34 com7 -> /dev/ttyS6
lrwxrwxrwx 1 root root 10 6月  25 19:34 com8 -> /dev/ttyS7
lrwxrwxrwx 1 root root 10 6月  25 19:34 com9 -> /dev/ttyS8
lrwxrwxrwx 1 root root  8 6月  25 19:30 d:: -> /dev/sr0
lrwxrwxrwx 1 root root  5 6月  25 21:18 y: -> /root
lrwxrwxrwx 1 root root  1 6月  25 21:18 z: -> /
CallApp Deepin-WeChat c:/Program Files/Tencent/WeChat/WeChat.exe
Disable auto update
rm: 无法删除 '/root/.deepinwine/Deepin-WeChat/drive_c/users/root/Application Data/Tencent/WeChat/All Users/config/configEx.ini': 没有那个文件或目录
2021年 06月 25日 星期五 21:18:12 CST:kill WeChat.exe block
cat: /proc/5273/maps: 没有那个文件或目录
cat: /proc/5273/maps: 没有那个文件或目录
2021年 06月 25日 星期五 21:18:12 CST:tag bottle: 
Traceback (most recent call last):
  File "/root/.deepinwine/deepin-wine-helper/get_tray_window", line 28, in <module>
    get_tray_window()
  File "/root/.deepinwine/deepin-wine-helper/get_tray_window", line 18, in get_tray_window
    traymanager = bus.get_object("com.deepin.dde.TrayManager", "/com/deepin/dde/TrayManager")
  File "/usr/lib/python2.7/dist-packages/dbus/bus.py", line 243, in get_object
    follow_name_owner_changes=follow_name_owner_changes)
  File "/usr/lib/python2.7/dist-packages/dbus/proxies.py", line 250, in __init__
    self._named_service = conn.activate_name_owner(bus_name)
  File "/usr/lib/python2.7/dist-packages/dbus/bus.py", line 182, in activate_name_owner
    self.start_service_by_name(bus_name)
  File "/usr/lib/python2.7/dist-packages/dbus/bus.py", line 280, in start_service_by_name
    'su', (bus_name, flags)))
  File "/usr/lib/python2.7/dist-packages/dbus/connection.py", line 653, in call_blocking
    message, timeout)
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.ServiceUnknown: The name com.deepin.dde.TrayManager was not provided by any .service files
2021年 06月 25日 星期五 21:18:12 CST:active bottles: 
/root/.deepinwine/Deepin-WeChat/drive_c/Program Files/Tencent/WeChat
(p37) long@long-Ubuntu:/opt/apps/com.qq.weixin.deepin/files$ 010c:fixme:font:get_name_record_codepage encoding 29 not handled, platform 1.
010c:fixme:font:get_name_record_codepage encoding 29 not handled, platform 1.
010c:fixme:font:get_name_record_codepage encoding 29 not handled, platform 1.
010c:fixme:font:get_name_record_codepage encoding 29 not handled, platform 1.
0114:fixme:font:get_name_record_codepage encoding 29 not handled, platform 1.
0114:fixme:font:get_name_record_codepage encoding 29 not handled, platform 1.
0114:fixme:font:get_name_record_codepage encoding 29 not handled, platform 1.
0114:fixme:font:get_name_record_codepage encoding 29 not handled, platform 1.
010c:fixme:font:get_name_record_codepage encoding 20 not handled, platform 1.
010c:fixme:font:get_name_record_codepage encoding 20 not handled, platform 1.
0114:fixme:font:get_name_record_codepage encoding 20 not handled, platform 1.
0114:fixme:font:get_name_record_codepage encoding 20 not handled, platform 1.
010c:fixme:process:SetProcessDEPPolicy (3): stub
010c:err:winediag:SECUR32_initNTLMSP ntlm_auth was not found or is outdated. Make sure that ntlm_auth >= 3.0.25 is in your path. Usually, you can find it in the winbind package of your distribution.
0118:fixme:ver:GetCurrentPackageId (053FFF00 00000000): stub
0118:fixme:sync:SetWaitableTimerEx (000000E0, 053FFDB0, 0, 00000000, 00000000, 00000000, 1500) semi-stub
014c:fixme:winsock:fix_send_is_blocking_state is_blocking = 0, is_EAGAIN = 11
0154:fixme:iphlpapi:NotifyAddrChange (Handle 0x6cdff0c, overlapped 0x6cdfef4): stub
010c:fixme:win:RegisterTouchWindow (00010056 00000000): stub
015c:fixme:ole:CoInitializeSecurity 00000000, -1, 00000000, 00000000, 0, 3, 00000000, 0, 00000000 stub
015c:fixme:wbemprox:client_security_SetBlanket 772FFCA4, 07270778, 10, 0, (null), 3, 3, 00000000, 0x00000000
015c:fixme:wbemprox:client_security_Release 772FFCA4
015c:fixme:ole:CoInitializeSecurity 00000000, -1, 00000000, 00000000, 0, 3, 00000000, 0, 00000000 stub
015c:fixme:wbemprox:client_security_SetBlanket 772FFCA4, 07270778, 10, 0, (null), 3, 3, 00000000, 0x00000000
015c:fixme:wbemprox:client_security_Release 772FFCA4
015c:fixme:ole:CoInitializeSecurity 00000000, -1, 00000000, 00000000, 0, 3, 00000000, 0, 00000000 stub
015c:fixme:wbemprox:client_security_SetBlanket 772FFCA4, 07270778, 10, 0, (null), 3, 3, 00000000, 0x00000000
015c:fixme:wbemprox:client_security_Release 772FFCA4
015c:fixme:ole:CoInitializeSecurity 00000000, -1, 00000000, 00000000, 0, 3, 00000000, 0, 00000000 stub
015c:fixme:wbemprox:client_security_SetBlanket 772FFCA4, 0726BCE8, 10, 0, (null), 3, 3, 00000000, 0x00000000
015c:fixme:wbemprox:client_security_Release 772FFCA4
015c:fixme:ole:CoInitializeSecurity 00000000, -1, 00000000, 00000000, 0, 3, 00000000, 0, 00000000 stub
015c:fixme:wbemprox:client_security_SetBlanket 772FFCA4, 0726BCE8, 10, 0, (null), 3, 3, 00000000, 0x00000000
015c:fixme:wbemprox:client_security_Release 772FFCA4
0158:fixme:wlanapi:WlanEnumInterfaces (00000001, 00000000, 060EEC5C) semi-stub
015c:fixme:ole:CoInitializeSecurity 00000000, -1, 00000000, 00000000, 0, 3, 00000000, 0, 00000000 stub
015c:fixme:wbemprox:client_security_SetBlanket 772FFCA4, 0726C9E8, 10, 0, (null), 3, 3, 00000000, 0x00000000
015c:fixme:wbemprox:client_security_Release 772FFCA4
015c:fixme:ntdll:NtQuerySystemInformation info_class SYSTEM_PERFORMANCE_INFORMATION
015c:fixme:ole:CoInitializeSecurity 00000000, -1, 00000000, 00000000, 0, 3, 00000000, 0, 00000000 stub
015c:fixme:wbemprox:client_security_SetBlanket 772FFCA4, 052F1D30, 10, 0, (null), 3, 3, 00000000, 0x00000000
015c:fixme:wbemprox:client_security_Release 772FFCA4
010c:fixme:heap:RtlSetHeapInformation 00000000 1 00000000 0 stub
010c:fixme:ntdll:EtwEventRegister ({d2d578d9-2936-45b6-a09f-30e32715f42d}, 10135670, 1382ED80, 138A9108) stub.
[0625/211817:INFO:exception_record.cc(518)] [QB]Process ID: 264 Type: 1
X Error of failed request:  BadValue (integer parameter out of range for operation)
  Major opcode of failed request:  152 (GLX)
  Minor opcode of failed request:  3 (X_GLXCreateContext)
  Value in failed request:  0x0
  Serial number of failed request:  275
  Current serial number in output stream:  276

### 3. 问题
安装是成功了。
按ReadMe里面写的，清理过了，也不行。
高级文档配置也不行

**Comment by chenloveheimei** [comment]
终于知道原因了，要重装nvidia，装的时候在sudo ./NVIDIA-Linux-x86_64-XXX.XXX.run -no-x-check -no-nouveau-check -no-opengl-files 把OpenGL去掉，然后就没问题了

**Comment by zq1997** [comment]
驱动一般推荐apt安装

**Comment by chenloveheimei** [comment]
> 驱动一般推荐apt安装

你好，想问下企业微信装不了，好像找不到网站了，要怎么处理呢

**Comment by zq1997** [comment]
com.qq.weixin.work.deepin

**Comment by chenloveheimei** [comment]
> com.qq.weixin.work.deepin

sudo(p37) long@long-Ubuntu:~$ sudo apt install com.qq.weixin.work.deepin
正在读取软件包列表... 完成
正在分析软件包的依赖关系树       
正在读取状态信息... 完成       
下列【新】软件包将被安装：
  com.qq.weixin.work.deepin:i386
升级了 0 个软件包，新安装了 1 个软件包，要卸载 0 个软件包，有 128 个软件包未被升级。
需要下载 473 MB 的归档。
解压缩后会消耗 529 MB 的额外空间。
错误:1 https://deepin-wine.i-m.dev  com.qq.weixin.work.deepin 3.1.6.3605deepin3
  404  Not Found [IP: 61.54.25.98 443]
E: 无法下载 https://community-store-packages.deepin.com/appstore/pool/appstore/c/com.qq.weixin.work.deepin/com.qq.weixin.work.deepin_3.1.6.3605deepin3_i386.deb  404  Not Found [IP: 61.54.25.98 443]
E: 有几个软件包无法下载，要不运行 apt-get update 或者加上 --fix-missing 的选项再试试？


下载不了

**Comment by zq1997** [comment]
apt update

**Comment by chenloveheimei** [comment]
> apt update

ok，搞定。
想问下里面的photoshop是破解的还是有使用限制时间的？
