### ISSUE TITLE
高分屏下显示比例太小

### ISSUE THREAD

**Issue by AkaraChen** [zq1997/deepin-wine#182]
Ubuntu 20.04 LTS，正常通过这个仓库的方式安装了qq，使用起来似乎一切正常，唯一美中不足的是，显示比例是在是太小了，字体太小，完全看不清
也许可以通过修改wine配置文件找到方法，但是我尝试google了以下，但是找到的资料无法解决我的问题

**Comment by AkaraChen** [comment]
Google后的结果都是类似于`env WINEPREFIX="$HOME/.deepinwine/Deepin-QQ" winecfg`这种，但是没有一种的是有效的

**Comment by zhang8473** [comment]
看 https://github.com/zq1997/deepin-wine/issues/175 其他app解决方案类似。
