### ISSUE TITLE
ubuntu 4K 屏幕字体太小

### ISSUE THREAD

**Issue by Privilger** [zq1997/deepin-wine#185]
如题，请问是需要对wine添加一些设置么？

**Comment by Silence2540** [comment]
用下面这个命令打开wine设置界面，如果是其它应用，可以把Deepin-QQ替换成对应的应用名（`~/.deepinwine/`下可以找到），在设置窗口的显示选项卡的屏幕分辨率可以调整，记得先关掉对应的应用：
`env WINEPREFIX="$HOME/.deepinwine/Deepin-QQ" "$HOME/.deepinwine/deepin-wine5/bin/wine" winecfg`
（ubuntu20.04自测可行）

**Comment by Privilger** [comment]
LGTM
