### ISSUE TITLE
源里好像没有微信了，只剩下企业版微信

### ISSUE THREAD

**Issue by greatyingzi** [zq1997/deepin-wine#192]
![2021-08-12_20-01](https://user-images.githubusercontent.com/20220018/129193529-9e1f3101-4021-4fb0-a0fa-a33b29ea6f87.png)

**Comment by 11D-Beyonder** [comment]
是的，找不到软件包。

**Comment by ronald6818** [comment]
这个还能用吗

**Comment by greatyingzi** [comment]
> 这个还能用吗

别的软件还是可以继续安装使用的，只是微信装不了了

**Comment by pay46** [comment]
遇到同样问题，请问微信还会更新吗？

**Comment by ZenBoy999** [comment]
Just changed to a new machine, found no  package named: com.qq.weixin.deepin. 
Too sad.

**Comment by xiewjsir** [comment]
还是没有

**Comment by xiewjsir** [comment]
急用的朋友可以通过这个方式去安装：https://2dogz.cn/blog/article/15/
