### ISSUE TITLE
qq当前版本已经无法使用了

### ISSUE THREAD

**Issue by zlfccnu** [zq1997/deepin-wine#20]
貌似deepin源里面的qq已经无法登录了？

**Comment by zq1997** [comment]
不会啊，我刚重装了一次。

**Comment by zlfccnu** [comment]
貌似是部分，deepin论坛里面已经反应了，已经放出了最新版的包，我刚装是8.9，这个版本无法登录了。

**Comment by zq1997** [comment]
可以放一个论坛链接么？

**Comment by zlfccnu** [comment]
http://packages.deepin.com/deepin/pool/non-free/d/deepin.com.qq.im/

**Comment by zlfccnu** [comment]
里面有9.1.8了

**Comment by zlfccnu** [comment]
但是我直接apt-get 还是8.9,这个源不是直接同步deepin的吗？

**Comment by zlfccnu** [comment]
https://bbs.deepin.org/forum.php?mod=viewthread&tid=183719&extra=
这是之前官方测试的帖子

**Comment by zq1997** [comment]
我去，刚才我脑子里一直想的是TIM，刚发现QQ确实是更新了

**Comment by zlfccnu** [comment]
很新鲜热乎的，ubuntu上需要特别的设置安装吗？因为直接apt-get还是不能安装9.1.8版本。我正在下载deb包

**Comment by zq1997** [comment]
确认了，过一段时间用`apt update + apt dist-upgrade`就可以升级上去。
但这个点还不行，因为我的仓库是从清华源扒的，这个快，清华的现在还没更新，所以我得等它。不过应该就是一两天的事情。

**Comment by zq1997** [comment]
关注这个地址[https://mirrors.tuna.tsinghua.edu.cn/deepin/pool/non-free/d/deepin.com.qq.im/](https://mirrors.tuna.tsinghua.edu.cn/deepin/pool/non-free/d/deepin.com.qq.im/)
这里更新了我就能更新。

**Comment by zq1997** [comment]
好像清华源显示同步中，应该明天早上就能行的

**Comment by zlfccnu** [comment]
好的，那明早直接升级吧，但是我下载官方直接安装显示
`Dependency is not satisfiable: deepin-wine32-preloader`

**Comment by zq1997** [comment]
因为官网的那个热乎版依赖包也升级了，直接下载安装是不行的，你得手动把其他依赖一个一个都更新。
或者等这个仓库同步好了apt升级，自动处理依赖。

**Comment by zlfccnu** [comment]
> 因为官网的那个热乎版依赖包也升级了，直接下载安装是不行的，你得手动把其他依赖一个一个都更新。
> 或者等这个仓库同步好了apt升级，自动处理依赖。

ok,了解，估计明早就ok了

**Comment by zq1997** [comment]
应该能用了吧？

**Comment by FindHao** [comment]
新的9.1打不开。
`wine version: 2.18
libGL error: No matching fbConfigs or visuals found
libGL error: failed to load driver: swrast
X Error of failed request:  GLXBadContext
  Major opcode of failed request:  151 (GLX)
  Minor opcode of failed request:  6 (X_GLXIsDirect)
  Serial number of failed request:  201
  Current serial number in output stream:  200

`
但是我之前没用命令行打开过8.9，所以不确定是不是上面的问题导致的。

**Comment by zq1997** [comment]
@FindHao 安装README的清理步骤先清理并且重装一下试试

**Comment by YaoLaiGang** [comment]
> @FindHao 安装README的清理步骤先清理并且重装一下试试

请问使用上了么？为什么我安装最新的基本上无法使用，卡顿非常严重？

**Comment by zq1997** [comment]
@YaoLaiGang 我用linux mint 19.2测试没有卡顿

**Comment by FindHao** [comment]
> > @FindHao 安装README的清理步骤先清理并且重装一下试试
> 
> 请问使用上了么？为什么我安装最新的基本上无法使用，卡顿非常严重？

并没有。我现在正在用tim。
