### ISSUE TITLE
Ubuntu20.04下微信(3.2.154deepin13)无法启动.

### ISSUE THREAD

**Issue by qicai21** [zq1997/deepin-wine#200]
差不多1个月没登录ubuntu,1周前上来,发现微信登录不了,反复提示"微信遇到错误,错误编号:2835F49F86746E1E7ECE1AD45C4E326B".

完整删除微信,去除deepin后重装,反复多次依然无法解决.

~/.deepinwine/Deepin-Wechat/下文件看起来也完整,i386也添加正确了.

--------------------------------------------
.deepinwine/Deepin-WeChat/
├── dosdevices
│   ├── c: -> ../drive_c
│   ├── com1 -> /dev/ttyS0
│   ├── com10 -> /dev/ttyS9
│   ├── com11 -> /dev/ttyS10
│   ├── com12 -> /dev/ttyS11
│   ├── com13 -> /dev/ttyS12
│   ├── com14 -> /dev/ttyS13
│   ├── com15 -> /dev/ttyS14
│   ├── com16 -> /dev/ttyS15
│   ├── com17 -> /dev/ttyS16
│   ├── com18 -> /dev/ttyS17
│   ├── com19 -> /dev/ttyS18
│   ├── com2 -> /dev/ttyS1
│   ├── com20 -> /dev/ttyS19
│   ├── com21 -> /dev/ttyS20
│   ├── com22 -> /dev/ttyS21
│   ├── com23 -> /dev/ttyS22
│   ├── com24 -> /dev/ttyS23
│   ├── com25 -> /dev/ttyS24
│   ├── com26 -> /dev/ttyS25
│   ├── com27 -> /dev/ttyS26
│   ├── com28 -> /dev/ttyS27
│   ├── com29 -> /dev/ttyS28
│   ├── com3 -> /dev/ttyS2
│   ├── com30 -> /dev/ttyS29
│   ├── com31 -> /dev/ttyS30
│   ├── com32 -> /dev/ttyS31
│   ├── com4 -> /dev/ttyS3
│   ├── com5 -> /dev/ttyS4
│   ├── com6 -> /dev/ttyS5
│   ├── com7 -> /dev/ttyS6
│   ├── com8 -> /dev/ttyS7
│   ├── com9 -> /dev/ttyS8
│   ├── d:: -> /dev/sr0
│   ├── y: -> /home/qicai21
│   └── z: -> /
├── drive_c
│   ├── deepin
│   ├── ProgramData
│   ├── Program Files
│   ├── users
│   └── windows
├── PACKAGE_VERSION
├── system.reg
├── update.policy
├── userdef.reg
├── user.reg
└── winx
    └── extensions.so -> /opt/apps/com.qq.weixin.deepin/files/extensions.so

------------------------------------
(base) qicai21@hasee:~$ echo $XDG_CURRENT_DESKTOP
ubuntu:GNOME
(base) qicai21@hasee:~$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.3 LTS
Release:	20.04
Codename:	focal
(base) qicai21@hasee:~$ grep -rn '^\s*deb ' --include '*.list' /etc/apt/
/etc/apt/sources.list:5:deb http://cn.archive.ubuntu.com/ubuntu/ focal main restricted
/etc/apt/sources.list:10:deb http://cn.archive.ubuntu.com/ubuntu/ focal-updates main restricted
/etc/apt/sources.list:16:deb http://cn.archive.ubuntu.com/ubuntu/ focal universe
/etc/apt/sources.list:18:deb http://cn.archive.ubuntu.com/ubuntu/ focal-updates universe
/etc/apt/sources.list:26:deb http://cn.archive.ubuntu.com/ubuntu/ focal multiverse
/etc/apt/sources.list:28:deb http://cn.archive.ubuntu.com/ubuntu/ focal-updates multiverse
/etc/apt/sources.list:36:deb http://cn.archive.ubuntu.com/ubuntu/ focal-backports main restricted universe multiverse
/etc/apt/sources.list:46:deb http://security.ubuntu.com/ubuntu focal-security main restricted
/etc/apt/sources.list:48:deb http://security.ubuntu.com/ubuntu focal-security universe
/etc/apt/sources.list:50:deb http://security.ubuntu.com/ubuntu focal-security multiverse
/etc/apt/sources.list:58:deb https://typora.io/linux ./
/etc/apt/sources.list:60:deb https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2004/x86_64/ /
/etc/apt/sources.list.d/steam.list:1:deb [arch=amd64,i386] https://repo.steampowered.com/steam/ stable steam
/etc/apt/sources.list.d/eugenesan-ubuntu-ppa-focal.list:1:deb http://ppa.launchpad.net/eugenesan/ppa/ubuntu focal main
/etc/apt/sources.list.d/nodesource.list:1:deb https://deb.nodesource.com/node_14.x focal main
/etc/apt/sources.list.d/linuxuprising-ubuntu-java-focal.list:1:deb http://ppa.launchpad.net/linuxuprising/java/ubuntu focal main
/etc/apt/sources.list.d/v2ray.list:1:deb [arch=amd64] https://apt.v2fly.org/ stable main
/etc/apt/sources.list.d/google-chrome.list:3:deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main
/etc/apt/sources.list.d/mongodb-org-4.4.list:1:deb [arch=amd64,arm64] https://repo.mongodb.org/apt/ubuntu focal/mongodb-org/4.4 multiverse
/etc/apt/sources.list.d/spotify.list:1:deb http://repository.spotify.com stable non-free
/etc/apt/sources.list.d/qv2ray.list:1:deb [arch=amd64] https://qv2ray.net/debian/ focal main
/etc/apt/sources.list.d/obsproject-ubuntu-obs-studio-focal.list:1:deb http://ppa.launchpad.net/obsproject/obs-studio/ubuntu focal main
/etc/apt/sources.list.d/deepin-wine.i-m.dev.list:1:deb [trusted=yes] https://deepin-wine.i-m.dev /
/etc/apt/sources.list.d/skype-stable.list:1:deb [arch=amd64] https://repo.skype.com/deb stable main

**Comment by greatyingzi** [comment]
使用命令行启动，看下错误是什么。

**Comment by greatyingzi** [comment]
如果找不到问题，可以试试ukylin的微信https://www.ubuntukylin.com/applications/106-cn.html，我这边试过，这个也可以正常使用。

**Comment by CeciliaKasumi** [comment]
我也无法启动请问你的好了吗

**Comment by qicai21** [comment]
> 我也无法启动请问你的好了吗

没好,已经卸载了,暂时也没有使用的需求,就先不纠结了.看到有人ubuntu20_wechat3.2.154能够正常启动,估计是我某个包有冲突,应该是个人问题.
