### ISSUE TITLE
ubuntu20.04 新版企业微信 托盘图标不显示

### ISSUE THREAD

**Issue by phpluo** [zq1997/deepin-wine#213]
升级了新版企业微信后不显示托盘图标（
虚拟机新安装的也是一样的 图一是虚拟机截取的）
![tu1](https://user-images.githubusercontent.com/15026737/133018393-aa2aabc7-2d09-4ead-8c53-f3f53d54389b.png)
我从系统timeshift备份里赋值老版本出来  替换能正常显示
![2021-09-13_11-13](https://user-images.githubusercontent.com/15026737/133019044-d743be5d-8a4c-4bd1-80d4-8d3838cfe283.png)

![2021-09-13_11-16](https://user-images.githubusercontent.com/15026737/133018787-3f68b19e-1f5f-43e1-90ea-49d6c28ebf6b.png)
系统信息
![2021-09-13_11-17](https://user-images.githubusercontent.com/15026737/133018859-bafd1bef-1ce0-4352-9b87-dbd56528cb27.png)

**Comment by laraws** [comment]
遇到了同样的问题

**Comment by laraws** [comment]
> 升级了新版企业微信后不显示托盘图标（ 虚拟机新安装的也是一样的 图一是虚拟机截取的） ![tu1](https://user-images.githubusercontent.com/15026737/133018393-aa2aabc7-2d09-4ead-8c53-f3f53d54389b.png) 我从系统timeshift备份里赋值老版本出来 替换能正常显示 ![2021-09-13_11-13](https://user-images.githubusercontent.com/15026737/133019044-d743be5d-8a4c-4bd1-80d4-8d3838cfe283.png)
> 
> ![2021-09-13_11-16](https://user-images.githubusercontent.com/15026737/133018787-3f68b19e-1f5f-43e1-90ea-49d6c28ebf6b.png) 系统信息 ![2021-09-13_11-17](https://user-images.githubusercontent.com/15026737/133018859-bafd1bef-1ce0-4352-9b87-dbd56528cb27.png)

请问最后怎么解决的呢

**Comment by phpluo** [comment]
> > 升级了新版企业微信后不显示托盘图标（ 虚拟机新安装的也是一样的 图一是虚拟机截取的） ![tu1](https://user-images.githubusercontent.com/15026737/133018393-aa2aabc7-2d09-4ead-8c53-f3f53d54389b.png) 我从系统timeshift备份里赋值老版本出来 替换能正常显示 ![2021-09-13_11-13](https://user-images.githubusercontent.com/15026737/133019044-d743be5d-8a4c-4bd1-80d4-8d3838cfe283.png)
> > ![2021-09-13_11-16](https://user-images.githubusercontent.com/15026737/133018787-3f68b19e-1f5f-43e1-90ea-49d6c28ebf6b.png) 系统信息 ![2021-09-13_11-17](https://user-images.githubusercontent.com/15026737/133018859-bafd1bef-1ce0-4352-9b87-dbd56528cb27.png)
> 
> 请问最后怎么解决的呢

之前就是是使用老版本、后面升级 偶尔会出现图标消失 甚至占位符都没有的情况、每次都是重新运行企业 微信。 弃坑了。用了4、5年的mint和Ubuntu  现在入手mac m1 pro 了 真香
