### ISSUE TITLE
在 Ubuntu 21.10 上安装 qq python-gi 依赖冲突

### ISSUE THREAD

**Issue by linsui** [zq1997/deepin-wine#231]
在 Ubuntu 21.10 上安装 qq 有依赖冲突，ppa里的python-gi 版本过低。手动安装https://packages.ubuntu.com/zh-cn/focal/python-gi 之后可以正常安装。

**Comment by zq1997** [comment]
`python-gi`在ubuntu 20.10里被取缔了了，本仓库里带的`python-gi`由于版本问题会和其他软件冲突。#120 手动下载的`python-gi`其实是ubuntu 20.04提供的。

**Comment by linsui** [comment]
是的，所以能否解决这个冲突或者在文档里说明？

**Comment by zq1997** [comment]
临时把这个包加了进去。
主要是deepin一直在用python2，非常无奈，估计这种大软件他们那边也没精力去迁移，依赖了很多过时包。

**Comment by linsui** [comment]
非常感谢 :+1:
