### ISSUE TITLE
ubuntu20.04在11.11夜晚到现在下载完脚本后不会出现成功后的提示，apt安装无法定位软件包

### ISSUE THREAD

**Issue by erge6521** [zq1997/deepin-wine#235]
版本：Ubuntu20.04
异常描述：wget脚本成功，脚本执行后不再出现成功后的安装微信qq的示例等部分，apt安装包名无法定位软件
时间点：大概11.11夜晚10点之后
异常代码：
`wget -O- https://deepin-wine.i-m.dev/setup.sh | sh
--2021-11-12 09:25:29--  https://deepin-wine.i-m.dev/setup.sh
正在解析主机 deepin-wine.i-m.dev (deepin-wine.i-m.dev)... 104.198.14.52
正在连接 deepin-wine.i-m.dev (deepin-wine.i-m.dev)|104.198.14.52|:443... 已连接。
已发出 HTTP 请求，正在等待回应... 200 OK
长度： 1978 (1.9K) [application/x-shellscript]
正在保存至: “STDOUT”

-                   100%[===================>]   1.93K  --.-KB/s    用时 0s    

2021-11-12 09:25:30 (22.0 MB/s) - 已写入至标准输出 [1978/1978]

[sudo] zhang 的密码： 
命中:1 http://mirrors.aliyun.com/ubuntu focal InRelease
获取:2 http://mirrors.aliyun.com/ubuntu focal-security InRelease [114 kB]      
获取:3 http://mirrors.aliyun.com/ubuntu focal-updates InRelease [114 kB]       
命中:4 https://dl.google.com/linux/chrome/deb stable InRelease                 
获取:5 http://mirrors.aliyun.com/ubuntu focal-proposed InRelease [267 kB]      
获取:6 http://mirrors.aliyun.com/ubuntu focal-backports InRelease [101 kB]     
获取:7 https://packages.microsoft.com/repos/edge stable InRelease [7,342 B]    
获取:8 http://mirrors.aliyun.com/ubuntu focal-security/main Sources [185 kB]   
获取:9 http://mirrors.aliyun.com/ubuntu focal-security/main i386 Packages [306 kB]
获取:10 http://mirrors.aliyun.com/ubuntu focal-security/main amd64 Packages [987 kB]
命中:11 https://download.docker.com/linux/ubuntu focal InRelease              
错误:7 https://packages.microsoft.com/repos/edge stable InRelease
  由于没有公钥，无法验证下列签名： NO_PUBKEY EB3E94ADBE1229CF
获取:12 http://mirrors.aliyun.com/ubuntu focal-security/main amd64 DEP-11 Metadata [29.0 kB]
获取:13 http://mirrors.aliyun.com/ubuntu focal-security/main amd64 c-n-f Metadata [8,884 B]
获取:14 http://mirrors.aliyun.com/ubuntu focal-security/universe amd64 Packages [651 kB]
获取:15 http://mirrors.aliyun.com/ubuntu focal-security/universe i386 Packages [515 kB]
获取:16 http://mirrors.aliyun.com/ubuntu focal-security/universe amd64 DEP-11 Metadata [63.7 kB]
获取:17 http://mirrors.aliyun.com/ubuntu focal-security/universe amd64 c-n-f Metadata [12.9 kB]
获取:18 http://mirrors.aliyun.com/ubuntu focal-security/multiverse amd64 DEP-11 Metadata [2,464 B]
获取:19 http://mirrors.aliyun.com/ubuntu focal-updates/restricted Sources [29.0 kB]
获取:20 http://mirrors.aliyun.com/ubuntu focal-updates/main Sources [449 kB]
获取:21 http://mirrors.aliyun.com/ubuntu focal-updates/main i386 Packages [562 kB]
获取:22 http://mirrors.aliyun.com/ubuntu focal-updates/main amd64 Packages [1,344 kB]
获取:23 http://mirrors.aliyun.com/ubuntu focal-updates/main Translation-en [276 kB]
获取:24 http://mirrors.aliyun.com/ubuntu focal-updates/main amd64 DEP-11 Metadata [279 kB]
获取:25 http://mirrors.aliyun.com/ubuntu focal-updates/main amd64 c-n-f Metadata [14.5 kB]
获取:26 http://mirrors.aliyun.com/ubuntu focal-updates/universe amd64 Packages [875 kB]
获取:27 http://mirrors.aliyun.com/ubuntu focal-updates/universe i386 Packages [647 kB]
获取:28 http://mirrors.aliyun.com/ubuntu focal-updates/universe amd64 DEP-11 Metadata [356 kB]
获取:29 http://mirrors.aliyun.com/ubuntu focal-updates/universe amd64 c-n-f Metadata [19.5 kB]
获取:30 http://mirrors.aliyun.com/ubuntu focal-updates/multiverse amd64 DEP-11 Metadata [940 B]
获取:31 http://mirrors.aliyun.com/ubuntu focal-proposed/restricted Sources [20.0 kB]
获取:32 http://mirrors.aliyun.com/ubuntu focal-proposed/main Sources [58.7 kB]
获取:33 http://mirrors.aliyun.com/ubuntu focal-proposed/main amd64 Packages [170 kB]
获取:34 http://mirrors.aliyun.com/ubuntu focal-proposed/main i386 Packages [50.7 kB]
获取:35 http://mirrors.aliyun.com/ubuntu focal-proposed/main Translation-en [37.1 kB]
获取:36 http://mirrors.aliyun.com/ubuntu focal-proposed/main amd64 DEP-11 Metadata [3,884 B]
获取:37 http://mirrors.aliyun.com/ubuntu focal-proposed/main amd64 c-n-f Metadata [1,660 B]
获取:38 http://mirrors.aliyun.com/ubuntu focal-proposed/restricted amd64 Packages [171 kB]
获取:39 http://mirrors.aliyun.com/ubuntu focal-proposed/restricted Translation-en [24.0 kB]
获取:40 http://mirrors.aliyun.com/ubuntu focal-proposed/universe amd64 DEP-11 Metadata [8,832 B]
获取:41 http://mirrors.aliyun.com/ubuntu focal-backports/universe amd64 DEP-11 Metadata [10.4 kB]
正在读取软件包列表... 完成                                            
W: GPG 错误：https://packages.microsoft.com/repos/edge stable InRelease: 由于没有公钥，无法验证下列签名： NO_PUBKEY EB3E94ADBE1229CF
E: 仓库 “https://packages.microsoft.com/repos/edge stable InRelease” 没有数字签名。
N: 无法安全地用该源进行更新，所以默认禁用该源。
N: 参见 apt-secure(8) 手册以了解仓库创建和用户配置方面的细节。
zhang@zhang-Lenovo-XiaoXin-RUI7000:~$ sudo apt-get install com.qq.weixin.deepin
正在读取软件包列表... 完成
正在分析软件包的依赖关系树       
正在读取状态信息... 完成       
E: 无法定位软件包 com.qq.weixin.deepin
E: 无法按照 glob ‘com.qq.weixin.deepin’ 找到任何软件包
E: 无法按照正则表达式 com.qq.weixin.deepin 找到任何软件包
`

**Comment by erge6521** [comment]
微软edge没公钥的源会影响本项目源的生成，解决办法：`cd /etc/apt/sources.list.d`
`sudo rm microsoft-edge-beta.list`
`sudo rm microsoft-edge-beta.list.save`

**Comment by wang-xiaowu** [comment]
记录一下：
```
你遇到的错误信息是关于 Microsoft 的软件仓库签名验证失败。具体错误是：
错误:4 https://packages.microsoft.com/repos/code stable InRelease
  由于没有公钥，无法验证下列签名： NO_PUBKEY EB3E94ADBE1229CF
这表明你的系统无法验证 https://packages.microsoft.com/repos/code 仓库中的软件包，因为缺少对应的公钥。
解决方法：
要解决这个问题，你需要手动导入缺失的公钥。以下是步骤：
步骤 1: 导入 Microsoft 的 GPG 公钥
下载并添加 Microsoft 的公钥：
使用以下命令导入公钥：
curl https://packages.microsoft.com/keys/microsoft.asc | sudo gpg --dearmor -o /usr/share/keyrings/microsoft-archive-keyring.gpg
这将从 https://packages.microsoft.com/keys/microsoft.asc 下载 GPG 公钥，并将其保存到 /usr/share/keyrings/microsoft-archive-keyring.gpg。
步骤 2: 更新 apt 源配置
更新你的 APT 源配置文件，确保 apt 使用正确的密钥文件。编辑 Microsoft 的仓库源配置文件：
sudo vim /etc/apt/sources.list.d/vscode.list
如果你看到类似这样的行：
deb [arch=amd64] https://packages.microsoft.com/repos/code stable main
你需要将其修改为：
deb [arch=amd64 signed-by=/usr/share/keyrings/microsoft-archive-keyring.gpg] https://packages.microsoft.com/repos/code stable main
这将告诉 apt 使用你刚才导入的 GPG 密钥进行签名验证。
步骤 3: 更新软件源
更新 APT 索引：
sudo apt update
```
