### ISSUE TITLE
求一个文件 /usr/lib/i386-linux-gnu/deepin-wine5/shell32.dll.so 发到我的邮箱 谢谢

### ISSUE THREAD

**Issue by yiyayamaya** [zq1997/deepin-wine#238]
手贱给覆盖了不会重装 求好心老哥发我一份这个文件

版本应该是这个

deepin-wine5-i386/未知,未知,now 5.0.16-1 i386 [已安装，自动]
deepin-wine5/未知,未知,now 5.0.16-1 i386 [已安装，自动]

**Comment by duzhaokun123** [comment]
其实去可以`apt reinstall`
