### ISSUE TITLE
更新到3.4.0.38deepin6后，输入框点击表情和截图均导致闪退

### ISSUE THREAD

**Issue by BossKen1995** [zq1997/deepin-wine#265]
如题，上版本3.4.0.38deepin4同样存在该问题，求助~

**Comment by BossKen1995** [comment]
系统ubuntu 20.04

**Comment by Tonny24Wang** [comment]
ubuntu22 deepin6 同样的问题，另外点击收到的文件直接转到浏览器而不是直接打开，但是接收文件正常，可以再对应目录下找到文件。

**Comment by WeihongPan** [comment]
同！

**Comment by BossKen1995** [comment]
最新版本3.4.0.38deepin16该问题已解决，感谢作者！
