### ISSUE TITLE
命令启动wechat

### ISSUE THREAD

**Issue by YerongLi2** [zq1997/deepin-wine#272]
什么系统，什么桌面，什么版本
Antix 21 Debian 11-update/bookworm, 桌面icewm
com.qq.weixin.deepin安装正常.

但是安装完成后`/usr/share/applications/`里没有 .desktop图标, 请问有办法**命令行**启动吗?

	$ echo $XDG_CURRENT_DESKTOP
	lsb_release -a
	grep -rn '^\s*deb ' --include '*.list' /etc/apt/
	icewm
	No LSB modules are available.
	Distributor ID:	Debian
	Description:	Debian GNU/Linux bookworm/sid
	Release:	11-updates
	Codename:	n/a
	/etc/apt/sources.list.d/google-chrome.list:3:deb [arch=amd64] https://dl.google.com/linux/chrome/deb/ stable main
	/etc/apt/sources.list.d/slack.list:3:deb https://packagecloud.io/slacktechnologies/slack/debian/ jessie main
	/etc/apt/sources.list.d/debian.list:2:deb http://ftp.us.debian.org/debian/ bullseye main contrib non-free
	/etc/apt/sources.list.d/debian.list:3:deb http://security.debian.org/ bullseye-security main contrib non-free
	/etc/apt/sources.list.d/debian.list:22:deb http://deb.debian.org/debian/ testing main contrib non-free
	/etc/apt/sources.list.d/debian.list:23:deb http://deb.debian.org/debian/ testing-updates main contrib non-free
	/etc/apt/sources.list.d/debian.list:24:deb http://deb.debian.org/debian-security testing-security main
	/etc/apt/sources.list.d/debian-stable-updates.list:2:deb http://ftp.us.debian.org/debian/ bullseye-updates main contrib non-free
	/etc/apt/sources.list.d/vscode.list:3:deb [arch=amd64,arm64,armhf] http://packages.microsoft.com/repos/code stable main
	/etc/apt/sources.list.d/deepin-wine.i-m.dev.list:1:deb [trusted=yes] https://deepin-wine.i-m.dev /
	/etc/apt/sources.list.d/bullseye-backports.list:2:deb http://deb.debian.org/debian bullseye-backports main contrib non-free
	/etc/apt/sources.list.d/antix.list:2:deb http://mirrors.rit.edu/mxlinux/mx-packages/antix/bullseye bullseye main nosystemd nonfree

**Comment by YerongLi** [comment]
I found the following command will run the wechat through command line.

`sudo /opt/apps/com.qq.weixin.deepin/files/run.sh`

**Comment by YerongLi2** [comment]
Issue resolved.

**Comment by thomas-art** [comment]
[微信.desktop.zip](https://github.com/zq1997/deepin-wine/files/8638689/desktop.zip)
遇到同样问题的可以下载这个.desktop文件放到/usr/share/applications/  文件夹里

**Comment by zxkmm** [comment]
> 

I don't think run as root is a good idea.

**Comment by imjiaoyuan** [comment]
@thomas-art 方法有效！请问有企业微信的吗？我安装的wine应用都没有图标

**Comment by imjiaoyuan** [comment]
@thomas-art 已解决！自己写desktop文件即可！
