### ISSUE TITLE
BUG(输入框)：ubuntu 21.10 微信版本 3.6.018 输入框问题

### ISSUE THREAD

**Issue by nuty** [zq1997/deepin-wine#278]
系统：Ubuntu 21.10
微信版本： 3.6.018
输入法：IBUS 智能拼音
问题描述：在微信界面上任何一个输入框输入文字，汉语和英语都无法显示在输入框中。但是点击发送可以正常发消息。

**Comment by liaozihang** [comment]
我是企业微信不能用，输入文字无显示，但实际内容可以发送出去。

**Comment by nuty** [comment]
@liaozihang 测试可以解决文字输入的问题。感谢分享解决方案。
