### ISSUE TITLE
文档中请更改“QQ头像无法加载的问题”这一项的内容

### ISSUE THREAD

**Issue by whtrys** [zq1997/deepin-wine#286]
已经查明问题所在，是因为ipv6，只要**将ipv6停用**即可
使用如下代码：
`sudo gedit /etc/sysctl.conf`
打开文件后在最后加入
`net.ipv6.conf.all.disable_ipv6 =1`
`net.ipv6.conf.default.disable_ipv6 =1`
`net.ipv6.conf.lo.disable_ipv6 =1`
然后重载系统参数
`sudo sysctl -p`
即可

**Comment by zq1997** [comment]
已修改

**Comment by chenxiex** [comment]
这个解决方案并不好，现在很多网站、应用都已经升级ipv6，部分应用（例如xdroid）甚至必须开启ipv6才能正常联网。
相比之下星火商店里面推荐的设置privoxy代理的办法对其它应用影响还小一些。
