### ISSUE TITLE
ubuntu22.04安装应用时出现问题

### ISSUE THREAD

**Issue by xcfxr** [zq1997/deepin-wine#288]
已经成功安装了微信，但是安装其他应用时均报错。
(base) xucee@xucee:~/桌面$ sudo apt-get install com.qq.music.deepin
正在读取软件包列表... 完成
正在分析软件包的依赖关系树... 完成
正在读取状态信息... 完成                 
E: 无法定位软件包 com.qq.music.deepin
E: 无法按照 glob ‘com.qq.music.deepin’ 找到任何软件包
E: 无法按照正则表达式 com.qq.music.deepin 找到任何软件包

**Comment by zq1997** [comment]
只有https://deepin-wine.i-m.dev/ 列出的应用才有，其他的可能被官方撤包了
