### ISSUE TITLE
Ubuntu 20.04使用截图功能时黑屏

### ISSUE THREAD

**Issue by DanielYang59** [zq1997/deepin-wine#292]
各位好，我使用的是Ubuntu 20.04 LTS，电脑为X1 Carbon Gen 6（CPU为i7-8550U，无独显），使用“_com.qq.weixin.deepin/unknown,now 3.4.0.38deepin16_”版本的微信时点击截图（不论是否开启“截图时隐藏当前窗口”）整个屏幕都会完全黑屏（如下图所示），使用“_deepin.com.qq.office_2.0.0deepin4_i386_”时没有问题。  
此外，```echo $XDG_SESSION_TYPE```命令返回：```x11```。
![Screenshot from 2022-06-19 11-00-40](https://user-images.githubusercontent.com/80093591/174461708-d43e755b-779e-408e-9085-23c986db427e.png)

**Comment by lori-zhao** [comment]
同样的问题，Flamesshot安装还存在依赖问题，解决之后使用也出现使用问题，不是启动不起来

**Comment by lori-zhao** [comment]
https://github.com/zq1997/deepin-wine/issues/250#issuecomment-1018094695
回退了，目前截图问题正常

**Comment by DanielYang59** [comment]
Closed as not getting response.
