### ISSUE TITLE
com.coursemaker.deepin和com.dalongcloudpc.deepin软件包在https://deepin-wine.i-m.dev/上出现了两次

### ISSUE THREAD

**Issue by xiaopangju** [zq1997/deepin-wine#293]
如题，在https://deepin-wine.i-m.dev这个网站上，com.coursemaker.deepin这个包出现了两次，且版本号、简介等完全相同。建议删去多余的。（com.dalongcloudpc.deepin这个包似乎也出现了两次）
# 截图
![图片](https://user-images.githubusercontent.com/56964531/176140348-2ce302dc-8016-4fbf-8877-151ecb86cce3.png)

**Comment by zq1997** [comment]
之前记得有些包在上游源里出现过两次，懒得处理了
