### ISSUE TITLE
sudo apt-get update报错，应该怎么解决呢？使用的是ubuntu20.04

### ISSUE THREAD

**Issue by brcarry** [zq1997/deepin-wine#298]
命中:1 http://mirrors.ustc.edu.cn/ubuntu focal InRelease
命中:2 http://mirrors.ustc.edu.cn/ubuntu focal-updates InRelease                                   
忽略:3 http://mirrors.tuna.tsinghua.edu.cn/ros/ubuntu focal InRelease                              
命中:4 http://mirrors.ustc.edu.cn/ubuntu focal-backports InRelease                                 
命中:5 http://mirrors.ustc.edu.cn/ubuntu focal-security InRelease                                  
命中:6 http://mirrors.tuna.tsinghua.edu.cn/ros/ubuntu focal Release                                
命中:7 https://dl.google.com/linux/chrome/deb stable InRelease                                     
命中:9 http://packages.microsoft.com/repos/code stable InRelease                               
忽略:10 https://deepin-wine.i-m.dev  InRelease                            
忽略:11 https://deepin-wine.i-m.dev  Release         
忽略:12 https://deepin-wine.i-m.dev  Packages
忽略:13 https://deepin-wine.i-m.dev  Translation-zh_CN
忽略:14 https://deepin-wine.i-m.dev  Translation-zh
忽略:15 https://deepin-wine.i-m.dev  Translation-en
忽略:12 https://deepin-wine.i-m.dev  Packages         
忽略:13 https://deepin-wine.i-m.dev  Translation-zh_CN
忽略:14 https://deepin-wine.i-m.dev  Translation-zh   
忽略:15 https://deepin-wine.i-m.dev  Translation-en   
忽略:12 https://deepin-wine.i-m.dev  Packages         
忽略:13 https://deepin-wine.i-m.dev  Translation-zh_CN
忽略:14 https://deepin-wine.i-m.dev  Translation-zh   
忽略:15 https://deepin-wine.i-m.dev  Translation-en   
忽略:12 https://deepin-wine.i-m.dev  Packages
忽略:13 https://deepin-wine.i-m.dev  Translation-zh_CN
忽略:14 https://deepin-wine.i-m.dev  Translation-zh   
忽略:15 https://deepin-wine.i-m.dev  Translation-en   
忽略:12 https://deepin-wine.i-m.dev  Packages         
忽略:13 https://deepin-wine.i-m.dev  Translation-zh_CN
忽略:14 https://deepin-wine.i-m.dev  Translation-zh   
忽略:15 https://deepin-wine.i-m.dev  Translation-en   
忽略:12 https://deepin-wine.i-m.dev  Packages         
忽略:13 https://deepin-wine.i-m.dev  Translation-zh_CN
忽略:14 https://deepin-wine.i-m.dev  Translation-zh   
忽略:15 https://deepin-wine.i-m.dev  Translation-en   
错误:12 https://deepin-wine.i-m.dev  Packages         
  Certificate verification failed: The certificate is NOT trusted. The certificate chain uses expired certificate.  Could not handshake: Error in the certificate verification. [IP: 104.198.14.52 443]
忽略:13 https://deepin-wine.i-m.dev  Translation-zh_CN
忽略:14 https://deepin-wine.i-m.dev  Translation-zh   
忽略:15 https://deepin-wine.i-m.dev  Translation-en   
正在读取软件包列表... 完成                            
E: 无法下载 https://deepin-wine.i-m.dev/Packages  Certificate verification failed: The certificate is NOT trusted. The certificate chain uses expired certificate.  Could not handshake: Error in the certificate verification. [IP: 104.198.14.52 443]
E: 部分索引文件下载失败。如果忽略它们，那将转而使用旧的索引文件。

**Comment by zq1997** [comment]
旧的issue记得有提过这个问题

**Comment by GreenTeodoro839** [comment]
更新系统根证书

**Comment by OrangeSodahub** [comment]
不能自己查查吗

**Comment by brcarry** [comment]
> 更新系统根证书

谢谢您！已解决
