### ISSUE TITLE
执行开始脚本，报证书过期

### ISSUE THREAD

**Issue by a747097587** [zq1997/deepin-wine#299]
与issue https://github.com/zq1997/deepin-wine/issues/222 类似
执行 wget -O- https://deepin-wine.i-m.dev/setup.sh | sh 的时候，发生如下报错：
![image](https://user-images.githubusercontent.com/28568597/184313496-32988ffd-a9ac-45ab-bf55-071b2d8c0229.png)

sudo apt install ca-certificates --reinstall  之后也没用
![image](https://user-images.githubusercontent.com/28568597/184313622-9b1b3d1f-f95e-4376-9ad4-fe16e80e7e82.png)
仓库地址是正确的
![image](https://user-images.githubusercontent.com/28568597/184314005-055d7296-06f1-4636-8ee9-0052491a5ae4.png)
本地浏览器可以打开
![image](https://user-images.githubusercontent.com/28568597/184314206-8e327cef-b8cb-44e8-88b2-4f347a43a13c.png)

**Comment by zq1997** [comment]
wget百度主页试试，按理浏览器打得开wget也行
