### ISSUE TITLE
非常Nice！

### ISSUE THREAD

**Issue by ysy950803** [zq1997/deepin-wine#3]
环境：Ubuntu 16.04
试了下最新的微信，很稳定。使用方式也比以前的移植方便多了。

**Comment by zq1997** [comment]
![image](https://user-images.githubusercontent.com/17429111/64579056-1320c700-d3b4-11e9-84dc-dfdec99b2568.png)
很高兴可以帮到你

**Comment by luosainan96** [comment]
我刚刚在ubuntu上按照你的教程成功安装了最新版的wechat(2.6.8.65deepin0)，但是启动的时候还是告诉我微信版本过低需要升级到最新版，这是怎么回事呢

**Comment by zq1997** [comment]
```
rm -rf ~/.deepinwine/Deepin-WeChat/ ~/Documents/WeChat\ Files
```
移除旧的容器与配置试试

**Comment by luosainan96** [comment]
我没有这个路径。把之前的旧容器完全卸载后，再按照你的进行安装，微信还是这个问题。QQ什么的都是好的。

**Comment by zq1997** [comment]
奇怪，确定装了新版？dist-upgrade一下

**Comment by luosainan96** [comment]
DIST是什么

**Comment by zq1997** [comment]
`sudo apt dist-upgrade && dpkg -l deepin.com.wechat`

**Comment by luosainan96** [comment]
仍旧没有解决

**Comment by ysy950803** [comment]
@luosainan96 我记得微信旧版本还是可以用的吧，如果不行可以试试以前的办法：https://github.com/wszqkzqk/deepin-wine-ubuntu
重装一下deepin-wine环境，然后再用 @zq1997 的这个项目升级到最新，我目前反正是这么操作的。

**Comment by luosainan96** [comment]
好了好了好了，谢谢你！！！是.deepinwine/Deepin-WeChat/没有删掉的原因。

**Comment by luosainan96** [comment]
rm -rf ~/.deepinwine/Deepin-WeChat/ ~/Documents/WeChat\ Files
