### ISSUE TITLE
本人完成了在debian的wine7上安装完整或精简的VB6,想和你合作做一个一键安装。

### ISSUE THREAD

**Issue by ghost** [zq1997/deepin-wine#300]
如题

**Comment by zq1997** [comment]
deepin-wine其实是deepin官方魔改过的wine，和原生的wine 7可以说是有很大区别了。我个人的建议是如果希望发布和安装简单，可以也自制一个源，我是通过netlify部署我的安装脚本和仓库资源的，成本为0。只要学习一下debian仓库的结构，就可以自制了。
UNIX 设计哲学：Do one thing and do it well
所以我并不太倾向在这个仓库里加入wine VB6环境的支持
