### ISSUE TITLE
N: Updating from such a repository can't be done securely, and is therefore disabled by default.

### ISSUE THREAD

**Issue by ghost** [zq1997/deepin-wine#302]
Resolving deepin-wine.i-m.dev (deepin-wine.i-m.dev)... 104.198.14.52
Connecting to deepin-wine.i-m.dev (deepin-wine.i-m.dev)|104.198.14.52|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 1978 (1.9K) [application/x-shellscript]
Saving to: ‘STDOUT’

-                   100%[===================>]   1.93K  --.-KB/s    in 0s      

2022-09-20 10:48:15 (28.0 MB/s) - written to stdout [1978/1978]

Hit:1 https://mirrors.ustc.edu.cn/ubuntu jammy InRelease
Hit:2 https://mirrors.ustc.edu.cn/ubuntu jammy-updates InRelease
Hit:3 https://mirrors.ustc.edu.cn/ubuntu jammy-backports InRelease
Hit:4 https://mirrors.ustc.edu.cn/ubuntu jammy-security InRelease
Ign:5 http://packages.ros.org/ros/ubuntu jammy InRelease
Hit:6 http://packages.ros.org/ros2/ubuntu jammy InRelease
Err:7 http://packages.ros.org/ros/ubuntu jammy Release
  404  Not Found [IP: 64.50.236.52 80]
Reading package lists... Done
E: The repository 'http://packages.ros.org/ros/ubuntu jammy Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.

**Comment by zq1997** [comment]
报错和本仓库无关，是系统固有源的问题
