### ISSUE TITLE
微信在 ubuntu 20.04上非常稳定，期望更新到3.7版本

### ISSUE THREAD

**Issue by shelmesky** [zq1997/deepin-wine#308]
微信在 ubuntu 20.04 上非常稳定，可以长期使用，期望微信能更新到3.7版本。

**Comment by zq1997** [comment]
没办法，deepin现在的源不知道有一个什么特别神奇的重定向机制
- 我们只能下载 https://com-store-packages.uniontech.com/appstore/... 里的元信息
- 而在deepin系统上，这个链接不知通过什么操作会自动重定向到形如 https://home-store-img.uniontech.com/221124140501770/appstore/... 这样的地址去
 
后者看起来是一个及时构建的源镜像，而且地址应该随时会变，且目前不知道如何获取最新地址。只能用前者里面的旧包。

最近几年deepin的源改动了好几次，不清楚是为了反爬虫还是出于功能架构升级需求，这次是真的把我整不会了。

**Comment by zq1997** [comment]
已更新，但是注意参考 #310 解决启动问题
