### ISSUE TITLE
ubuntu 22.04.1 更新后，企业微信不能用了

### ISSUE THREAD

**Issue by littleboss** [zq1997/deepin-wine#314]
更新到版本com.qq.weixin.work.deepin 到4.0.16.6007deepin18，不能启动了，是对libldap有依赖么？

**Comment by EFCHolla** [comment]
https://github.com/zq1997/deepin-wine/issues/310#issuecomment-1328003693

**Comment by EFCHolla** [comment]
手动安装那两个依赖就可以了

**Comment by littleboss** [comment]
> 

apt 已经安装了，也注释了export WINEPREDLL="$ARCHIVE_FILE_DIR/dlls"，还是起不来，是昨天更新后的版本

**Comment by xiaoquanWu** [comment]
系统升级了一下，我也启动不了，@littleboss 你解决了吗

**Comment by crazyn2** [comment]
希望能提供个docker容器，这样就能避免升级问题

**Comment by crazyn2** [comment]
也可以提供个Docker容器运行linux版的腾讯会议

**Comment by zzhgh** [comment]
> 

腾讯会议已经有Linux版本的了，https://meeting.tencent.com/download/

**Comment by crazyn2** [comment]
依赖问题还是有，最好能提供个Docker容器运行

**Comment by zolo2013** [comment]
我的ubuntu 20.04上虽然可以安装，但run.sh报错的是 com.deepin.dde.TrayManager在dbus上无法找到服务，应该是deepin-win额的 TrayManager service 没有启动。4.0.16.6007deepin18 或者 4.0.16.6007deepin13 旧版本之前是可以运行的。哪里可以下载旧的版本呢？谢谢。

**Comment by lihz1990** [comment]
通过下载安装老版本，然后注释 `/opt/apps/com.qq.weixin.work.deepin/files/run.sh` 中的 `export WINEPREDLL="$ARCHIVE_FILE_DIR/dlls"` 一行，重启企业微信成功。

老版本地址： https://com-store-packages.uniontech.com/appstore/pool/appstore/c/com.qq.weixin.work.deepin/com.qq.weixin.work.deepin_4.0.0.6007deepin10_i386.deb

**Comment by littleboss** [comment]
> 系统升级了一下，我也启动不了，@littleboss 你解决了吗

我还没有解决 @xiaoquanWu

**Comment by littleboss** [comment]
> 通过下载安装老版本，然后注释 `/opt/apps/com.qq.weixin.work.deepin/files/run.sh` 中的 `export WINEPREDLL="$ARCHIVE_FILE_DIR/dlls"` 一行，重启企业微信成功。
> 
> 老版本地址： https://com-store-packages.uniontech.com/appstore/pool/appstore/c/com.qq.weixin.work.deepin/com.qq.weixin.work.deepin_4.0.0.6007deepin10_i386.deb

@lihz1990 谢谢，这个可行，先回归老版本了

**Comment by tommyjiang** [comment]
> 通过下载安装老版本，然后注释 `/opt/apps/com.qq.weixin.work.deepin/files/run.sh` 中的 `export WINEPREDLL="$ARCHIVE_FILE_DIR/dlls"` 一行，重启企业微信成功。
> 
> 老版本地址： https://com-store-packages.uniontech.com/appstore/pool/appstore/c/com.qq.weixin.work.deepin/com.qq.weixin.work.deepin_4.0.0.6007deepin10_i386.deb

感谢分享，先用着老版本等 fix。

**Comment by littleboss** [comment]
the latest version is ok

**Comment by tommyjiang** [comment]
最新版可以了，感谢。
