### ISSUE TITLE
ubuntu20.04-22.04 最新的环境包为deepin-wine6-stable=6.0.0.42-1以后企业微信无法打开，上一个版本6.0.0.41-1是可以正常打开

### ISSUE THREAD

**Issue by github68616208** [zq1997/deepin-wine#317]
ubuntu20.04-22.04 最新的环境包为deepin-wine6-stable=6.0.0.42-1以后企业微信无法打开，上一个版本6.0.0.41-1是可以正常打开

**Comment by github68616208** [comment]
taif -f /var/log/syslog查看系统log，点击图标后 最后wine的log 显示wine version：6.0
ubuntu desktop 20.04和ubuntu desktop 22.04均测试过，#310参数在之前版本是管用，deepin-wine6-stable:6.0.0.42-1以后不管用了

**Comment by github68616208** [comment]
微信是正常可以使用的，只是企业微信不可用

**Comment by ChangGL** [comment]
遇到了同样的问题，请问是否已解决

**Comment by github68616208** [comment]
目前还是不行，只是临时用着优麒麟的wine

**Comment by github68616208** [comment]
最近的更新中，此问题不存了，可以关闭问题了
