### ISSUE TITLE
怎么安装最新的企业微信

### ISSUE THREAD

**Issue by DWendou** [zq1997/deepin-wine#335]
有没有最新的企业微信的包，求分享一个！

**Comment by DWendou** [comment]
直接在设置里更新就好了

**Comment by oi520** [comment]
> 直接在设置里更新就好了

兄弟，你把新版deeping发邮件给我吗哈哈，我这里找别人的号等上去也进不了升级页面，我是真的很无语。

**Comment by oi520** [comment]
> 直接在设置里更新就好了

我也可以了，哈哈，感谢；方法就是用别人的账号升级我自己的软件，但是企业微信当前版本得是4.0.0版本的才能在Ubuntu20.04上运行的相对稳定，然后再点击升级。
