### ISSUE TITLE
How to install netease-cloud-music

### ISSUE THREAD

**Issue by BobDLA** [zq1997/deepin-wine#343]
Thanks for the greate project. I have insalled the wechat by this project and works great.
And I try to install the nease-could-music which should support by [deepin](https://wiki.deepin.org/zh/01_%E8%BD%AF%E4%BB%B6wiki/00_GUI%E8%BD%AF%E4%BB%B6/03_%E7%AC%AC%E4%B8%89%E6%96%B9%E5%BC%80%E5%8F%91%E7%9A%84%E8%BD%AF%E4%BB%B6/02_%E5%BD%B1%E9%9F%B3%E5%A8%B1%E4%B9%90%E7%9B%B8%E5%85%B3/%E7%BD%91%E6%98%93%E4%BA%91%E9%9F%B3%E4%B9%90) also.

But, seems it's not in this project support list.
Could you please suggest how to make it work?

Thank you.

**Comment by sq6er4** [comment]
You can install YesPlayMusic instead of netease-cloud-music

**Comment by BobDLA** [comment]
> You can install YesPlayMusic instead of netease-cloud-music

THanks, yespplaymusic is a great choice.
