### ISSUE TITLE
Ubuntu 20.04 更新系统后，微信的图片另存为，选择文件全部闪退

### ISSUE THREAD

**Issue by sk142857** [zq1997/deepin-wine#344]
一开始用的没有任何问题。但是，做了系统更新之后，微信的文件选择器以及文件另存为等，全部闪退。

`80~20.04.1-Ubuntu SMP Wed May 17 14:58:14 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux`

**Comment by pay46** [comment]
我也是同样问题，现在只能用终端find后移动，非常麻烦

**Comment by hongyi-zhao** [comment]
@pay46 
> 我也是同样问题，

同样问题。系统信息：

```
werner@X10DAi:~$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 22.10
Release:	22.10
Codename:	kinetic
```
> 现在只能用终端find后移动，非常麻烦

那倒没有必要，可以在类似如下位置寻找相应自动接受的文件：

```
werner@X10DAi:~/Desktop$ realpath File 
/home/werner/Documents/WeChat Files/wxid_1e2zv59busz621/FileStorage/MsgAttach/33ee697a31fb5898306f4f6378b540ce/File
```

**Comment by imyhxy** [comment]
同样问题，现在无法发送文件或者图片

**Comment by pay46** [comment]
> @pay46
> 
> > 我也是同样问题，
> 
> 同样问题。系统信息：
> 
> ```
> werner@X10DAi:~$ lsb_release -a
> No LSB modules are available.
> Distributor ID:	Ubuntu
> Description:	Ubuntu 22.10
> Release:	22.10
> Codename:	kinetic
> ```
> 
> > 现在只能用终端find后移动，非常麻烦
> 
> 那倒没有必要，可以在类似如下位置寻找相应自动接受的文件：
> 
> ```
> werner@X10DAi:~/Desktop$ realpath File 
> /home/werner/Documents/WeChat Files/wxid_1e2zv59busz621/FileStorage/MsgAttach/33ee697a31fb5898306f4f6378b540ce/File
> ```
@hongyi-zhao 
谢谢分享。还有些情况，就是对方发图片，图片接受并显示在对话框，这种情况没有文件名，咋办？

**Comment by hongyi-zhao** [comment]
> @hongyi-zhao
> 谢谢分享。还有些情况，就是对方发图片，图片接受并显示在对话框，这种情况没有文件名，咋办？

我也不清楚。我说的并不是解决方案，而是权宜之计。

**Comment by imyhxy** [comment]
现在通过星火商店安装了微信，用着没有问题

**Comment by tianxingyzxq** [comment]
同样问题

**Comment by hongyi-zhao** [comment]
> 现在通过星火商店安装了微信，用着没有问题

打不开下面的页面：

https://spark-app.store/store/sort/chat

![image](https://github.com/zq1997/deepin-wine/assets/11155854/0b98a8ba-f640-41f6-a87a-59abcfedc624)

**Comment by chubbyk-uu** [comment]
同样的问题，而且也没法截图，截图画面全黑

**Comment by DDDDBoom** [comment]
同上，等一个解决办法

**Comment by Mistress-of-the-Blade** [comment]
同上，文件另存为无反应

**Comment by hongyi-zhao** [comment]
已经没有采用这种方法的必要了。最新版本的wine完美兼容所有这些程序的最新版本了。

参考下图：

![image](https://github.com/zq1997/deepin-wine/assets/11155854/7fdff1e9-8025-4c02-b72c-ee9fcb22b3ba)

See [here](https://appdb.winehq.org/objectManager.php?sClass=application&iId=16931) for more details.

**Comment by iefengjian** [comment]
更新了下微信，文件另存和文件传输点不开了

**Comment by iefengjian** [comment]
> 已经没有采用这种方法的必要了。最新版本的wine完美兼容所有这些程序的最新版本了。
> 
> 参考下图：
> 
> ![image](https://user-images.githubusercontent.com/11155854/255072002-7fdff1e9-8025-4c02-b72c-ee9fcb22b3ba.png)
> 
> See [here](https://appdb.winehq.org/objectManager.php?sClass=application&iId=16931) for more details.

wine微信试了一下，还有挺多问题，隔一段时间会崩溃掉，不知道你有这个问题没，另外我的截图不了

**Comment by hongyi-zhao** [comment]
几点说明：
1. 分别尝试如下的wine最新版本，找出问题最少的：

```
$ sudo apt install --install-recommends winehq-stable
$ sudo apt install --install-recommends winehq-devel
$ sudo apt install --install-recommends winehq-staging 
```
2. 我目前的问题是：输入区域不显示光标。
3. 截图似乎也不是功能完全正常。换用其他工具即可。

**Comment by toddlerya** [comment]
> 已经没有采用这种方法的必要了。最新版本的wine完美兼容所有这些程序的最新版本了。
> 
> 参考下图：
> 
> ![image](https://user-images.githubusercontent.com/11155854/255072002-7fdff1e9-8025-4c02-b72c-ee9fcb22b3ba.png)
> 
> See [here](https://appdb.winehq.org/objectManager.php?sClass=application&iId=16931) for more details.

试了下，可以。
相关资料如下：
1. 安装wine最新版： 
    - https://wiki.winehq.org/Ubuntu_zhcn
    - https://linux.cn/article-16028-1.html
3. 下载WeChatSetup-3.8.0.41.exe：https://github.com/tom-snow/wechat-windows-versions/releases

**Comment by byteroll** [comment]
这个问题有解吗？

**Comment by hongyi-zhao** [comment]
> 这个问题有解吗？

什么意思？上面已经说了可以用，但并不完美。

**Comment by liudatutu** [comment]
同样问题，文件和图片等不能另存为，是否有解决方案

**Comment by iefengjian** [comment]
最近有空找了些方法，并不算完全解决，可以选择 "在文件中打开" 再自己复制移动吧
“在文件中打开“可以用以下方法恢复：
新建文件，并添加可执行权限：/usr/bin/dde-file-manager

```
#!/bin/bash
echo "$@" >/tmp/fake-dde-call.log
dbus-send --print-reply --dest=org.freedesktop.FileManager1 \
        /org/freedesktop/FileManager1 \
        org.freedesktop.FileManager1.ShowItems \
        array:string:"file://${2}" \
        string:fake-dde-show-items &&  \
        exit 0
dolphin --select "$2" && exit 0
xdg-open $(dirname "$2")
```

**Comment by hongyi-zhao** [comment]
我觉得，基于deepin的方法终究是不好的，局限性和不可预料性太大。从长远来看，还是基于原生wine+wechat的方法最具有可移植性。

**Comment by hongyi-zhao** [comment]
> https://github.com/zq1997/deepin-wine/issues/344#issuecomment-1666803254
> * 我目前的问题是：输入区域不显示光标。
> 
> * 截图似乎也不是功能完全正常。换用其他工具即可。

经测试，安装[32位版本](https://dldir1v6.qq.com/weixin/Windows/WeChatSetup_x86.exe)则没有上述问题。

**Comment by sumic** [comment]
更换老的deepin-wine6版本问题解决，基本确认是wine版本问题

**Comment by imyhxy** [comment]
@sumic 在哪里下载老版本，是哪一个版本没问题

**Comment by sumic** [comment]
> @sumic 在哪里下载老版本，是哪一个版本没问题

我是还有一台老电脑上装的，我直接复制过来了。
貌似Version: 6.0.0.31

**Comment by sumic** [comment]
> @sumic 在哪里下载老版本，是哪一个版本没问题

https://github.com/sumic/deepin-wine6/tree/main
我传了一个，自己覆盖

**Comment by zq1997** [comment]
现在deepin放出了基于deepin-wine8的amd64微信，
卸载i386版本并安装amd64版本，如下
`sudo apt install com.qq.weixin.deepin`
文件功能就可以使用了

**Comment by imyhxy** [comment]
我用最近几个版本一直有问题：
1. 有透明框
2. 公众号打不开

**Comment by toddlerya** [comment]
> 我用最近几个版本一直有问题：
> 
> 1. 有透明框
> 2. 公众号打不开

+1，我也有这个问题

操作系统环境
```shell
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 22.04.2 LTS
Release:	22.04
Codename:	jammy
```

桌面为Xfce

安装信息
```shell
$ sudo apt install com.qq.weixin.deepin
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
The following package was automatically installed and is no longer required:
  libdouble-conversion1
Use 'sudo apt autoremove' to remove it.
The following additional packages will be installed:
  deepin-wine-helper deepin-wine8-stable fonts-wqy-microhei libnss-myhostname
The following packages will be REMOVED:
  com.qq.weixin.deepin:i386
The following NEW packages will be installed:
  com.qq.weixin.deepin deepin-wine8-stable fonts-wqy-microhei libnss-myhostname
The following packages will be upgraded:
  deepin-wine-helper
1 upgraded, 4 newly installed, 1 to remove and 139 not upgraded.
Need to get 556 MB of archives.
After this operation, 1,442 MB of additional disk space will be used.
Do you want to continue? [Y/n] Y
Get:1 http://mirrors.aliyun.com/ubuntu jammy/universe amd64 fonts-wqy-microhei all 0.2.0-beta-3.1 [1,607 kB]
Get:2 http://mirrors.aliyun.com/ubuntu jammy-proposed/universe amd64 libnss-myhostname amd64 249.11-0ubuntu3.12 [54.9 kB]
Get:3 https://deepin-wine.i-m.dev  deepin-wine8-stable 8.16-deepin10 [194 MB]
Get:4 https://deepin-wine.i-m.dev  deepin-wine-helper 5.2.31-1 [684 kB]                                                                                                                                  
Get:5 https://deepin-wine.i-m.dev  com.qq.weixin.deepin 3.9.7deepin6 [360 MB]                                                                                                                            
Fetched 556 MB in 3min 56s (2,357 kB/s)                                                                                                                                                                  
Selecting previously unselected package deepin-wine8-stable.
(Reading database ... 257536 files and directories currently installed.)
Preparing to unpack .../deepin-wine8-stable_8.16-deepin10_amd64.deb ...
Unpacking deepin-wine8-stable (8.16-deepin10) ...
Preparing to unpack .../deepin-wine-helper_5.2.31-1_amd64.deb ...
Unpacking deepin-wine-helper (5.2.31-1) over (5.2.28-1) ...
Selecting previously unselected package fonts-wqy-microhei.
Preparing to unpack .../fonts-wqy-microhei_0.2.0-beta-3.1_all.deb ...
Unpacking fonts-wqy-microhei (0.2.0-beta-3.1) ...
Selecting previously unselected package com.qq.weixin.deepin.
Preparing to unpack .../com.qq.weixin.deepin_3.9.7deepin6_amd64.deb ...
prerm Old: upgrade to version 3.9.7deepin6
prerm do update script
Unpacking com.qq.weixin.deepin (3.9.7deepin6) over (3.9.5.80deepin10) ...
Old: upgrade to 3.9.7deepin6
Selecting previously unselected package libnss-myhostname:amd64.
Preparing to unpack .../libnss-myhostname_249.11-0ubuntu3.12_amd64.deb ...
Unpacking libnss-myhostname:amd64 (249.11-0ubuntu3.12) ...
Setting up deepin-wine-helper (5.2.31-1) ...
most recently configured version 5.2.28-1
Setting up deepin-wine8-stable (8.16-deepin10) ...
Setting up fonts-wqy-microhei (0.2.0-beta-3.1) ...
Setting up libnss-myhostname:amd64 (249.11-0ubuntu3.12) ...
First installation detected...
Checking NSS setup...
Setting up com.qq.weixin.deepin (3.9.7deepin6) ...
most recently configured version 3.9.5.80deepin10
do install script
Processing triggers for fontconfig (2.13.1-4.2ubuntu5) ...
Processing triggers for libc-bin (2.35-0ubuntu3.5) ...
Processing triggers for man-db (2.10.2-1) ...

```
