### ISSUE TITLE
缺少  deepin-wine32-preloader:i386

### ISSUE THREAD

**Issue by mochp** [zq1997/deepin-wine#35]
deepin-wine32-preloader:i386您也许需要运行“apt --fix-broken install”来修正上面的错误。
下列软件包有未满足的依赖关系：
 deepin.com.wechat:i386 : 依赖: deepin-wine:i386 (>= 2.18-19)
                          依赖: deepin-wine32:i386 但是它将不会被安装
                          依赖: deepin-wine32-preloader:i386 但是它将不会被安装
E: 有未能满足的依赖关系。请尝试不指明软件包的名字来运行“apt --fix-broken install”(也可以指定一个解决办法)。

**Comment by zq1997** [comment]
先试试

apt --fix-broken install

**Comment by mochp** [comment]
還是這個問題，不管什麼指令都抱這個錯

**Comment by zq1997** [comment]
`sudo apt install deepin-wine32-preloader`试试
