### ISSUE TITLE
大佬，安装过程中引用USTC的仓库失效了！！

### ISSUE THREAD

**Issue by culin003** [zq1997/deepin-wine#352]
您希望继续执行吗？ [Y/n] y
错误:1 https://deepin-wine.i-m.dev  libsasl2-modules-db 2.1.28+dfsg-6ubuntu2
  404  Not Found [IP: 202.141.160.110 443]
错误:2 https://deepin-wine.i-m.dev  libsasl2-2 2.1.28+dfsg-6ubuntu2
  404  Not Found [IP: 202.141.160.110 443]
错误:3 https://deepin-wine.i-m.dev  libsasl2-modules 2.1.28+dfsg-6ubuntu2
  404  Not Found [IP: 202.141.160.110 443]
E: 无法下载 https://mirrors.ustc.edu.cn/ubuntu/pool/main/c/cyrus-sasl2/libsasl2-modules-db_2.1.28%2bdfsg-6ubuntu2_amd64.deb  404  Not Found [IP: 202.141.160.110 443]
E: 无法下载 https://mirrors.ustc.edu.cn/ubuntu/pool/main/c/cyrus-sasl2/libsasl2-2_2.1.28%2bdfsg-6ubuntu2_amd64.deb  404  Not Found [IP: 202.141.160.110 443]
E: 无法下载 https://mirrors.ustc.edu.cn/ubuntu/pool/main/c/cyrus-sasl2/libsasl2-modules_2.1.28%2bdfsg-6ubuntu2_amd64.deb  404  Not Found [IP: 202.141.160.110 443]
E: 有几个软件包无法下载，要不运行 apt-get update 或者加上 --fix-missing 的选项再试试？

----------------------- 
OS: Linux Mint 21.2 x86_64 
Host: 82JH Lenovo Legion Y7000P2021H 
Kernel: 5.15.0-84-generic 
Uptime: 1 hour, 13 mins 
Packages: 2314 (dpkg) 
Shell: bash 5.1.16 
Resolution: 1600x900, 1920x1080 
DE: Cinnamon 5.8.4 
WM: Mutter (Muffin) 
WM Theme: Fluent-Dark (Mint-Y) 
Theme: Sunset-Dark [GTK2/3] 
Icons: Mint-L-Red [GTK2/3] 
Terminal: gnome-terminal 
CPU: 11th Gen Intel i7-11800H (16) @ 4.600GHz 
GPU: Intel TigerLake-H GT1 [UHD Graphics] 
GPU: NVIDIA GeForce RTX 3060 Mobile / Max-Q 
Memory: 7980MiB / 31876MiB

**Comment by jinclaudio** [comment]
我也遇到了同样的问题，这个源404了

**Comment by XiaodongAAA** [comment]
我也遇到了同样的问题，请问解决了吗？

**Comment by culin003** [comment]
自己下载那三个缺失的文件安装就可以了



--
发自我的网易邮箱手机智能版



在 2023-09-29 05:15:52，XiaodongAAA ***@***.***> 写道：


我也遇到了同样的问题，请问解决了吗？

**Comment by XiaodongAAA** [comment]
问题是，网上已经无法下载到这几个库了，能够提供个下载的地址吗？

**Comment by wolfyzhang-github** [comment]
you can manually download the corresponding package from the debain repository to address this issue when needed

https://ftp.debian.org/debian/pool/main/c/cyrus-sasl2/

**Comment by chyiever** [comment]
maybe u can download needed packages from ubuntukylin, for example u can install wechat following https://www.ubuntukylin.com/applications/119-cn.html

**Comment by wolfyzhang-github** [comment]
> maybe u can download needed packages from ubuntukylin, for example u can install wechat following https://www.ubuntukylin.com/applications/119-cn.html

@ChyiEver 

- this is not the relevant content discussed by this issue regarding the source 404, we need libsasl2 here, not wechat for other porting methods
- the wechat version of the method you provided is quite old

**Comment by zpatronus** [comment]
> you can manually download the corresponding package from the debain repository to address this issue when needed
> 
> https://ftp.debian.org/debian/pool/main/c/cyrus-sasl2/

@wolfyzhang-github 

Seems that these packages are no longer in this repo either

**Comment by zq1997** [comment]
已经重新配置了，之前用的源过了支持周期了，官方删了。
