### ISSUE TITLE
今天（9/26/2023）突然无法登陆了

### ISSUE THREAD

**Issue by zhuokaizhao** [zq1997/deepin-wine#353]
Ubuntu 22.04 最新版本，今天微信突然无法登陆了，扫码后显示unable to log in。不知道是因为什么，其他人有遇到相似问题嘛？

**Comment by ning-quantvortex** [comment]
遇到同样问题

**Comment by MMMHT** [comment]
我删掉重装解决了

**Comment by zhuokaizhao** [comment]
> 我删掉重装解决了

感谢，重装确实解决了。

**Comment by ning-quantvortex** [comment]
重装之后第一次登录可以， 但是之后因为4K改了字体又不行了

**Comment by zhuokaizhao** [comment]
每次关机后再开开机就又不能登陆了，只能再重装。
