### ISSUE TITLE
ubuntu 22.04 系统libgirepository-1.0-1依赖问题

### ISSUE THREAD

**Issue by lowa9** [zq1997/deepin-wine#354]
**ubuntu 22.04 / Gnome 42.9**

安装wpspdf时报错：
**下列软件包有未满足的依赖关系：
 libgirepository-1.0-1 : 破坏: python-gi (< 3.42.0-1+b1) 但是 3.36.0-1 正要被安装
E: 无法修正错误，因为您要求某些软件包保持现状，就是它们破坏了软件包间的依赖关系。**

尝试按照 #120 去手动下载，但是找不到超过3.42版本的python-gi...

**Comment by zq1997** [comment]
看起来`com.wpspdf.deepin`和`com.jspdf.deepin`都叫wpspdf，不知道是指哪个，后者应该可以安装吧。
前者还依赖python2，依赖出故障是大概率的。

**Comment by lowa9** [comment]
🫠
