### ISSUE TITLE
QQ轻聊版语音问题

### ISSUE THREAD

**Issue by Wings-Fantasy** [zq1997/deepin-wine#36]
QQ轻聊版语音时，其他人说话会有电流声，我说话其他人听不见。
<div align="center"><img alt="设置界面截图" src="https://s1.ax1x.com/2020/03/25/8jOFe0.png" /></div>
在这个设置界面点测试麦克风，说话没有任何反映。点击播放测试声音后也有电流声，音频如下：

[OneDrive文件链接](https://1drv.ms/u/s!ArMU1zkF8BQCgyTwu726ti0VlXU2)

我真的不知道音频该如何外链

**Comment by zq1997** [comment]
硬件驱动问题无解，毕竟是移植的
