### ISSUE TITLE
微信无法从剪切板粘贴图片到输入栏

### ISSUE THREAD

**Issue by G4419** [zq1997/deepin-wine#367]
ubuntu20.04系统
无法从剪切板粘贴图片到输入栏，但可以从文件拖拽到输入栏。
安装 libjpeg62:i386也无法解决问题。

**Comment by lifetin** [comment]
+1

**Comment by zq1997** [comment]
flameshot截图的一直可以

**Comment by 0xHigos** [comment]
> flameshot截图的一直可以

ubuntu 23 ，使用flameshot，和系统自带的截图工具无法直接copy到wechat,得先在文件夹中保存一下，然后才可以复制过去

**Comment by nature21** [comment]
+1

**Comment by G4419** [comment]
后来我用的星火应用商店里的微信就好了，可能我当时哪里没有设置好

**Comment by zq1997** [comment]
可能是wayland问题，切x11桌面也许可以
