### ISSUE TITLE
Ubuntu PPA 仓库连接失效

### ISSUE THREAD

**Issue by Ann-Holmes** [zq1997/deepin-wine#37]
Ubuntu PPA 仓库目前连接失效

```shell
sudo apt update
```
运行上述命令之后, 无法连接该仓库

![image](https://user-images.githubusercontent.com/41296458/78320014-158a7e80-759b-11ea-977c-d550e93a7f6c.png)

**Comment by zq1997** [comment]
ipv6的dns错了，已经修复

**Comment by Ann-Holmes** [comment]
> ipv6的dns错了，已经修复

感谢~
