### ISSUE TITLE
deepin-wine-helper依赖问题

### ISSUE THREAD

**Issue by jiawei666** [zq1997/deepin-wine#379]
![image](https://github.com/zq1997/deepin-wine/assets/24775116/d24841a0-63a1-4fda-8892-985b25639aad)

安装是提示 deepin-wine-helper (>= 5.2.31-1) 
查了一下这个包最高版本好像是5.1.45
https://aur.archlinux.org/packages/deepin-wine-helper

**Comment by xuewenwang** [comment]
how to solve?

**Comment by zq1997** [comment]
sudo apt install deepin-wine-helper 试试吧

**Comment by jiawei666** [comment]
> sudo apt install deepin-wine-helper 试试吧

会引出新的问题
![image](https://github.com/zq1997/deepin-wine/assets/24775116/54c86a7a-9085-4e5c-bcdc-7da179569227)

**Comment by zq1997** [comment]
一直递归下去，可以找出根源

**Comment by jiawei666** [comment]
![image](https://github.com/zq1997/deepin-wine/assets/24775116/e55231cf-2cac-4c4d-a435-5c40b05cdd24)
像这样递归查下去 我也不能解决问题呀

**Comment by jiawei666** [comment]
我之前用的版本倒是没依赖问题 但是被我卸载了 我有办法安装回底版本微信吗

**Comment by zq1997** [comment]
可能和 https://github.com/zq1997/deepin-wine/issues/375#issuecomment-1929107531 有关

**Comment by GFDYMS** [comment]
同样的问题，请问解决了吗

**Comment by jiawei666** [comment]
> 同样的问题，请问解决了吗

没呢

**Comment by GFDYMS** [comment]
> > 同样的问题，请问解决了吗
> 
> 没呢

佛了

**Comment by github68616208** [comment]
ubuntu22。04是没有这个问题的，可以正常安装
ubuntu20.04找到解决方法了，安装星火应用商店和依赖包，依赖就被安装好了，deepin-wine的脚本就可以正常执行安装了

**Comment by jiawei666** [comment]
> ubuntu22。04是没有这个问题的，可以正常安装
> 
> ubuntu20.04找到解决方法了，安装星火应用商店和依赖包，依赖就被安装好了，deepin-wine的脚本就可以正常执行安装了

星火应用商店是啥呀

**Comment by github68616208** [comment]
> > ubuntu22。04是没有这个问题的，可以正常安装
> > ubuntu20.04找到解决方法了，安装星火应用商店和依赖包，依赖就被安装好了，deepin-wine的脚本就可以正常执行安装了
> 
> 星火应用商店是啥呀

linux应用市场，你百度就可以了

**Comment by jiawei666** [comment]
> > > ubuntu22。04是没有这个问题的，可以正常安装
> > > ubuntu20.04找到解决方法了，安装星火应用商店和依赖包，依赖就被安装好了，deepin-wine的脚本就可以正常执行安装了
> > 
> > 
> > 星火应用商店是啥呀
> 
> linux应用市场，你百度就可以了

果然可以 感谢大佬
