### ISSUE TITLE
  Could not wait for server fd - select (11: Resource temporarily unavailable) 

### ISSUE THREAD

**Issue by zhoyifan** [zq1997/deepin-wine#38]
强哥的这个包对我很有帮助,我装wszqkzqk的deepin-wine-ubuntu的时候碰到了 "sudo apt-get install -f"也修不好的dependency问题,装你的deepin-wine就没碰到问题.但是我现在换了一个mirror,就又提示有故障了.qq装不上,但是可以装上了tim.所以想问下你用的是哪个mirror.
Debian 10.3.0 amd64
用的是这个mirror
https://mirrors.tuna.tsinghua.edu.cn/deepin/pool/non-free/d/deepin.com.qq.im/

`
Reading package lists... Done

Building dependency tree       

Reading state information... Done

The following packages were automatically installed and are no longer required:

  gir1.2-gtkspell3-3.0 libpocketsphinx3 libsphinxbase3 python3-aeidon python3-enchant

Use 'sudo apt autoremove' to remove them.

The following NEW packages will be installed:

  deepin.com.qq.im:i386

0 upgraded, 1 newly installed, 0 to remove and 0 not upgraded.

Need to get 85.9 MB of archives.

After this operation, 99.5 MB of additional disk space will be used.

Get:1 https://deepin-wine.i-m.dev/deepin ./ deepin.com.qq.im 9.1.8deepin0 [85.9 MB]

Get:1 https://deepin-wine.i-m.dev/deepin ./ deepin.com.qq.im 9.1.8deepin0 [85.9 MB]                                                                 

Err:1 https://deepin-wine.i-m.dev/deepin ./ deepin.com.qq.im 9.1.8deepin0                                                                           

  Could not wait for server fd - select (11: Resource temporarily unavailable) [IP: 101.6.8.193 443]

E: Failed to fetch https://mirrors.tuna.tsinghua.edu.cn/deepin/pool/non-free/d/deepin.com.qq.im
/deepin.com.qq.im_9.1.8deepin0_i386.deb  Could not wait for server fd - select (11: Resource temporarily unavailable) [IP: 101.6.8.193 443]

E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
`

**Comment by zq1997** [comment]
按理来说，TIM和QQ除了包本身，其余依赖完全相同，TIM好了，排除依赖错误，也排除镜像的问题，应该就是这两个包的下载问题。
你试一下
```
apt-get download deepin.com.qq.im
```
或者
```
wget 'https://mirrors.tuna.tsinghua.edu.cn/deepin/pool/non-free/d/deepin.com.qq.im/deepin.com.qq.im_9.1.8deepin0_i386.deb'
```
看看能正常下载吗。
也许是源里面正常更新，偶尔服务器错误。
