### ISSUE TITLE
找不到服务器

### ISSUE THREAD

**Issue by Lazeny** [zq1997/deepin-wine#4]
在刷新源的时候，找不到服务器，自行添加hosts记录（20开头的IP）则是443端口无法链接

错误:12 https://deepin-wine.i-m.dev/deepin ./ InRelease                        
  无法发起与 deepin-wine.i-m.dev:443 (2001:19f0:5:553f:5400:2ff:fe40:c78e) 的连接 - connect (101: 网络不可达) 无法连接上 deepin-wine.i-m.dev:443 (104.156.224.107)，连接超时
正在读取软件包列表... 完成                                                 
正在分析软件包的依赖关系树       
正在读取状态信息... 完成       
有 1 个软件包可以升级。请执行 ‘apt list --upgradable’ 来查看它们。
W: 无法下载 https://deepin-wine.i-m.dev/deepin/./InRelease  无法发起与 deepin-wine.i-m.dev:443 (2001:19f0:5:553f:5400:2ff:fe40:c78e) 的连接 - connect (101: 网络不可达) 无法连接上 deepin-wine.i-m.dev:443 (104.156.224.107)，连接超时
W: 部分索引文件下载失败。如果忽略它们，那将转而使用旧的索引文件。

**Comment by zq1997** [comment]
直接下载[https://deepin-wine.i-m.dev/deepin/./InRelease](https://deepin-wine.i-m.dev/deepin/./InRelease)这个地址能连通吗？

**Comment by Lazeny** [comment]
> 直接下载https://deepin-wine.i-m.dev/deepin/./InRelease这个地址能连通吗？

能

**Comment by Lazeny** [comment]
> 直接下载https://deepin-wine.i-m.dev/deepin/./InRelease这个地址能连通吗？

浏览器直接可以下，终端需要挂代理

**Comment by zq1997** [comment]
奇怪了，我寻思这服务器也没有被墙啊？
我觉得HOST啥的先恢复吧，然后ping一下看看。

总之得先想办法让`wget https://deepin-wine.i-m.dev/deepin/./InRelease`能正常下载。

**Comment by Lazeny** [comment]
> 奇怪了，我寻思这服务器也没有被墙啊？
> 我觉得HOST啥的先恢复吧，然后ping一下看看。
> 
> 总之得先想办法让`wget https://deepin-wine.i-m.dev/deepin/./InRelease`能正常下载。

挂代理解决了
