### ISSUE TITLE
这个deepinwine的源是自己维护的吗

### ISSUE THREAD

**Issue by wszqkzqk** [zq1997/deepin-wine#40]
https://deepin-wine.i-m.dev 是谁维护的呀
当年我也想搞一个PPA什么的，但是最终还是没有弄
有一个源了，也方便

我弃坑Ubuntu了，你加油

**Comment by zq1997** [comment]
提取了一下deepin和Ubuntu的Packages.gz文件，然后做了一下减法，就做成了这个源了。但是里面的文件还是重定向到deepin的源里去了的。

**Comment by wszqkzqk** [comment]
直接定向貌似有依赖问题吧

**Comment by zq1997** [comment]
重定向大部分，确实有部分丢失的依赖，需要手动维护deb包
