### ISSUE TITLE
安装的时候依然会报依赖问题

### ISSUE THREAD

**Issue by chenzx023** [zq1997/deepin-wine#41]
有一些软件包无法被安装。如果您用的是 unstable 发行版，这也许是
因为系统无法达到您要求的状态造成的。该版本中可能会有一些您需要的软件
包尚未被创建或是它们已被从新到(Incoming)目录移出。
下列信息可能会对解决问题有所帮助：

下列软件包有未满足的依赖关系：
 deepin.com.wechat:i386 : 依赖: deepin-wine:i386 (>= 2.18-19)
                          依赖: deepin-wine32:i386 但是它将不会被安装
                          依赖: deepin-wine32-preloader:i386 但是它将不会被安装

E: 无法修正错误，因为您要求某些软件包保持现状，就是它们破坏了软件包间的依赖关系

我已经按照md操作的

**Comment by zq1997** [comment]
有些发行版确实会有些依赖问题，毕竟不同发行版之间差异太大了。

这么定位一下具体错误看看，
找到报错的依赖，如上面报错中的`deepin-wine32-preloader:i386`，然后尝试（不是真的安装）apt-get install，如此递归，找对最终的缺失安装包，看看准确原因
