### ISSUE TITLE
https://deepin-wine.i-m.dev 连接不上

### ISSUE THREAD

**Issue by 467057463** [zq1997/deepin-wine#42]
``` bash
--2020-04-21 15:10:42--  https://deepin-wine.i-m.dev/setup.sh
正在解析主机 deepin-wine.i-m.dev (deepin-wine.i-m.dev)... 140.82.62.192, 2001:19f0:5:324c:5400:2ff:fea8:3e4f
正在连接 deepin-wine.i-m.dev (deepin-wine.i-m.dev)|140.82.62.192|:443... 失败：连接超时。
正在连接 deepin-wine.i-m.dev (deepin-wine.i-m.dev)|2001:19f0:5:324c:5400:2ff:fea8:3e4f|:443... 失败：网络不可达。
```

**Comment by zq1997** [comment]
无法复现

**Comment by Wings-Fantasy** [comment]
我的Debian系统出现了相似的问题，apt update的时候无法链接
```
W: 无法下载 https://deepin-wine.i-m.dev/deepin/./InRelease  无法发起与 deepin-wine.i-m.dev:443 (2001:19f0:5:324c:5400:2ff:fea8:3e4f) 的连接 - connect (101: 网络不可达) 无法连接上 deepin-wine.i-m.dev:443 (140.82.62.192)，连接超时
```

**Comment by zq1997** [comment]
> 我的Debian系统出现了相似的问题，apt update的时候无法链接
> ```
> W: 无法下载 https://deepin-wine.i-m.dev/deepin/./InRelease  无法发起与 deepin-wine.i-m.dev:443 (2001:19f0:5:324c:5400:2ff:fea8:3e4f) 的连接 - connect (101: 网络不可达) 无法连接上 deepin-wine.i-m.dev:443 (140.82.62.192)，连接超时
> ```

ping得通吗？难道是被墙了？

**Comment by Wings-Fantasy** [comment]
我发现我的apt在使用ipv6，刚刚在怀疑不支持ipv6，所以我强制apt使用ipv4。
apt链接的ip为140.82.62.192，输入到浏览器里显示的是
`网页无法运作，140.82.62.192未发送任何数据`

**Comment by zq1997** [comment]
@Wings-Fantasy 坑啊，这个服务器可能被部分省份墙了，我下午换一个，晚上试试应该就行了。

**Comment by zq1997** [comment]
现在可以试试

**Comment by genghisun** [comment]
Ubuntu18.04也遇到了这个问题
> W: Failed to fetch https://deepin-wine.i-m.dev/deepin/./InRelease  Cannot initiate the connection to deepin-wine.i-m.dev:443 (2001:19f0:5:14e1:5400:2ff:feb5:2fc1). - connect (101: Network is unreachable) Could not connect to deepin-wine.i-m.dev:443 (207.148.29.101). - connect (111: Connection refused)
> W: Failed to fetch https://deepin-wine.i-m.dev/ubuntu-fix/./InRelease  Cannot initiate the connection to deepin-wine.i-m.dev:443 (2001:19f0:5:14e1:5400:2ff:feb5:2fc1). - connect (101: Network is unreachable)
用了梯子`proxychains4 sudo apt update`也同样连接不上

**Comment by zq1997** [comment]
我换了服务器啊，直接浏览器打开网页打开的了吗？

**Comment by genghisun** [comment]
> 我换了服务器啊，直接浏览器打开网页打开的了吗？

打不开……
但是ping的通

**Comment by zq1997** [comment]
现在试试。

下午被一个114.244.13.147的ip反复请求了成百上千次，也不知道是哪家的爬虫。好像nginx崩了

**Comment by genghisun** [comment]
可以了哟～辛苦啦
可以close啦

**Comment by lazebird** [comment]
无法下载 https://deepin-wine.i-m.dev/InRelease
这个文件确实不存在，应该和网络无关，是脚本错误还是？另外出错后还继续执行脚本了
![2022-06-08 11-46-27屏幕截图](https://user-images.githubusercontent.com/12560868/172527377-95e36946-3093-4857-9b49-258afe6aac1b.png)

**Comment by zq1997** [comment]
没有InRelease，必须设置[trusted=yes],才能使用Release

**Comment by lazebird** [comment]
> 无法下载 https://deepin-wine.i-m.dev/InRelease 这个文件确实不存在，应该和网络无关，是脚本错误还是？另外出错后还继续执行脚本了 ![2022-06-08 11-46-27屏幕截图](https://user-images.githubusercontent.com/12560868/172527377-95e36946-3093-4857-9b49-258afe6aac1b.png)

看起来是直接执行setup.sh的问题，执行完单独apt update,再apt install貌似可以

**Comment by Fayhao** [comment]
> > 无法下载 https://deepin-wine.i-m.dev/InRelease 这个文件确实不存在，应该和网络无关，是脚本错误还是？另外出错后还继续执行脚本了 ![2022-06-08 11-46-27屏幕截图](https://user-images.githubusercontent.com/12560868/172527377-95e36946-3093-4857-9b49-258afe6aac1b.png)
> 
> 看起来是直接执行setup.sh的问题，执行完单独apt update,再apt install貌似可以
大佬方便提供一下解决问题的命令行吗？我也遇到了同样的问题，但不同的是我单独运行update也会报同样的错，挂不挂梯都一样
![image](https://github.com/zq1997/deepin-wine/assets/102647612/b45db1fc-73a6-4e38-9069-b3ae6d03cf0c)

**Comment by lazebird** [comment]
> > > 无法下载 https://deepin-wine.i-m.dev/InRelease 这个文件确实不存在，应该和网络无关，是脚本错误还是？另外出错后还继续执行脚本了 ![2022-06-08 11-46-27屏幕截图](https://user-images.githubusercontent.com/12560868/172527377-95e36946-3093-4857-9b49-258afe6aac1b.png)
> > 
> > 
> > 看起来是直接执行setup.sh的问题，执行完单独apt update,再apt install貌似可以
> > 大佬方便提供一下解决问题的命令行吗？我也遇到了同样的问题，但不同的是我单独运行update也会报同样的错，挂不挂梯都一样
> > ![image](https://private-user-images.githubusercontent.com/102647612/325148212-b45db1fc-73a6-4e38-9069-b3ae6d03cf0c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM5NDkxMDYsIm5iZiI6MTcxMzk0ODgwNiwicGF0aCI6Ii8xMDI2NDc2MTIvMzI1MTQ4MjEyLWI0NWRiMWZjLTczYTYtNGUzOC05MDY5LWIzYWU2ZDAzY2YwYy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDI0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQyNFQwODUzMjZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kYWZiYzY5MWRhNDBlMjFkODcwNzYzNDg1NDBlNjZmMGY2ZGMyM2VkM2JiZDNjMTI2YzAzMGQ4NTAxZDc0YTg4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.JMfinGiLDZYWaiH1811PeRzwX-Fgu79X-Shcve5R92k)

非常抱歉，时间太久了，我现在没有继续用这个，记不清当时怎么处理的了

**Comment by tangzhiqiang3** [comment]
wget -O- https://deepin-wine.i-m.dev/setup.sh | sh
--2024-08-14 10:18:34--  https://deepin-wine.i-m.dev/setup.sh
Resolving deepin-wine.i-m.dev (deepin-wine.i-m.dev)... 10.8.6.63, 2406:da18:b3d:e202::64, 2406:da18:880:3801::c8
Connecting to deepin-wine.i-m.dev (deepin-wine.i-m.dev)|10.8.6.63|:443... failed: No route to host.
Connecting to deepin-wine.i-m.dev (deepin-wine.i-m.dev)|2406:da18:b3d:e202::64|:443... failed: Network is unreachable.
Connecting to deepin-wine.i-m.dev (deepin-wine.i-m.dev)|2406:da18:880:3801::c8|:443... failed: Network is unreachable.

 ping deepin-wine.i-m.dev
PING deepin-wine.i-m.dev (10.8.6.63) 56(84) bytes of data.
From 10.245.40.4 (10.245.40.4) icmp_seq=7 Packet filtered
From 10.245.40.4 (10.245.40.4) icmp_seq=11 Packet filtered
From 10.245.40.4 (10.245.40.4) icmp_seq=12 Packet filtered
From 10.245.40.4 (10.245.40.4) icmp_seq=13 Packet filtered
From 10.245.40.4 (10.245.40.4) icmp_seq=14 Packet filtered
From 10.245.40.4 (10.245.40.4) icmp_seq=15 Packet filtered
From 10.245.40.4 (10.245.40.4) icmp_seq=16 Packet filtered


ubuntu22.04, 目前用梯子也是同样的问题，不知道什么原因...

**Comment by zq1997** [comment]
> wget -O- https://deepin-wine.i-m.dev/setup.sh | sh --2024-08-14 10:18:34-- https://deepin-wine.i-m.dev/setup.sh Resolving deepin-wine.i-m.dev (deepin-wine.i-m.dev)... 10.8.6.63, 2406:da18:b3d:e202::64, 2406:da18:880:3801::c8 Connecting to deepin-wine.i-m.dev (deepin-wine.i-m.dev)|10.8.6.63|:443... failed: No route to host. Connecting to deepin-wine.i-m.dev (deepin-wine.i-m.dev)|2406:da18:b3d:e202::64|:443... failed: Network is unreachable. Connecting to deepin-wine.i-m.dev (deepin-wine.i-m.dev)|2406:da18:880:3801::c8|:443... failed: Network is unreachable.
> 
> ping deepin-wine.i-m.dev PING deepin-wine.i-m.dev (10.8.6.63) 56(84) bytes of data. From 10.245.40.4 (10.245.40.4) icmp_seq=7 Packet filtered From 10.245.40.4 (10.245.40.4) icmp_seq=11 Packet filtered From 10.245.40.4 (10.245.40.4) icmp_seq=12 Packet filtered From 10.245.40.4 (10.245.40.4) icmp_seq=13 Packet filtered From 10.245.40.4 (10.245.40.4) icmp_seq=14 Packet filtered From 10.245.40.4 (10.245.40.4) icmp_seq=15 Packet filtered From 10.245.40.4 (10.245.40.4) icmp_seq=16 Packet filtered
> 
> ubuntu22.04, 目前用梯子也是同样的问题，不知道什么原因...

dns被污染了大概，10.0.0.0/8是内网网段

**Comment by tangzhiqiang3** [comment]
@zq1997  那有没有解决方法呢，网上搜索了很多方法都还是没有解决呢
目前用梯子是能访问网页：https://deepin-wine.i-m.dev
但是无论用不用梯子，wget依然出现上面的问题
