### ISSUE TITLE
安装依赖问题

### ISSUE THREAD

**Issue by teapethu** [zq1997/deepin-wine#43]
安装不了啊，报错如下：

Reading package lists... Done
Building dependency tree
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 deepin.com.wechat:i386 : Depends: deepin-wine-helper:i386 (>= 1.2deepin8) but it is not going to be installed
E: Unable to correct problems, you have held broken packages.

**Comment by teapethu** [comment]
之后尝试先安装
apt-get install deepin-wine
安装完成后，再装微信，还是同样的问题。

Debian bullseye testing版本

**Comment by zq1997** [comment]
testing版本的debian移除了`python-gobject`，需要手动安装[http://mirrors.tuna.tsinghua.edu.cn/ubuntu/pool/universe/p/pygobject/python-gobject_3.26.1-2ubuntu1_all.deb](http://mirrors.tuna.tsinghua.edu.cn/ubuntu/pool/universe/p/pygobject/python-gobject_3.26.1-2ubuntu1_all.deb)

**Comment by teapethu** [comment]
> testing版本的debian移除了`python-gobject`，需要手动安装http://mirrors.tuna.tsinghua.edu.cn/ubuntu/pool/universe/p/pygobject/python-gobject_3.26.1-2ubuntu1_all.deb

一大堆没有的依赖，都要一个一个装吗？先是这2个
python-gi
python-gobject-2
然后还有libxxxx，不敢再手动装了

**Comment by zq1997** [comment]
怎么会，好像就是缺失这一个啊

**Comment by teapethu** [comment]
> 怎么会，好像就是缺失这一个啊

这个依赖于：
python-gi
python-gobject-2

第一个还好说，就在同一个地方，我也下了。。。然后第二个我Google了一下，下的也是对的，然后装第二的时候，又让装什么libxxxx的，我就没再继续了

**Comment by teapethu** [comment]
> 怎么会，好像就是缺失这一个啊

还有，那个libxxxx，试过直接apt装，也是没有的。

**Comment by zq1997** [comment]
好像是的，主要是缺`python-gobject`，这个包依赖了你说的那一大串

**Comment by zq1997** [comment]
主要是deepin它们用的是稳定版的debian，然后`python-gobject`在testing版中过期了，手动处理吧，只能找debian稳定版对应的包补上去

**Comment by zwkcoding** [comment]
Depends: deepin-wine-helper

去下载个新的版本吧
https://mirrors.aliyun.com/deepin/pool/non-free/d/

**Comment by zq1997** [comment]
重新运行setup脚本，再试试？

**Comment by teapethu** [comment]
之前一顿手工安装，能用了，但是中文字体显示方块儿，就没再用了，Linux用个微信真难啊~
回头去试试新版，不过我好像还得先搞定中文字体。。。。Anyway, thanks a lot.

**Comment by oPiZiL** [comment]
Ubuntu 16.04.3也有这个问题

**Comment by oPiZiL** [comment]
参考知乎这个链接 https://zhuanlan.zhihu.com/p/73033900  
```
# 1.创建一个Wine文件夹，推荐用bash创建：
cd Document(这里添加你准备放wine的文件夹)
sudo mkdir Wine
sudo chmod 777 Wine(赋予权限)
cd Wine
# 2.克隆项目到本地

git clone https://gitee.com/wszqkzqk/deepin-wine-for-ubuntu.git
# 3.运行安装程序

cd deepin-wine-for-ubuntu
sudo ./install.sh
// KDE桌面或者其他安装出现错误执行 ./KDE-install.sh
```

然后就可以使用apt-get安装微信了
