### ISSUE TITLE
how to update qq and wechat ，please help me!

### ISSUE THREAD

**Issue by johnchan20** [zq1997/deepin-wine#45]

**Comment by zq1997** [comment]
使用`apt`系列命令像更新正常软件包一样更新即可，可以更新到deepin打包的最新版本。

如果是需要更新到腾讯的最新版本，下载微信安装包exe后，`WINEPREFIX=/home/<用户名>/.deepinwine/Deepin-WeChat/ deepin-wine <exe安装包路径>`
