### ISSUE TITLE
使用 https://deepin-wine.i-m.dev 软件源安装，登录QQ立马被封号

### ISSUE THREAD

**Issue by kgbook** [zq1997/deepin-wine#47]
安装流程参考 README.md，执行 setup.sh   后 `sudo apt install deepin.com.qq.im`.
安装完成后，登录QQ，登录成功，QQ弹窗提示安装ActiveX等插件，还没来得及反应，QQ自动被退出。手机QQ也被下线，通知“该帐号涉嫌传播违法违规信息被暂时冻结”。

相关信息：
```shell
$ dpkg -l | grep qq
ii  deepin.com.qq.im:i386   9.1.8deepin0    i386   Tencent QQ Client on Deepin Wine
```

Debian 10.3.0, 登录QQ后什么操作都没的来及做，立马被封号！！！

请确认 https://deepin-wine.i-m.dev 软件源 package 的安全性。

**Comment by zq1997** [comment]
用的清华的软件镜像，先去申诉试试

**Comment by kgbook** [comment]
帐号 | xxxxxxxx
-- | --
时间 | 2020/05/12  10:58:48
来源 | QQ安全中心
原因 | 由于号码存在密码外泄风险，为保护您的帐号、数据等安全，系统已自动冻结QQ

**Comment by kgbook** [comment]
修改密码后已解封，再次登录没再被封号了。
不清楚腾讯安全检测逻辑是怎么样的。。。
应该和软件源没关系。
