### ISSUE TITLE
中文乱码，框框 如何解决

### ISSUE THREAD

**Issue by InfiniteYuan1** [zq1997/deepin-wine#5]
![image](https://user-images.githubusercontent.com/13313946/64680569-9a536500-d4b0-11e9-8216-5bc9e52687b9.png)

谢谢你～

**Comment by zq1997** [comment]
这个问题有点玄，
- 我在同学的Mint/Ubuntu上一直复现不出来，装上去就正常
- 然后对于一些系统语言是非中文的机子，`sudo dpkg-reconfigure locales`选择`zh_CN.UTF-8`为默认就可以解决
- 但似乎网上对于蛮多地方说中文显示为框框

所以你先试试`sudo dpkg-reconfigure locales`设置中文UTF-8然后重启软件，最好还把`~/.deepinwine`目录下的东西清理一下。
不行的话参考 #2 中 @ViggoC 的解决方法（这个issue很长，拖到底看最下面几条就行）

**Comment by InfiniteYuan1** [comment]
![image](https://user-images.githubusercontent.com/13313946/64753969-bb22c580-d557-11e9-90af-6a211127b44e.png)
尴尬，确实不行

**Comment by zq1997** [comment]
那试试这个吧[https://blog.csdn.net/qq_37624415/article/details/82228572](https://blog.csdn.net/qq_37624415/article/details/82228572)
