### ISSUE TITLE
chromebook第一次安装，按安装提示一步步来提示缺少依赖关系，请问这种怎么解决啊？

### ISSUE THREAD

**Issue by lee2333** [zq1997/deepin-wine#51]
下列软件包有未满足的依赖关系：
 deepin.com.wechat:i386 : 依赖: deepin-wine:i386 (>= 2.18-19)
                          依赖: deepin-wine32:i386 但是它将不会被安装
                          依赖: deepin-wine32-preloader:i386 但是它将不会被安装
                          依赖: deepin-wine-helper:i386 (>= 1.2deepin8) 但是它将不会被安

**Comment by zq1997** [comment]
这个`deepin-wine-helper:i386`软件包出了问题，先安装它看什么报错

**Comment by lee2333** [comment]
我输入dpkg --print-architecture出现arm64；dpkg --print-foreign-architectures出现i386，是不是就是安装上这个软件包了呀？？

**Comment by zq1997** [comment]
那只是第一步，不是全部
