### ISSUE TITLE
sudo apt-get install deepin.com.wechat报错

### ISSUE THREAD

**Issue by dayfan0810** [zq1997/deepin-wine#53]
$ sudo apt-get install deepin.com.wechat
正在读取软件包列表... 完成
正在分析软件包的依赖关系树       
正在读取状态信息... 完成       
有一些软件包无法被安装。如果您用的是 unstable 发行版，这也许是
因为系统无法达到您要求的状态造成的。该版本中可能会有一些您需要的软件
包尚未被创建或是它们已被从新到(Incoming)目录移出。
下列信息可能会对解决问题有所帮助：

下列软件包有未满足的依赖关系：
 deepin.com.wechat:i386 : 依赖: deepin-wine:i386 (>= 2.18-19)
                          依赖: deepin-wine32:i386 但是它将不会被安装
                          依赖: deepin-wine32-preloader:i386 但是它将不会被安装
                          依赖: deepin-wine-helper:i386 (>= 1.2deepin8) 但是它将不会被安装
E: 无法修正错误，因为您要求某些软件包保持现状，就是它们破坏了软件包间的依赖关系。

**Comment by zq1997** [comment]
sudo apt update

**Comment by wxxxxxxh** [comment]
> sudo apt update

额执行了该命令之后还是会报这个错误

**Comment by zq1997** [comment]
> > sudo apt update
> 
> 额执行了该命令之后还是会报这个错误

系统版本什么？以及最底层哪个依赖错了？

**Comment by wxxxxxxh** [comment]
> > > sudo apt update
> > 
> > 
> > 额执行了该命令之后还是会报这个错误
> 
> 系统版本什么？以及最底层哪个依赖错了？

系统版本是16.04
报错是以下信息：
----------
正在读取软件包列表... 完成
正在分析软件包的依赖关系树       
正在读取状态信息... 完成       
有一些软件包无法被安装。如果您用的是 unstable 发行版，这也许是
因为系统无法达到您要求的状态造成的。该版本中可能会有一些您需要的软件
包尚未被创建或是它们已被从新到(Incoming)目录移出。
下列信息可能会对解决问题有所帮助：

下列软件包有未满足的依赖关系：
 deepin.com.wechat:i386 : 依赖: deepin-wine:i386 (>= 2.18-19)
                          依赖: deepin-wine32:i386 但是它将不会被安装
                          依赖: deepin-wine32-preloader:i386 但是它将不会被安装
                          依赖: deepin-wine-helper:i386 (>= 1.2deepin8) 但是它将不会被安装
E: 无法修正错误，因为您要求某些软件包保持现状，就是它们破坏了软件包间的依赖关系。

**Comment by zq1997** [comment]
先尝试安装缺失的依赖，找到最底层的错误。
另外推荐升级ubuntu，16太老了，18起步

**Comment by dayfan0810** [comment]
> 先尝试安装缺失的依赖，找到最底层的错误。
> 另外推荐升级ubuntu，16太老了，18起步

哎，公司电脑不敢升级

**Comment by zq1997** [comment]
那可以试试把那缺失的底层依赖手动dpkg安装，然后再apt
