### ISSUE TITLE
deepin-wine5 可以兼容微信的新版本，是否有升级到deepin-wine5的计划?

### ISSUE THREAD

**Issue by holmeszyx** [zq1997/deepin-wine#59]
这个里面有人验证过。

[https://github.com/countstarlight/deepin-wine-wechat-arch/issues/42#issuecomment-655375955](https://github.com/countstarlight/deepin-wine-wechat-arch/issues/42#issuecomment-655375955)

不知是否有升级到deepin-wine5的计划？

**Comment by zq1997** [comment]
微信的程序包还是依赖于2.6的吧，没看见新的

**Comment by holmeszyx** [comment]
明白，本地项目还是基于deepin官方包打包的是吧。那就等官方自己升级了。

Arch哪个是他门自己移植的。

**Comment by zq1997** [comment]
估计是自己打包的，deepin v20还是beta，估计在慢慢放出官方包吧
