### ISSUE TITLE
deep-wine-wechat 运行的小bug

### ISSUE THREAD

**Issue by Iranb** [zq1997/deepin-wine#6]
操作系统：ubuntu 18.04
deepin-wine 版本为使用该项目安装的版本
在安装微信后可以正常使用，但是在最小化到托盘的时候，屏幕中央会留下黑色小方块，浮动在窗口最底层，可以被其他窗口覆盖，鼠标移动到上面后指针会显示wechat点击按钮的图标，估计可能是窗口loading初始化的时候的相关图标加载bug
（图片不知道怎么上传呜呜呜）
在截图的过程中发现了一个小bug，使用该项目安装的TIM在最小化到托盘后，再次启动则截图功能失效，或更改截图设置使得截图时会隐藏tim窗口，此操作也会导致截图功能失效，这个感觉不是这个项目本身编译的问题，个人认为是wine的问题，提出issue的目的是希望能够讨论一下相关的解决方案。本人非常欣赏且感激您的项目为开发者带来的便利，也希望能变得更好^_^

**Comment by Iranb** [comment]
![微信最小化后留下的黑色区域](https://user-images.githubusercontent.com/49674669/64924280-572d2500-d815-11e9-8895-1d41d125ff86.png)补充一下图片

**Comment by zq1997** [comment]
1. 微信的黑框是表情包窗口，在任意聊天界面输入`666`，不需要发送，可以去除黑框
2. TIM截图确实是有问题，不知道怎么解决，我个人是把`alt ctrl A`绑定到系统截图了

因为用的deepin软件包，而deepin本身又是包装的windows软件，两层移植，在ubuntu上肯定不可避免各种小问题，确实没有办法。
