### ISSUE TITLE
命令sudo apt update 会报错，按文档写的升级命令没用

### ISSUE THREAD

**Issue by liuguodong1019** [zq1997/deepin-wine#61]
命中:1 http://dl.google.com/linux/chrome/deb stable InRelease
命中:2 http://us.archive.ubuntu.com/ubuntu bionic InRelease                    
命中:3 http://ppa.launchpad.net/ondrej/php/ubuntu bionic InRelease             
获取:4 http://security.ubuntu.com/ubuntu bionic-security InRelease [88.7 kB]   
获取:5 http://us.archive.ubuntu.com/ubuntu bionic-updates InRelease [88.7 kB]  
命中:6 http://ppa.launchpad.net/videolan/master-daily/ubuntu bionic InRelease  
忽略:7 https://deepin-wine.i-m.dev/deepin ./ InRelease                         
忽略:8 https://deepin-wine.i-m.dev/ubuntu-fix ./ InRelease
获取:9 http://us.archive.ubuntu.com/ubuntu bionic-backports InRelease [74.6 kB]
错误:10 https://deepin-wine.i-m.dev/deepin ./ Release                          
  404  Not Found [IP: 178.128.17.49 443]
错误:11 https://deepin-wine.i-m.dev/ubuntu-fix ./ Release                      
  404  Not Found [IP: 178.128.17.49 443]
正在读取软件包列表... 完成                                                     
E: 仓库 “https://deepin-wine.i-m.dev/deepin ./ Release” 不再含有 Release 文件。
N: 无法安全地用该源进行更新，所以默认禁用该源。
N: 参见 apt-secure(8) 手册以了解仓库创建和用户配置方面的细节。
E: 仓库 “https://deepin-wine.i-m.dev/ubuntu-fix ./ Release” 不再含有 Release 文件。
N: 无法安全地用该源进行更新，所以默认禁用该源。
N: 参见 apt-secure(8) 手册以了解仓库创建和用户配置方面的细节。

**Comment by zq1997** [comment]
文档除了点错，看新的步骤

**Comment by liuguodong1019** [comment]
> 文档出了点错，看新的步骤
已经解决，感谢
