### ISSUE TITLE
Ubuntu 2004系统里面无法录入中文，英文正常

### ISSUE THREAD

**Issue by taiyong** [zq1997/deepin-wine#66]
在Ubuntu 2004系统里面使用Wechat的时候对话框输入英文正常没问题，但中文无法录入（输入法会显示打出来的中文，但是无法录入到对话框，也无法发送）。但是从别的文件上拷贝来的中文可以粘贴到对话框并成功发送。

**Comment by zq1997** [comment]
重启

**Comment by taiyong** [comment]
重启不太有帮助。我重启了微信，也重启了电脑，结果依旧。电脑系统是Ubuntu2004，安装了所有更新，输入法选的是Ibus。

**Comment by zq1997** [comment]
我用搜狗输入法是可以的

**Comment by sheep94lion** [comment]
https://blog.csdn.net/qq_18649781/article/details/87476043
可以看看这个。对我有用。

**Comment by NingAnMe** [comment]
`sudo vim /opt/deepinwine/tools/run.sh`
增加下面几行内容
```
export GTK_IM_MODULE="fcitx"
export QT_IM_MODULE="fcitx" 
export XMODIFIERS="@im=fcitx"
```
重启微信

**Comment by MakerFace** [comment]
> `sudo vim /opt/deepinwine/tools/run.sh` 增加下面几行内容
> 
> ```
> export GTK_IM_MODULE="fcitx"
> export QT_IM_MODULE="fcitx" 
> export XMODIFIERS="@im=fcitx"
> ```
> 
> 重启微信

有用。同时也适用于ibus框架，将`fcitx`改为`ibus`就行。
新版本文件路径改了：`/opt/apps/com.qq.weixin.deepin/files/run.sh`

**Comment by Huang-CL** [comment]
@MakerFace 
我尝试了，但是无论添加的内容使用fcitx还是ibus都不解决问题
在微信和QQ中均无法调用中文输入法，英文输入正常

系统：ubuntu 22.04.2
系统语言为英文
deepin-wine6-stable --version: wine version: 6.0
GNOME Version: 42.5
Keyboard input method system: IBus
已安装输入法包括系统自带Chinese Intelligent Pinyin和Rime

**Comment by MakerFace** [comment]
> 

我在VMWare虚拟机中使用Ubuntu 22.04.2安装微信3.7.0.30deepin17版本，以及ibus-rime，只在`~/.pam_enviornment`中写入如下配置就能输入中文了。
```conf
LANGUAGE	DEFAULT=en_US:en
LANG	DEFAULT=en_US.UTF-8
LC_NUMERIC	DEFAULT=en_US.UTF-8
LC_TIME	DEFAULT=en_US.UTF-8
LC_MONETARY	DEFAULT=en_US.UTF-8
LC_PAPER	DEFAULT=en_US.UTF-8
LC_NAME	DEFAULT=en_US.UTF-8
LC_ADDRESS	DEFAULT=en_US.UTF-8
LC_TELEPHONE	DEFAULT=en_US.UTF-8
LC_MEASUREMENT	DEFAULT=en_US.UTF-8
LC_IDENTIFICATION	DEFAULT=en_US.UTF-8
PAPERSIZE	DEFAULT=letter
export GTK_IM_MODULE="ibus"
export QT_IM_MODULE="ibus"
export XMODIFIERS="@im=ibus"
```
![image](https://user-images.githubusercontent.com/19760290/230758464-bc46a227-9410-4010-b0d8-b345f4730ea6.png)

**Comment by MakerFace** [comment]
> @MakerFace 我尝试了，但是无论添加的内容使用fcitx还是ibus都不解决问题 在微信和QQ中均无法调用中文输入法，英文输入正常
> 
> 系统：ubuntu 22.04.2 系统语言为英文 deepin-wine6-stable --version: wine version: 6.0 GNOME Version: 42.5 Keyboard input method system: IBus 已安装输入法包括系统自带Chinese Intelligent Pinyin和Rime

我在VMWare虚拟机中安装了Ubuntu 22.04.2，以及微信3.7.0.30deepin17、IBus1.5.22、ibus-rime等，在设置中添加输入源后logout或reboot，可以输入中文，并没有复现这个问题。

**Comment by Huang-CL** [comment]
> 我在VMWare虚拟机中安装了Ubuntu 22.04.2，以及微信3.7.0.30deepin17、IBus1.5.22、ibus-rime等，在设置中添加输入源后logout或reboot，可以输入中文，并没有复现这个问题。

多谢回复，我目前微信版本是3.7.0.29，准备升级一下试试。添加输入源是指下面这样写吗？还是用fcitx？
```
export GTK_IM_MODULE="ibus"
export QT_IM_MODULE="ibus" 
export XMODIFIERS="@im=ibus"
```

**Comment by MakerFace** [comment]
> > 我在VMWare虚拟机中安装了Ubuntu 22.04.2，以及微信3.7.0.30deepin17、IBus1.5.22、ibus-rime等，在设置中添加输入源后logout或reboot，可以输入中文，并没有复现这个问题。
> 
> 多谢回复，我目前微信版本是3.7.0.29，准备升级一下试试。添加输入源是指下面这样写吗？还是用fcitx？
> 
> ```
> export GTK_IM_MODULE="ibus"
> export QT_IM_MODULE="ibus" 
> export XMODIFIERS="@im=ibus"
> ```

我是在`gnome-control-center`中的`Region and Language`中设置的输入法框架。

**Comment by Huang-CL** [comment]
也就是说输入法框架无论选择fcitx还是ibus，添加到`/opt/apps/com.qq.weixin.deepin/files/run.sh`的脚本都应该是
```
export GTK_IM_MODULE="fcitx"
export QT_IM_MODULE="fcitx" 
export XMODIFIERS="@im=fcitx"
```
是这个意思吗？谢谢

我刚刚尝试了，输入法框架选择ibus，并且添加上面的脚本，之后登出ubuntu账户重新登陆，问题仍然存在。另外wechat自己无法从3.7.0.29更新到30, 更新的时候报错说“未能下载”。

**Comment by Huang-CL** [comment]
我还尝试了干脆删除英文输入法，只保留中文输入法。结果还是无法输入中文。说明不是输入法切换的问题。

**Comment by MakerFace** [comment]
> 也就是说输入法框架无论选择fcitx还是ibus，添加到`/opt/apps/com.qq.weixin.deepin/files/run.sh`的脚本都应该是
> 
> ```
> export GTK_IM_MODULE="fcitx"
> export QT_IM_MODULE="fcitx" 
> export XMODIFIERS="@im=fcitx"
> ```
> 
> 是这个意思吗？谢谢
> 
> 我刚刚尝试了，输入法框架选择ibus，并且添加上面的脚本，之后登出ubuntu账户重新登陆，问题仍然存在。另外wechat自己无法从3.7.0.29更新到30, 更新的时候报错说“未能下载”。

我没有在新版本的`run.sh`中添加这些环境变量，只在gnome的设置界面中设置了语言和区域的输入源，如下：
![image](https://user-images.githubusercontent.com/19760290/230842152-cffa2705-dc5b-4b17-b7fe-4a29a7966a07.png)
可以通过`apt list --installed | grep weixin`查询版本，如果是wine6的话，应该是3.7.0.30deepin17，不能通过WeChat自带的更新功能来更新软件。

**Comment by MakerFace** [comment]
> 我还尝试了干脆删除英文输入法，只保留中文输入法。结果还是无法输入中文。说明不是输入法切换的问题。

其它软件可以使用中文输入法嘛？

**Comment by Huang-CL** [comment]
很感谢你的回复。
1. gnome的设置我们看起来是差不多的。只不过我的输入法设置在Keyboard页面中，不在Region & Language里面。剩下的设置看上去和你完全一样。
2. 我的版本也是 3.7.0.30deepin17 i386， 只是微信内部显示的版本号是3.7.0.29，那看起来也是一样的。
3. 可以，我现在就是用这个系统在打字。在比如WPS，emacs里面都正常。

**Comment by MakerFace** [comment]
> 很感谢你的回复。
> 
> 1. gnome的设置我们看起来是差不多的。只不过我的输入法设置在Keyboard页面中，不在Region & Language里面。剩下的设置看上去和你完全一样。
> 2. 我的版本也是 3.7.0.30deepin17 i386， 只是微信内部显示的版本号是3.7.0.29，那看起来也是一样的。
> 3. 可以，我现在就是用这个系统在打字。在比如WPS，emacs里面都正常。

如果你不是第一次安装，可以试着按README的清理步骤把wine的环境清理一下。

**Comment by Huang-CL** [comment]
我是第一次安装。上周20.04的系统在一次更新之后搞乱了，各种包之间的dependency搞不定，安装几乎所有的包都说有depends问题，于是放弃重装的22.04系统。之前在20.04的时候用的搜狗输入法，虽然可以用，但是感觉和wine兼容也不是很好，经常把系统搞死机，所以重装之后不想用搜狗了。

**Comment by MakerFace** [comment]
> 我是第一次安装。上周20.04的系统在一次更新之后搞乱了，各种包之间的dependency搞不定，安装几乎所有的包都说有depends问题，于是放弃重装的22.04系统。之前在20.04的时候用的搜狗输入法，虽然可以用，但是感觉和wine兼容也不是很好，经常把系统搞死机，所以重装之后不想用搜狗了。

刚刚又在新的虚拟机测试了一下，还是没有复现你的问题，我的步骤如下：
1. 安装微信
    ```bash
    wget -O- https://deepin-wine.i-m.dev/setup.sh | sh
    sudo apt-get install com.qq.weixin.deepin
    ```
2. 安装ibus和ibus-rime
    ```bash
    sudo apt install ibus ibus-rime
    ```
    ![image](https://user-images.githubusercontent.com/19760290/230855212-2722275f-16a3-42ed-b651-a7d6f540343e.png)

3. 重启或登出后，进入系统设置输入源
![image](https://user-images.githubusercontent.com/19760290/230853325-4e3835b4-3db8-4379-bcdf-a073eb783df9.png)
![image](https://user-images.githubusercontent.com/19760290/230853756-e042e79d-529d-4e1d-83dc-c9f447a89b4b.png)
![image](https://user-images.githubusercontent.com/19760290/230853854-e4f63a88-ed45-4edf-ae6f-3b2a5619f122.png)
4. 打开微信测试
![image](https://user-images.githubusercontent.com/19760290/230854101-f9dc341a-489f-44c7-a78d-3d39f347a585.png)

**Comment by Huang-CL** [comment]
我们的设置应该是完全一样的。ibus好像是系统自己就有，不需要额外安装。我和你一样的方法安装了微信以及rime。如果保留英文输入法，那么切换输入法的时候会闪一下中文输入法，马上就变回英文输入法。如果把英文输入法干脆删掉，那么虽然选定的是中文输入法，但是不会出现选词框，而且英文直接作为输入，也就是和英文输入法状态完全一致。我刚刚又试了，如果选择`use the same source for all windows`，那么可以切换到中文，但是仍然无法输入中文，和删掉英文输入法的状态相同。
![image](https://user-images.githubusercontent.com/13855548/230856058-088ee38e-cfb6-4a14-87df-72755677618d.png)

![image](https://user-images.githubusercontent.com/13855548/230855972-0e6d32fa-d7e6-4fca-a9c4-3d8df5bad9bd.png)

**Comment by MakerFace** [comment]
可以尝试完全清除wine环境，重新安装试试。

**Comment by Huang-CL** [comment]
完全清除wine环境之后重新安装，问题解决了！非常感谢！

**Comment by Huang-CL** [comment]
我现在是如果选择`Use the same source for all windows`，那么就一切正常。
但如果切换到`Switch input sources individually for each window`，就又会变成原本无法切换到中文输入法的状态。这个问题如果能解决最好，不过既然已经可用了，先这么用着也问题不大了
