### ISSUE TITLE
ubuntu18 有没有遇到桌面右上角有异常的长方块

### ISSUE THREAD

**Issue by dongdongqiang2018** [zq1997/deepin-wine#67]
像下图这样，偶尔在某个应用下打开，他就会一直是应用右上角的样子
![微信图片_20200811153336](https://user-images.githubusercontent.com/49979601/89870390-59942c80-dbe8-11ea-9af0-d4900ed7a109.png)

![ec2e12e2112b109bd7d5fe0e574b981](https://user-images.githubusercontent.com/49979601/89871510-1a66db00-dbea-11ea-9c36-13474efd2ed9.png)

![69bc8a9221f2d783303c8498930bed1](https://user-images.githubusercontent.com/49979601/89870471-76c8fb00-dbe8-11ea-838f-224c99bb3bc6.png)

**Comment by zq1997** [comment]
因为没有了任务栏

**Comment by gaazau** [comment]
需要安装`Topicons Plus`并启用，[参考这里](https://blog.csdn.net/yukun_hh/article/details/105412330)
