### ISSUE TITLE
deepin-wechat 聊天窗口输入中文字符出现乱码

### ISSUE THREAD

**Issue by devsea** [zq1997/deepin-wine#7]
如图所示:数字没有问题
![微信图片_20190921145728.jpg](https://i.loli.net/2019/09/21/vPk2bQ65a7TYSod.jpg)

**Comment by zq1997** [comment]
似乎很多人都发现有字体问题,先看看网上其他人的方法能解决吗?

**Comment by Leon1128** [comment]
同问

**Comment by zq1997** [comment]
试试 https://blog.csdn.net/qq_37624415/article/details/82228572

**Comment by Leon1128** [comment]
。。。不仅没用，还多了黑窗

**Comment by zq1997** [comment]
参考[https://github.com/zq1997/deepin-wine/blob/master/README.md#%E5%8D%B8%E8%BD%BD%E6%B8%85%E7%90%86](https://github.com/zq1997/deepin-wine/blob/master/README.md#%E5%8D%B8%E8%BD%BD%E6%B8%85%E7%90%86卸载重装)

**Comment by Leon1128** [comment]
https://github.com/wszqkzqk/deepin-wine-ubuntu/issues/136#issuecomment-514585722用这个方法解决了。
