### ISSUE TITLE
大佬，求帮忙解决一下依赖问题，2天了 ((哭。。

### ISSUE THREAD

**Issue by eytb2** [zq1997/deepin-wine#72]
直接用你的脚本装，提示如下
`sudo apt-get install deepin.com.qq.office

Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 deepin.com.qq.office:i386 : Depends: deepin-wine:i386 (>= 1.9-11)
                             Depends: deepin-wine32:i386 but it is not going to be installed
                             Depends: deepin-wine32-preloader:i386 but it is not going to be installed
                             Depends: deepin-wine-helper:i386 (>= 1.0deepin34) but it is not going to be installed
E: Unable to correct problems, you have held broken packages.`

各种方式都试了，装不了。

能不能加你个QQ，沟通方便一点， 1219964453

**Comment by zq1997** [comment]
你用`apt-get install -s xxxx`一路尝试，看看最底层的以来错在哪里了

**Comment by zq1997** [comment]
`Depends: xxxx but it is not going to be installed`

字面意思，这说明系统试图安装`xxxx`但是无法装上去，这一般是你已有的软件源配置问题、或者安装过了一些有冲突的东西。

那么，你应该试着安装`xxxx`，执行`apt-get install -s xxxx`（不需sudo，只是模拟，放心测试），它一般又会接着告诉你`依赖: yyyy 但是它将不会被安装`，说明更底层的错误出在了`yyyy`，不断尝试，先找到罪魁祸首。

**Comment by eytb2** [comment]
@zq1997 嗯， 解决了。  我删除了一个关于dpkg相关的state文件。然后重新生成了。 太难了
