### ISSUE TITLE
Pixelbook的Crostini(Debian)，安装微信时依赖问题无法解决

### ISSUE THREAD

**Issue by Karl15926** [zq1997/deepin-wine#76]
*如果你是Linux新手，请严格按照下面的模板来提问，你见过去公安局报案直接说“我钱丢了”但是不说时间地点经过的？请互相尊重，不要一上来什么信息都没有直接贴问题。*
*如果你对Linux比较熟悉，并且明白问题的根本原因出在哪里，甚至做了简单的复现，那自由表述即可，不必拘泥下面的模板。*

**系统版本**
通过`lsb_release -a`查看。
Debian bullseye

**桌面类型**
Gnome？KDE？不清楚的话通过`echo $XDG_CURRENT_DESKTOP`查看。
KDE

**软件源列表**
`grep -rn '^\s*deb ' --include '*.list' /etc/apt/`的输出。

`/etc/apt/sources.list:1:deb http://ftp.cn.debian.org/debian bullseye main`
`/etc/apt/sources.list:2:deb https://deb.debian.org/debian buster main`
`/etc/apt/sources.list:3:deb https://deb.debian.org/debian-security buster/updates main`
`/etc/apt/sources.list.d/cros.list:1:deb https://storage.googleapis.com/cros-packages/86 buster main`
`/etc/apt/sources.list.d/deepin-wine.i-m.dev.list:1:deb [trusted=yes] https://deepin-wine.i-m.dev /`

**问题描述**

问题是怎么产生的，有什么表现，如何复现。

执行`sudo apt install deepin.com.wechat`
有依赖问题，libgirepository破坏python-gi (< 3.34.0-4~) 但是 3.30.4-1 正要被安装。
![Screenshot 2020-09-04 at 19.22.32.png](https://i.loli.net/2020/09/04/upC75kdhaAgbSBZ.png)

**Comment by zq1997** [comment]
先看看这个![https://github.com/zq1997/deepin-wine#%E5%AE%89%E8%A3%85%E4%BE%9D%E8%B5%96%E9%97%AE%E9%A2%98](https://github.com/zq1997/deepin-wine#%E5%AE%89%E8%A3%85%E4%BE%9D%E8%B5%96%E9%97%AE%E9%A2%98)

**Comment by zq1997** [comment]
`apt-cache policy python-gi`
看看输出

**Comment by Karl15926** [comment]
我把源换成Debian 10.0(buster)就好了……

**Comment by disburden** [comment]
@Karl15926 我刚装了ubuntu20.10 遇到了和你一样的问题,我也尝试着更换源,但是不起作用,能把你用的源发一份给我吗?谢谢!
油箱:disburden@88.com

**Comment by Karl15926** [comment]
> @Karl15926 我刚装了ubuntu20.10 遇到了和你一样的问题,我也尝试着更换源,但是不起作用,能把你用的源发一份给我吗?谢谢!
> email:disburden@88.com

就是清华的源和中科大的源，没什么特别的，之前装不上主要是我的Debian版本是buster我却用了bullsye版本的源
