### ISSUE TITLE
Ubuntu 20.04 ，安装微信运行会存在卡死的情况

### ISSUE THREAD

**Issue by WuChenDi** [zq1997/deepin-wine#77]
**系统版本**
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.1 LTS
Release:	20.04
Codename:	focal

**桌面类型**
ubuntu:GNOME

**软件源列表**
/etc/apt/sources.list.d/google-chrome.list:3:deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main
/etc/apt/sources.list.d/deepin-wine.i-m.dev.list:1:deb [trusted=yes] https://deepin-wine.i-m.dev /
/etc/apt/sources.list:5:deb http://cn.archive.ubuntu.com/ubuntu/ focal main restricted
/etc/apt/sources.list:10:deb http://cn.archive.ubuntu.com/ubuntu/ focal-updates main restricted
/etc/apt/sources.list:16:deb http://cn.archive.ubuntu.com/ubuntu/ focal universe
/etc/apt/sources.list:18:deb http://cn.archive.ubuntu.com/ubuntu/ focal-updates universe
/etc/apt/sources.list:26:deb http://cn.archive.ubuntu.com/ubuntu/ focal multiverse
/etc/apt/sources.list:28:deb http://cn.archive.ubuntu.com/ubuntu/ focal-updates multiverse
/etc/apt/sources.list:36:deb http://cn.archive.ubuntu.com/ubuntu/ focal-backports main restricted universe multiverse
/etc/apt/sources.list:46:deb http://security.ubuntu.com/ubuntu focal-security main restricted
/etc/apt/sources.list:48:deb http://security.ubuntu.com/ubuntu focal-security universe
/etc/apt/sources.list:50:deb http://security.ubuntu.com/ubuntu focal-security multiverse

**问题描述**
安装运行打开正常运行（尝试调整分辨率，发送消息，查看图片/视频）就会出现这种情况

![2020-09-06 09-12-59屏幕截图](https://user-images.githubusercontent.com/31385662/92316070-8ee23d80-f021-11ea-809b-c3854fc29fcf.png)

**Comment by zq1997** [comment]
把输入法杀了试试

**Comment by WuChenDi** [comment]
> 把输入法杀了了试试

还是一样

**Comment by typoverflow** [comment]
Ubuntu 20.04, Gnome遇到了同样的问题，运行微信后点击任意对话框会卡死。
因为搜狗输入法仅最新版本支持Ubuntu 20.04，所以将输入法降级不太可行。

**Comment by function2-llx** [comment]
同，不止微信，Tim 也有同样的问题，具体表现为关闭输入法时 fcitx 就会重启。

**Comment by iamli01** [comment]
我18.04也出现这个问题,卸载了sogoupinyin_2.3.2.07, 重装了sogoupinyin_2.3.1.0112就好了,不再卡死了

**Comment by function2-llx** [comment]
> 我18.04也出现这个问题,卸载了sogoupinyin_2.3.2.07, 重装了sogoupinyin_2.3.1.0112就好了,不再卡死了

18.04 可以通过输入法降级的办法解决，但是 20.04 不行，因为两个系统用的 Qt 版本不同，搜狗还专门为 20.04 出了新的输入法。

**Comment by function2-llx** [comment]
一个临时的输入解决方案：在 telegram 中打好字然后复制粘贴过去，一定要注意微信中不可以开输入法，测试有效。

**Comment by Samge0** [comment]
同样的问题。。。

**Comment by Samge0** [comment]
但我目前用的是系统默认的输入法，在装了TopIcons Plus后，如果出现卡死的情况，我先右击一下状态栏上的微信图标随便选择一个功能选项，然后再切回微信聊天窗口就能正常输入了。

**Comment by kaizengjun** [comment]
升级搜狗输入法到v2.4.0版本后没有这个问题了。

**Comment by function2-llx** [comment]
> 升级搜狗输入法到v2.4.0版本后没有这个问题了。

同样升级后问题解决。
@zq1997 所以应该是输入法的问题，此 issue 应该可以关闭了。

**Comment by wxb2dyj** [comment]
> 升级搜狗输入法到v2.4.0版本后没有这个问题了。

我感谢你，折腾了很久从没有想过是搜狗输入法问题。
