### ISSUE TITLE
Ubuntu18.04安装搜狗输入法之后微信出现卡死

### ISSUE THREAD

**Issue by YaboSun** [zq1997/deepin-wine#78]
*如果你是Linux新手，请严格按照下面的模板来提问，你见过去公安局报案直接说“我钱丢了”但是不说时间地点经过的？请互相尊重，不要一上来什么信息都没有直接贴问题。*
*如果你对Linux比较熟悉，并且明白问题的根本原因出在哪里，甚至做了简单的复现，那自由表述即可，不必拘泥下面的模板。*

**系统版本**
Ubuntu18.04

**桌面类型**
Gnome

**软件源列表**
/etc/apt/sources.list:5:deb http://mirrors.aliyun.com/ubuntu/ bionic main restricted
/etc/apt/sources.list:10:deb http://mirrors.aliyun.com/ubuntu/ bionic-updates main restricted
/etc/apt/sources.list:16:deb http://mirrors.aliyun.com/ubuntu/ bionic universe
/etc/apt/sources.list:18:deb http://mirrors.aliyun.com/ubuntu/ bionic-updates universe
/etc/apt/sources.list:26:deb http://mirrors.aliyun.com/ubuntu/ bionic multiverse
/etc/apt/sources.list:28:deb http://mirrors.aliyun.com/ubuntu/ bionic-updates multiverse
/etc/apt/sources.list:36:deb http://mirrors.aliyun.com/ubuntu/ bionic-backports main restricted universe multiverse
/etc/apt/sources.list:46:deb http://mirrors.aliyun.com/ubuntu/ bionic-security main restricted
/etc/apt/sources.list:48:deb http://mirrors.aliyun.com/ubuntu/ bionic-security universe
/etc/apt/sources.list:50:deb http://mirrors.aliyun.com/ubuntu/ bionic-security multiverse
/etc/apt/sources.list.d/vscode.list:3:deb [arch=amd64] http://packages.microsoft.com/repos/vscode stable main
/etc/apt/sources.list.d/deepin-wine.i-m.dev.list:1:deb [trusted=yes] https://deepin-wine.i-m.dev /
/etc/apt/sources.list.d/google-chrome.list:3:deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main

**问题描述**
安装搜狗输入法之后微信无法使用，卸载搜狗输入法之后正常使用

**Comment by YaboSun** [comment]
按照前面评论降低搜狗输入法版本解决

**Comment by zarzen** [comment]
哪个搜狗的版本可以？

**Comment by YaboSun** [comment]
@zarzen sogoupinyin_2.2.0.0108_amd64.deb 地址https://mirrors.aliyun.com/deepin/pool/non-free/s/sogoupinyin

**Comment by zarzen** [comment]
@YaboSun 感谢！解决了

**Comment by fengcs** [comment]
使用谷歌拼音输入法，不吃带毛猪

**Comment by oPiZiL** [comment]
卸载之后微信直接都没法切换输入法了
