### ISSUE TITLE
启动器图标显示问号

### ISSUE THREAD

**Issue by NeilBian** [zq1997/deepin-wine#8]
启动器图标显示问号

**Comment by zq1997** [comment]
似乎与 [https://github.com/wszqkzqk/deepin-wine-ubuntu/issues/183](https://github.com/wszqkzqk/deepin-wine-ubuntu/issues/183) 问题一样
但是无法复现

**Comment by NeilBian** [comment]
删除deepin，重新安装之后可以了




    


在2019年09月23日 11:21，张强 写道： 似乎与 wszqkzqk/deepin-wine-ubuntu#183 问题一样

但是无法复现



—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.

[

{

"@context": "http://schema.org",

"@type": "EmailMessage",

"potentialAction": {

"@type": "ViewAction",

"target": "https://github.com/zq1997/deepin-wine/issues/8?email_source=notifications\u0026email_token=AKT3YYTYVZG3MLJFGF5IABLQLAY2BA5CNFSM4IZF4S2KYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOD7JWUUY#issuecomment-533949011",

"url": "https://github.com/zq1997/deepin-wine/issues/8?email_source=notifications\u0026email_token=AKT3YYTYVZG3MLJFGF5IABLQLAY2BA5CNFSM4IZF4S2KYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOD7JWUUY#issuecomment-533949011",

"name": "View Issue"

},

"description": "View this Issue on GitHub",

"publisher": {

"@type": "Organization",

"name": "GitHub",

"url": "https://github.com"

}

}

]
