### ISSUE TITLE
前几天安装正常，昨天今天安装的qq字体和菜单都有问题

### ISSUE THREAD

**Issue by oldyangyagn** [zq1997/deepin-wine#81]
系统是ubuntu20、打不开菜单 屏幕上一直提示菜单已就绪，但就是打不开qq的设置，还有字体默认不会提示安装了，自带的wine qq的字体看着很别扭，字体发虚2020.9.16安装的有这个问题，前几天的没有。点击deepin wine qq设置菜单提示TXMENUWINDOW已就绪 就是打不开

**Comment by zq1997** [comment]
deepin更新v20了

**Comment by oldyangyagn** [comment]
> deepin]v20]

点击deepin wine qq设置菜单提示TXMENUWINDOW已就绪 就是打不开这个怎么办

**Comment by zq1997** [comment]
无法复现

**Comment by zelphar** [comment]
主要问题应该是之前可以通过Noto Sans CJK SC Regular来替换字体，但是更新之后只能认到Noto Sans CJK SC了。
修改注册表
[HKEY_CURRENT_USER\Software\Wine\Fonts\Replacements]
将所有Noto Sans CJK SC Regular替换为Noto Sans CJK SC即可。
不过实际在我的环境下，替换之后依然会有一些字体显示为方框，或者突然假死只能强制退出的情况

**Comment by zq1997** [comment]
确实问题很大，但是不更新也不是个事，毕竟官方新版都出来了，旧版迟早被取代。不如早点放出来大家一起解决问题。

**Comment by zq1997** [comment]
我是干脆安装了全部windows字体解决问题。

**Comment by zelphar** [comment]
> 我是干脆安装了全部windows字体解决问题。

但好像听说直接装windows字体也会导致变卡什么的。。。字体就是永远的心病的感觉

**Comment by zq1997** [comment]
看README

**Comment by zelphar** [comment]
按照readme的方法做了，也安装了微软雅黑字体，成功一次，重启之后又不行了。然后不管我怎么重新设置都再也没有生效正常过。好像只有安装宋体才是稳定有效的方法，但是宋体显示效果很差，而且好像有其他兼容性问题。醉了
