### ISSUE TITLE
KUbuntu自动配置无效，只能通过配置过程详解的过程配置

### ISSUE THREAD

**Issue by i35010u** [zq1997/deepin-wine#84]

**Comment by zq1997** [comment]
信息？

**Comment by i35010u** [comment]
> 信息？

root@i35010u-AIPC:~# wget -O- https://deepin-wine.i-m.dev/setup.sh | sh
--2020-09-24 22:23:08--  https://deepin-wine.i-m.dev/setup.sh
Resolving deepin-wine.i-m.dev (deepin-wine.i-m.dev)... 157.230.37.202, 134.209.106.40, 2400:6180:0:d1::360:1001, ...
Connecting to deepin-wine.i-m.dev (deepin-wine.i-m.dev)|157.230.37.202|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 1176 (1.1K) [application/x-shellscript]
Saving to: ‘STDOUT’

-                                               100%[======================================================================================================>]   1.15K  --.-KB/s    in 0s      

2020-09-24 22:23:28 (30.0 MB/s) - written to stdout [1176/1176]

命中:1 http://dl.google.com/linux/chrome/deb stable InRelease
命中:2 http://mirrors.aliyun.com/ubuntu bionic InRelease                                                                                                                                      
命中:3 https://dl.winehq.org/wine-builds/ubuntu focal InRelease                                                                                                                               
获取:4 https://mirrors.tuna.tsinghua.edu.cn/ubuntu focal InRelease [265 kB]                                                                            
命中:5 https://mirrors.tuna.tsinghua.edu.cn/ubuntu focal-updates InRelease                               
命中:6 https://mirrors.tuna.tsinghua.edu.cn/ubuntu focal-backports InRelease
命中:7 https://mirrors.tuna.tsinghua.edu.cn/ubuntu focal-security InRelease
命中:8 https://mirrors.tuna.tsinghua.edu.cn/ubuntu focal-proposed InRelease                  
忽略:9 https://deepin-wine.i-m.dev focal InRelease                                           
忽略:10 https://deepin-wine.i-m.dev  InRelease                                                                                                                                                
错误:11 https://deepin-wine.i-m.dev focal Release                                                                                                                                             
  404  Not Found [IP: 157.230.37.202 443]
命中:12 https://deepin-wine.i-m.dev  Release                            
忽略:13 https://deepin-wine.i-m.dev  Release.gpg                        
错误:14 http://deb.torproject.org/torproject.org jessie InRelease       
  无法连接上 deb.torproject.org:80 (179.60.193.9)，连接超时
正在读取软件包列表... 完成                         
W: 目标 Packages (main/binary-amd64/Packages) 在 /etc/apt/sources.list:14 和 /etc/apt/sources.list:16 中被配置了多次
W: 目标 Packages (main/binary-i386/Packages) 在 /etc/apt/sources.list:14 和 /etc/apt/sources.list:16 中被配置了多次
W: 目标 Packages (main/binary-all/Packages) 在 /etc/apt/sources.list:14 和 /etc/apt/sources.list:16 中被配置了多次
W: 目标 Translations (main/i18n/Translation-zh_CN) 在 /etc/apt/sources.list:14 和 /etc/apt/sources.list:16 中被配置了多次
W: 目标 Translations (main/i18n/Translation-zh) 在 /etc/apt/sources.list:14 和 /etc/apt/sources.list:16 中被配置了多次
W: 目标 Translations (main/i18n/Translation-en) 在 /etc/apt/sources.list:14 和 /etc/apt/sources.list:16 中被配置了多次
W: 目标 DEP-11 (main/dep11/Components-amd64.yml) 在 /etc/apt/sources.list:14 和 /etc/apt/sources.list:16 中被配置了多次
W: 目标 DEP-11 (main/dep11/Components-all.yml) 在 /etc/apt/sources.list:14 和 /etc/apt/sources.list:16 中被配置了多次
W: 目标 DEP-11-icons-small (main/dep11/icons-48x48.tar) 在 /etc/apt/sources.list:14 和 /etc/apt/sources.list:16 中被配置了多次
W: 目标 DEP-11-icons (main/dep11/icons-64x64.tar) 在 /etc/apt/sources.list:14 和 /etc/apt/sources.list:16 中被配置了多次
W: 目标 DEP-11-icons-hidpi (main/dep11/icons-64x64@2.tar) 在 /etc/apt/sources.list:14 和 /etc/apt/sources.list:16 中被配置了多次
W: 目标 DEP-11-icons-large (main/dep11/icons-128x128.tar) 在 /etc/apt/sources.list:14 和 /etc/apt/sources.list:16 中被配置了多次
W: 目标 CNF (main/cnf/Commands-amd64) 在 /etc/apt/sources.list:14 和 /etc/apt/sources.list:16 中被配置了多次
W: 目标 CNF (main/cnf/Commands-all) 在 /etc/apt/sources.list:14 和 /etc/apt/sources.list:16 中被配置了多次
E: 仓库 “https://deepin-wine.i-m.dev focal Release” 没有 Release 文件。
N: 无法安全地用该源进行更新，所以默认禁用该源。
N: 参见 apt-secure(8) 手册以了解仓库创建和用户配置方面的细节。
W: 目标 Packages (main/binary-amd64/Packages) 在 /etc/apt/sources.list:14 和 /etc/apt/sources.list:16 中被配置了多次
W: 目标 Packages (main/binary-i386/Packages) 在 /etc/apt/sources.list:14 和 /etc/apt/sources.list:16 中被配置了多次
W: 目标 Packages (main/binary-all/Packages) 在 /etc/apt/sources.list:14 和 /etc/apt/sources.list:16 中被配置了多次
W: 目标 Translations (main/i18n/Translation-zh_CN) 在 /etc/apt/sources.list:14 和 /etc/apt/sources.list:16 中被配置了多次
W: 目标 Translations (main/i18n/Translation-zh) 在 /etc/apt/sources.list:14 和 /etc/apt/sources.list:16 中被配置了多次
W: 目标 Translations (main/i18n/Translation-en) 在 /etc/apt/sources.list:14 和 /etc/apt/sources.list:16 中被配置了多次
W: 目标 DEP-11 (main/dep11/Components-amd64.yml) 在 /etc/apt/sources.list:14 和 /etc/apt/sources.list:16 中被配置了多次
W: 目标 DEP-11 (main/dep11/Components-all.yml) 在 /etc/apt/sources.list:14 和 /etc/apt/sources.list:16 中被配置了多次
W: 目标 DEP-11-icons-small (main/dep11/icons-48x48.tar) 在 /etc/apt/sources.list:14 和 /etc/apt/sources.list:16 中被配置了多次
W: 目标 DEP-11-icons (main/dep11/icons-64x64.tar) 在 /etc/apt/sources.list:14 和 /etc/apt/sources.list:16 中被配置了多次
W: 目标 DEP-11-icons-hidpi (main/dep11/icons-64x64@2.tar) 在 /etc/apt/sources.list:14 和 /etc/apt/sources.list:16 中被配置了多次
W: 目标 DEP-11-icons-large (main/dep11/icons-128x128.tar) 在 /etc/apt/sources.list:14 和 /etc/apt/sources.list:16 中被配置了多次
W: 目标 CNF (main/cnf/Commands-amd64) 在 /etc/apt/sources.list:14 和 /etc/apt/sources.list:16 中被配置了多次
W: 目标 CNF (main/cnf/Commands-all) 在 /etc/apt/sources.list:14 和 /etc/apt/sources.list:16 中被配置了多次

**Comment by i35010u** [comment]
这是我已经手动配置之后的信息

**Comment by zq1997** [comment]
你的旧有源存在问题
