### ISSUE TITLE
taobaowangang的使用方法是什么？

### ISSUE THREAD

**Issue by iyagicom** [zq1997/deepin-wine#87]
root@iyagi-Inspiron-7559:/home/iyagi# wget -O- https://deepin-wine.i-m.dev/setup.sh | sh
.......................
무시:1 https://deepin-wine.i-m.dev  InRelease         
받기:2 https://deepin-wine.i-m.dev  Release [1,221 B]
무시:3 https://deepin-wine.i-m.dev  Release.gpg
받기:4 https://deepin-wine.i-m.dev  Packages [14.6 kB]
내려받기 15.8 k바이트, 소요시간 3초 (4,781 바이트/초)
패키지 목록을 읽는 중입니다... 완료

大功告成，现在可以试试安装deepin-wine软件了，
安装/更新TIM：sudo apt-get install deepin.com.qq.office
安装/更新QQ：sudo apt-get install deepin.com.qq.im
安装/更新微信：sudo apt-get install deepin.com.wechat

如果觉得有用，请到 https://github.com/zq1997/deepin-wine 点个star吧

root@iyagi-Inspiron-7559:/home/iyagi# apt-get install deepin.com.wangwang

root@iyagi-Inspiron-7559:/home/iyagi# apt-get install deepin.com.taobaowangang

root@iyagi-Inspiron-7559:/home/iyagi# apt-get install deepin.com.wangwang
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package deepin.com.wangwang
E: Couldn't find any package by glob 'deepin.com.wangwang'
E: Couldn't find any package by regex 'deepin.com.wangwang'

两个都不安装

**Comment by zq1997** [comment]
deepin.com.taobao.wangwang

**Comment by iyagicom** [comment]
使用Kubuntu 20.10。
有以下错误。

root@iyagi-Inspiron-7559:/home/iyagi# apt-get install deepin.com.taobao.wangwang
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 libgirepository-1.0-1 : Breaks: python-gi (< 3.34.0-4~) but 3.30.4-1 is to be installed
E: Unable to correct problems, you have held broken packages.

**Comment by zq1997** [comment]
可能是main universe等源配置不全

**Comment by disburden** [comment]
我刚装了20.10,也遇到了这个问题,好像是20.10这个版本都有这个问题,看到好多人提问的,但是没有一个有答案
