### ISSUE TITLE
安装最新版微信，点击小程序提示：“该功能不支持当前操作系统版本”

### ISSUE THREAD

**Issue by Samge0** [zq1997/deepin-wine#89]
*如果你是Linux新手，请严格按照下面的模板来提问，你见过去公安局报案直接说“我钱丢了”但是不说时间地点经过的？请互相尊重，不要一上来什么信息都没有直接贴问题。*
*如果你对Linux比较熟悉，并且明白问题的根本原因出在哪里，甚至做了简单的复现，那自由表述即可，不必拘泥下面的模板。*

**系统版本**
Ubuntu 20.04.1 LTS

**桌面类型**
Gnome

**软件源列表**
`/etc/apt/sources.list.d/deepin-wine.i-m.dev.list:1:deb [trusted=yes] https://deepin-wine.i-m.dev /
/etc/apt/sources.list.d/linuxuprising-ubuntu-shutter-focal.list:1:deb http://ppa.launchpad.net/linuxuprising/shutter/ubuntu focal main
/etc/apt/sources.list.d/docker.list:1:deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable
/etc/apt/sources.list.d/google-chrome.list:3:deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main
/etc/apt/sources.list:5:deb http://cn.archive.ubuntu.com/ubuntu/ focal main restricted
/etc/apt/sources.list:10:deb http://cn.archive.ubuntu.com/ubuntu/ focal-updates main restricted
/etc/apt/sources.list:16:deb http://cn.archive.ubuntu.com/ubuntu/ focal universe
/etc/apt/sources.list:18:deb http://cn.archive.ubuntu.com/ubuntu/ focal-updates universe
/etc/apt/sources.list:26:deb http://cn.archive.ubuntu.com/ubuntu/ focal multiverse
/etc/apt/sources.list:28:deb http://cn.archive.ubuntu.com/ubuntu/ focal-updates multiverse
/etc/apt/sources.list:36:deb http://cn.archive.ubuntu.com/ubuntu/ focal-backports main restricted universe multiverse
/etc/apt/sources.list:46:deb http://security.ubuntu.com/ubuntu focal-security main restricted
/etc/apt/sources.list:48:deb http://security.ubuntu.com/ubuntu focal-security universe
/etc/apt/sources.list:50:deb http://security.ubuntu.com/ubuntu focal-security multiverse`

**问题描述**

1、我先安装了微信：
sudo apt-get install deepin.com.wechat

2、然后去微信官网下载最新exe文件，更新最新微信：
WINEPREFIX=~/.deepinwine/Deepin-WeChat/ deepin-wine wx295.exe

3、然后点击任意一个小程序，都提示“该功能不支持当前操作系统版本”。

4、看了 [官方论坛相关问题](https://developers.weixin.qq.com/community/develop/doc/00062892b0484063376a012ef5bc00?_at=1602472734071) ，有人是xp系统或winserver也出现这样的问题，讨论中有人有提到是版本问题，于是我尝试安装了微信2.7.1版本、微信2.8.0版本都无法解决问题。

5、可能是微信检测系统信息了，因为我在win系统跟mac系统上的pc微信都是可以正常打开小程序的，所以想了解一下，有没有办法绕过（或伪装）系统信息的检测呢，因为想在ubuntu下能使用小程序。。。谢谢

**Comment by qykong** [comment]
`WINEPREFIX=~/.deepinwine/Deepin-WeChat deepin-wine winecfg` 然后把系统版本改成windows7以上就可以了。但我发现小程序就算能打开也还是有些bug

**Comment by Samge0** [comment]
> `WINEPREFIX=~/.deepinwine/Deepin-WeChat deepin-wine winecfg` 然后把系统版本改成windows7以上就可以了。但我发现小程序就算能打开也还是有些bug

谢谢解答~

**Comment by 93Alliance** [comment]
执行 WINEPREFIX=~/.deepinwine/Deepin-WeChat deepin-wine winecfg 报未找到 deepin-wine命令
