### ISSUE TITLE
wget链接无法使用了

### ISSUE THREAD

**Issue by Stranger469** [zq1997/deepin-wine#9]
![image](https://user-images.githubusercontent.com/16164219/65835671-21fbf900-e324-11e9-87ce-4284c5173985.png)

**Comment by zq1997** [comment]
这个页面浏览器看看怎么样? https://deepin-wine.i-m.dev/

**Comment by Stranger469** [comment]
> 这个页面浏览器看看怎么样? https://deepin-wine.i-m.dev/

我本人在境外，显示无法访问，挂了国内的梯子后显示该网站没有备案…

**Comment by zq1997** [comment]
https
s不能丢啊，最近用的阿里云，可能国外访问有问题吧

**Comment by zq1997** [comment]
我试了下翻墙国外确实访问不了，然后国内http没s会说没备案

**Comment by Stranger469** [comment]
> 我试了下翻墙国外确实访问不了，然后国内http没s会说没备案

不行，国内也无法使用

**Comment by Stranger469** [comment]
> 我试了下翻墙国外确实访问不了，然后国内http没s会说没备案

无法提供安全链接，可能是ssl证书或者其他地方出问题了

**Comment by zq1997** [comment]
我在国内看https都正常啊，明天我具体找一下原因

**Comment by Stranger469** [comment]
> 我在国内看https都正常啊，明天我具体找一下原因

好的，感谢

**Comment by zq1997** [comment]
被阿里云坑了，HTTPS未备案在有些网络可以访问（比如我的），有些网络不能（比如你的），换到香港去了，看看能用吗？

**Comment by Stranger469** [comment]
> 被阿里云坑了，HTTPS未备案在有些网络可以访问（比如我的），有些网络不能（比如你的），换到香港去了，看看能用吗？

可以使用了，感谢🙏
