### ISSUE TITLE
软件无法共存：安装QQ时需卸载一些其他软件依赖的软件包

### ISSUE THREAD

**Issue by CBlbj** [zq1997/deepin-wine#90]
**系统版本**
ubuntu 20.04

**桌面类型**
Gnome
**软件源列表**
/etc/apt/sources.list.d/google-chrome.list:3:deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main
/etc/apt/sources.list.d/deepin-wine.i-m.dev.list:1:deb [trusted=yes] https://deepin-wine.i-m.dev /
/etc/apt/sources.list:5:deb http://mirrors.aliyun.com/ubuntu/ focal main restricted
/etc/apt/sources.list:10:deb http://mirrors.aliyun.com/ubuntu/ focal-updates main restricted
/etc/apt/sources.list:16:deb http://mirrors.aliyun.com/ubuntu/ focal universe
/etc/apt/sources.list:18:deb http://mirrors.aliyun.com/ubuntu/ focal-updates universe
/etc/apt/sources.list:26:deb http://mirrors.aliyun.com/ubuntu/ focal multiverse
/etc/apt/sources.list:28:deb http://mirrors.aliyun.com/ubuntu/ focal-updates multiverse
/etc/apt/sources.list:36:deb http://mirrors.aliyun.com/ubuntu/ focal-backports main restricted universe multiverse
/etc/apt/sources.list:46:deb http://mirrors.aliyun.com/ubuntu/ focal-security main restricted
/etc/apt/sources.list:48:deb http://mirrors.aliyun.com/ubuntu/ focal-security universe
/etc/apt/sources.list:50:deb http://mirrors.aliyun.com/ubuntu/ focal-security multiverse
/etc/apt/sources.list:57:deb http://archive.ubuntu.com/ubuntu/ trusty main universe restricted multiverse

**问题描述**
成功安装deepin-wine后，安装QQ
`sudo apt-get install deepin.com.qq.im`输出：
`下列软件包将被【卸载】：
  libjpeg62:i386 libpython-stdlib python python-minimal python-pygraphviz
  python-support
`
其中软件包python*是另一个仿真软件所必需的，难受....
非常期待您的回复。

**Comment by zq1997** [comment]
/etc/apt/sources.list:57:
`trusty`是什么

**Comment by CBlbj** [comment]
> /etc/apt/sources.list:57:
> `trusty`是什么

不太清楚，这个应该是ubuntu默认的源

**Comment by zq1997** [comment]
应该不是

**Comment by CBlbj** [comment]
这个会影响后面的qq安装吗？

**Comment by zq1997** [comment]
可能是已有的软件依赖出了问题

**Comment by CBlbj** [comment]
我之前先安装的qq、微信，可以用。然后装那个仿真软件（ns3）的时候，需要依赖包python-minimal，输入：
`sudo apt-get install python-minimal`
输出：
```
下列软件包将被【卸载】：
  deepin-wine-helper:i386 deepin-wine-plugin-virtual deepin.com.qq.im:i386
  deepin.com.wechat:i386 mercurial mercurial-common python-dbus python-gi
  python-gobject python-gobject-2 python2 python2-minimal
```

**Comment by CBlbj** [comment]
> 可能是已有的软件依赖出了问题

是不是以为Python2和Python不兼容啊

**Comment by zq1997** [comment]
不清楚，没有遇到过
