### ISSUE TITLE
发送大的图片时卡死

### ISSUE THREAD

**Issue by pz9042** [zq1997/deepin-wine#93]
**系统版本**
Ubuntu 18.04.4 LTS

**桌面类型**
GNOME

**软件源列表**
/etc/apt/sources.list.d/notepadqq-team-ubuntu-notepadqq-bionic.list:1:deb http://ppa.launchpad.net/notepadqq-team/notepadqq/ubuntu bionic main
/etc/apt/sources.list.d/yarn.list:1:deb https://dl.yarnpkg.com/debian/ stable main
/etc/apt/sources.list.d/vscode.list:3:deb [arch=amd64] http://packages.microsoft.com/repos/vscode stable main
/etc/apt/sources.list.d/google-chrome.list:3:deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main
/etc/apt/sources.list.d/teamviewer.list:19:deb http://linux.teamviewer.com/deb stable main
/etc/apt/sources.list.d/bashtop-monitor-ubuntu-bashtop-bionic.list:1:deb http://ppa.launchpad.net/bashtop-monitor/bashtop/ubuntu bionic main
/etc/apt/sources.list.d/deepin-wine.i-m.dev.list:1:deb [trusted=yes] https://deepin-wine.i-m.dev /
/etc/apt/sources.list.d/home:llamaret.list:1:deb http://download.opensuse.org/repositories/home:/llamaret/KDE_Neon_18.04_universe/ /
/etc/apt/sources.list.d/dawidd0811-ubuntu-neofetch-bionic.list:1:deb http://ppa.launchpad.net/dawidd0811/neofetch/ubuntu bionic main
/etc/apt/sources.list.d/asbru-cm_asbru-cm.list:4:deb https://packagecloud.io/asbru-cm/asbru-cm/ubuntu/ bionic main
/etc/apt/sources.list.d/sogoupinyin.list:1:deb http://archive.ubuntukylin.com:10006/ubuntukylin xenial main
/etc/apt/sources.list:1:deb https://mirrors.tuna.tsinghua.edu.cn/ubuntu/ bionic main restricted universe multiverse
/etc/apt/sources.list:3:deb https://mirrors.tuna.tsinghua.edu.cn/ubuntu/ bionic-updates main restricted universe multiverse
/etc/apt/sources.list:5:deb https://mirrors.tuna.tsinghua.edu.cn/ubuntu/ bionic-backports main restricted universe multiverse
/etc/apt/sources.list:7:deb https://mirrors.tuna.tsinghua.edu.cn/ubuntu/ bionic-security main restricted universe multiverse
/etc/apt/sources.list:9:deb https://mirrors.tuna.tsinghua.edu.cn/ubuntu/ bionic-proposed main restricted universe multiverse
/etc/apt/sources.list:15:deb http://cn.archive.ubuntu.com/ubuntu/ bionic main restricted
/etc/apt/sources.list:20:deb http://cn.archive.ubuntu.com/ubuntu/ bionic-updates main restricted
/etc/apt/sources.list:26:deb http://cn.archive.ubuntu.com/ubuntu/ bionic universe
/etc/apt/sources.list:28:deb http://cn.archive.ubuntu.com/ubuntu/ bionic-updates universe
/etc/apt/sources.list:36:deb http://cn.archive.ubuntu.com/ubuntu/ bionic multiverse
/etc/apt/sources.list:38:deb http://cn.archive.ubuntu.com/ubuntu/ bionic-updates multiverse
/etc/apt/sources.list:46:deb http://cn.archive.ubuntu.com/ubuntu/ bionic-backports main restricted universe multiverse
/etc/apt/sources.list:56:deb http://security.ubuntu.com/ubuntu bionic-security main restricted
/etc/apt/sources.list:58:deb http://security.ubuntu.com/ubuntu bionic-security universe
/etc/apt/sources.list:60:deb http://security.ubuntu.com/ubuntu bionic-security multiverse
/etc/apt/sources.list:62:deb https://dl.winehq.org/wine-builds/ubuntu/ cosmic main
/etc/apt/sources.list:65:deb https://dl.winehq.org/wine-builds/ubuntu/ bionic main
/etc/apt/sources.list:72:deb https://download.virtualbox.org/virtualbox/debian bionic contrib

**问题描述**
发送4.3M图片给其他用户时，微信卡死。发送4Kb的不会

**Comment by zq1997** [comment]
N卡正常，没有卡

**Comment by pz9042** [comment]
> N卡正常，没有卡

没看明白什么意思

**Comment by zq1997** [comment]
nvidia的显卡，测试发送5MB图片，没有发生卡顿现象
