### ISSUE TITLE
请问这个微信能否进行版本升级？

### ISSUE THREAD

**Issue by xiangdongping999** [zq1997/deepin-wine#94]
我是一个新人，刚刚接触linux不久。之前最开始用的是deepin20，由于时不时卡顿，近期更换了 linux mint 20 
按照这个步骤一步一步的安装了 微信。但是发现这个微信的版本比Deepin商店安装的要低。
请问这个如何能进行更新?还是无法更新？

**Comment by zq1997** [comment]
可以先参考README里面的更新方法

**Comment by xiangdongping999** [comment]
以了解，非常感谢。
