### ISSUE TITLE
依赖问题

### ISSUE THREAD

**Issue by on99** [zq1997/deepin-wine#99]
```
❯ sudo apt-get --fix-broken install com.qq.weixin.deepin
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 com.qq.weixin.deepin:i386 : Depends: libc6:i386 (>= 2.28) but 2.27-3ubuntu1.3 is to be installed
                             Recommends: libcups2:i386 but it is not going to be installed
                             Recommends: libglu1-mesa:i386 but it is not going to be installed or
                                         libglu1:i386
                             Recommends: libgsm1:i386 but it is not going to be installed
                             Recommends: libgssapi-krb5-2:i386 but it is not going to be installed
                             Recommends: libkrb5-3:i386 but it is not going to be installed
                             Recommends: libodbc1:i386 but it is not going to be installed
                             Recommends: libosmesa6:i386 but it is not going to be installed
                             Recommends: libv4l-0:i386 but it is not going to be installed
                             Recommends: libxcomposite1:i386 but it is not going to be installed
                             Recommends: libxslt1.1:i386 but it is not going to be installed
E: Unable to correct problems, you have held broken packages.
```

系统elementary os 5.1，基于 Ubuntu 18.04，我看[这里](https://pkgs.org/download/libc6-i386)发现libc6:i386在18.04里面最新的就是2.27，找不到2.28以上的安装包 :rofl: 这还有救吗？

**Comment by zq1997** [comment]
升级系统，20.04早就出了

或者手动下载更高版本的libc6安装，不保证安全性

**Comment by on99** [comment]
我自己下载 glibc 2.32 回来编译了个 libc:i386，请问在 `sudo apt-get install com.qq.weixin.deepin` 的时候有可能指定我自己编译的吗？升级操作系统有点麻烦，不能rolling update :rofl:

**Comment by zq1997** [comment]
自己编译怕不行吧？因为`dpkg`系统没有检测到这个版本的存在。
去ubuntu仓库单独下载个新版glibc.deb不行吗

**Comment by on99** [comment]
实在是没找到 18.04 的 libc6:i386 2.27 以上版本 :cry: 我尝试下载 20.04 的安装失败，我再想想办法

**Comment by Baloneo** [comment]
https://pkgs.org/download/libc6
里面有各个版本的 libc6，可以下载安装试试，可能会损坏依赖

**Comment by on99** [comment]
> https://pkgs.org/download/libc6
> 里面有各个版本的 libc6，可以下载安装试试，可能会损坏依赖

谢谢，我在上面的留言也有提到这个地址，可惜 Ubuntu 18.04 只有 2.27，没有更高的版本了 :rofl: 只能放弃

**Comment by Baloneo** [comment]
> > https://pkgs.org/download/libc6
> > 里面有各个版本的 libc6，可以下载安装试试，可能会损坏依赖
> 
> 谢谢，我在上面的留言也有提到这个地址，可惜 Ubuntu 18.04 只有 2.27，没有更高的版本了  只能放弃

其它版本有高版本

**Comment by on99** [comment]
> > > https://pkgs.org/download/libc6
> > > 里面有各个版本的 libc6，可以下载安装试试，可能会损坏依赖
> > 
> > 
> > 谢谢，我在上面的留言也有提到这个地址，可惜 Ubuntu 18.04 只有 2.27，没有更高的版本了  只能放弃
> 
> 其它版本有高版本

高版本的libc6-i386依赖高版本的libc6，高版本的libc6依赖很多其它高版本的库 :rofl: 

```
❯ sudo dpkg -i libc6-i386_2.31-0ubuntu9_amd64.deb
Selecting previously unselected package libc6-i386.
(Reading database ... 200201 files and directories currently installed.)
Preparing to unpack libc6-i386_2.31-0ubuntu9_amd64.deb ...
Unpacking libc6-i386 (2.31-0ubuntu9) ...
Replaced by files in installed package libc6:i386 (2.27-3ubuntu1.3) ...
dpkg: dependency problems prevent configuration of libc6-i386:
 libc6-i386 depends on libc6 (= 2.31-0ubuntu9); however:
  Version of libc6:amd64 on system is 2.27-3ubuntu1.3.

dpkg: error processing package libc6-i386 (--install):
 dependency problems - leaving unconfigured
Processing triggers for libc-bin (2.27-3ubuntu1.3) ...
Errors were encountered while processing:
 libc6-i386
```

```
❯ sudo dpkg -i libc6_2.31-0ubuntu9_amd64\ \(2\).deb
dpkg: regarding libc6_2.31-0ubuntu9_amd64 (2).deb containing libc6:amd64:
 libc6:amd64 breaks locales (<< 2.31)
  locales (version 2.27-3ubuntu1.3) is present and installed.

dpkg: error processing archive libc6_2.31-0ubuntu9_amd64 (2).deb (--install):
 installing libc6:amd64 would break locales, and
 deconfiguration is not permitted (--auto-deconfigure might help)
Errors were encountered while processing:
 libc6_2.31-0ubuntu9_amd64 (2).deb
```

**Comment by zq1997** [comment]
系统底层库，贸然改动比较危险

**Comment by hu674494966** [comment]
> 升级系统，20.04早就出了，不知道elementary os跟进了没
> 
> 或者手动下载更高版本的libc6安装，不保证安全性
> 
> 或者看看https://github.com/wszqkzqk/deepin-wine-ubuntu 的项目，他的的安装包已经下载好了，旧版可用。而这个项目里的安装包都是从deepin官网实时摘下来的，只有最新版，没有办法考虑旧版。

我也遇到了类似的问题，Ubuntu16.04 报错如下：
The following packages have unmet dependencies:
 com.qq.weixin.deepin:i386 : Depends: libc6:i386 (>= 2.28) but 2.23-0ubuntu11.2 is to be installed
                             Depends: libgphoto2-6:i386 (>= 2.5.10) but 2.5.9-3 is to be installed
                             Depends: libgphoto2-port12:i386 (>= 2.5.10) but 2.5.9-3 is to be installed
                             Depends: libvkd3d1:i386 (>= 1.0) but it is not going to be installed
                             Recommends: libsdl2-2.0-0:i386 but it is not going to be installed
E: Unable to correct problems, you have held broken packages.
这个现在有办法解决吗？

**Comment by rangerzhou** [comment]
> > > > https://pkgs.org/download/libc6
> > > > 里面有各个版本的 libc6，可以下载安装试试，可能会损坏依赖
> > > 
> > > 
> > > 谢谢，我在上面的留言也有提到这个地址，可惜 Ubuntu 18.04 只有 2.27，没有更高的版本了  只能放弃
> > 
> > 
> > 其它版本有高版本
> 
> 高版本的libc6-i386依赖高版本的libc6，高版本的libc6依赖很多其它高版本的库 
> 
> ```
> ❯ sudo dpkg -i libc6-i386_2.31-0ubuntu9_amd64.deb
> Selecting previously unselected package libc6-i386.
> (Reading database ... 200201 files and directories currently installed.)
> Preparing to unpack libc6-i386_2.31-0ubuntu9_amd64.deb ...
> Unpacking libc6-i386 (2.31-0ubuntu9) ...
> Replaced by files in installed package libc6:i386 (2.27-3ubuntu1.3) ...
> dpkg: dependency problems prevent configuration of libc6-i386:
>  libc6-i386 depends on libc6 (= 2.31-0ubuntu9); however:
>   Version of libc6:amd64 on system is 2.27-3ubuntu1.3.
> 
> dpkg: error processing package libc6-i386 (--install):
>  dependency problems - leaving unconfigured
> Processing triggers for libc-bin (2.27-3ubuntu1.3) ...
> Errors were encountered while processing:
>  libc6-i386
> ```
> 
> ```
> ❯ sudo dpkg -i libc6_2.31-0ubuntu9_amd64\ \(2\).deb
> dpkg: regarding libc6_2.31-0ubuntu9_amd64 (2).deb containing libc6:amd64:
>  libc6:amd64 breaks locales (<< 2.31)
>   locales (version 2.27-3ubuntu1.3) is present and installed.
> 
> dpkg: error processing archive libc6_2.31-0ubuntu9_amd64 (2).deb (--install):
>  installing libc6:amd64 would break locales, and
>  deconfiguration is not permitted (--auto-deconfigure might help)
> Errors were encountered while processing:
>  libc6_2.31-0ubuntu9_amd64 (2).deb
> ```

大兄弟，问题解决了吗，我 18.04 强行升级 libc6 出问题了，

**Comment by on99** [comment]
> 大兄弟，问题解决了吗，我 18.04 强行升级 libc6 出问题了，

强行升级太危险, 应该是解决不了的... 我放弃了

**Comment by Baloneo** [comment]
> > > > > https://pkgs.org/download/libc6
> > > > > 里面有各个版本的 libc6，可以下载安装试试，可能会损坏依赖
> > > > 
> > > > 
> > > > 谢谢，我在上面的留言也有提到这个地址，可惜 Ubuntu 18.04 只有 2.27，没有更高的版本了  只能放弃
> > > 
> > > 
> > > 其它版本有高版本
> > 
> > 
> > 高版本的libc6-i386依赖高版本的libc6，高版本的libc6依赖很多其它高版本的库
> > ```
> > ❯ sudo dpkg -i libc6-i386_2.31-0ubuntu9_amd64.deb
> > Selecting previously unselected package libc6-i386.
> > (Reading database ... 200201 files and directories currently installed.)
> > Preparing to unpack libc6-i386_2.31-0ubuntu9_amd64.deb ...
> > Unpacking libc6-i386 (2.31-0ubuntu9) ...
> > Replaced by files in installed package libc6:i386 (2.27-3ubuntu1.3) ...
> > dpkg: dependency problems prevent configuration of libc6-i386:
> >  libc6-i386 depends on libc6 (= 2.31-0ubuntu9); however:
> >   Version of libc6:amd64 on system is 2.27-3ubuntu1.3.
> > 
> > dpkg: error processing package libc6-i386 (--install):
> >  dependency problems - leaving unconfigured
> > Processing triggers for libc-bin (2.27-3ubuntu1.3) ...
> > Errors were encountered while processing:
> >  libc6-i386
> > ```
> > 
> > 
> > ```
> > ❯ sudo dpkg -i libc6_2.31-0ubuntu9_amd64\ \(2\).deb
> > dpkg: regarding libc6_2.31-0ubuntu9_amd64 (2).deb containing libc6:amd64:
> >  libc6:amd64 breaks locales (<< 2.31)
> >   locales (version 2.27-3ubuntu1.3) is present and installed.
> > 
> > dpkg: error processing archive libc6_2.31-0ubuntu9_amd64 (2).deb (--install):
> >  installing libc6:amd64 would break locales, and
> >  deconfiguration is not permitted (--auto-deconfigure might help)
> > Errors were encountered while processing:
> >  libc6_2.31-0ubuntu9_amd64 (2).deb
> > ```
> 
> 大兄弟，问题解决了吗，我 18.04 强行升级 libc6 出问题了，

升级Linux系统

**Comment by rangerzhou** [comment]
> > 大兄弟，问题解决了吗，我 18.04 强行升级 libc6 出问题了，
> 
> 强行升级太危险, 应该是解决不了的... 我放弃了

命令行执行了 mintupdate ，一顿 update，居然好了……

**Comment by leijue222** [comment]
所以现在的版本不支持ubuntu18.04了吗？仅20及以上才行？
@zq1997 
我安装也是报错：
```
下列软件包有未满足的依赖关系：
 com.qq.weixin.deepin:i386 : 依赖: libc6:i386 (>= 2.28) 但是 2.27-3ubuntu1.4 正要被安装
                             推荐: libsdl2-2.0-0:i386 但是它将不会被安装
E: 无法修正错误，因为您要求某些软件包保持现状，就是它们破坏了软件包间的依赖关系。
```
